### ISSUE TITLE
Unicode characters are not handled properly in LaTeX exports

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#101]
I've placed the characters &pi; (`&pi;`) and &rarr; (`&rarr;`) in a novelWriter document. When I export to LaTeX and attempt PDF conversion using TeXshop two errors present themselves:

```
./Dick_and_Jane.tex:66: Package inputenc Error: Unicode character â (U+2192)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.66 Jack and Jill â
                       the hill to fetch a pail of water.
? 

./Dick_and_Jane.tex:68: Package inputenc Error: Unicode character Ï (U+03C0)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                   
                                                  
l.68 Puff likes to eat Ï
                          just like humans.
```

The two unicode characters don't appear in the PDF output after we press <kbd>Return</kbd> twice to bypass the error messages. 

I had thought the matter resolved with the addition of the `latexcodec` but I think I've jumped the gun and tested this prematurely.

**Comment by vkbo** [comment]
The `latexcodec` documentation states that it isn't complete. I suppose all we can do is identify the problems and add them to the replacement dictionary manually, or report them to the package developers.

I will add these two, and check a few others of similar type.

**Comment by johnblommers** [comment]
I've found a workaround. If the intention is to export to LaTeX then the writer can simply insert the LaTeX code for the symbols they want. So:

- PI can be presented as $\pi$ 
- RIGHTARROW can be represented as $\rightarrow$

novelWriter already passes the LaTeX codes directly into the LaTeX output file where it will present correctly when converted to PDF. I'm a [Gummi](https://github.com/alexandervdm/gummi) fan and this worked for me.

**Comment by vkbo** [comment]
Yes, the `latexcodec` package leaves already correct LaTeX formatted text alone.

Only paragraphs and heading text is encoded with this package though, but this is certainly a workable solution if LaTeX is the only export used. I will add it to the documentation.

**Comment by johnblommers** [comment]
Comment.

Writers that include LaTeX in their novels are probably a rare breed and will know how to handle problems they encounter using it in novelWriter.

For example. I created a LaTeX math formula that contained subscripts like this:

`$$f(x)=a_{0}+a_{1}x$$`

but on exporting this with novelWriter the subscript character `_` found itself escaped as `\_` in the `.tex` export file. The workaround is to instead use the `\sb` LaTeX syntax:

`$$f(x)=a\sb{0}+a\sb{1}x$$`

**Comment by vkbo** [comment]
Yeah, that's far beyond what is intended usage of novelWriter. It's for writing plain text. The LaTeX export is only intended for generating PDFs of plain text quickly.

**Comment by vkbo** [comment]
LaTeX export will not be included in the new Project Build Tool, and the current Export tool will be removed. This issue will therefore not be addressed. Closing it.
