### ISSUE TITLE
Hide or disable session timer completely

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1029]
**Current situation:**
The session timer is visible on the bottom right in the application window.

**Problem:**
I'm starting to get anxious when the clock starts ticking. The result is I'm leaving the application closed when in fact it would be good for productivity to just leave it open and read through the current progress - which includes opening documents, so the clock starts ticking again... even though I'm not working. Human psychology amirite, why is this stressing me out?

**Proposed solution(s):**
- Add an option in the settings that toggles the visibility of the timer on and off.
- Add an option in the settings that completely disables the logging of time (even for Writing Statistics).

Thanks for your consideration o7

**Comment by vkbo** [comment]
The whole timing and logging feature is to support writing sprints and daily goals. No data is logged if you don't make any changes during a session, so if you just want to read through, then there are no entries added to the log. You can reduce the time it takes to pause the clock from the settings as well. The minimum value is 0.5 minutes.

I suppose I can add a setting to hide the timer in the status bar. As for the session logging, I can perhaps add switches to show/hide the session length and idle time in the statistics display.
