### ISSUE TITLE
Add a modifier to the scene header for hard breaks

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1050]
Since both the level one and two headers have an exclamation point mode to modify the way the build tool processes the header, this can also be added to the level three scene header.

The main use case here is to distinguish between hard and soft scene breaks, which users may or may not use depending on how they structure the story. The build tool should take into the account and apply a different formatting rule for modified scene headers. Like for instance add an empty paragraph but no separator.

With the redesign of the build tool, there is more room to add more customisation options to headers, so this shouldn't be a problem.

**Edit 03.03.2024:** I'm leaning towards having an exception for hard scene breaks and assume the regular scenes are soft breaks. So, in other words:

* `### Scene Title` is a regular (soft) scene break.
* `###! Scene Title` is a hard scene break.

Since this only affects formatting of headings in the manuscript build, and nothing else, it doesn't really matter which way it is, but the assumption is that hard breaks are less common.

**Comment by awqk** [comment]
It seems scene headers are automatically hidden after chapter headers. In a short story, there wouldn't be chapters, so this auto-hide should probably also happen after the title header (or all higher level headers).

**Comment by vkbo** [comment]
> It seems scene headers are automatically hidden after chapter headers. In a short story, there wouldn't be chapters, so this auto-hide should probably also happen after the title header (or all higher level headers).

That's a bug. It should only do that for static text (scene separators). Please make a separate ticket, and I'll make a fix.
