### ISSUE TITLE
Remove already present spaces when inserting non-breaking spaces

### ISSUE THREAD

**Issue by aaribaud** [vkbo/novelWriter#1061]
This is a follow-up to https://github.com/vkbo/novelWriter/issues/703 but the scope is slightlydifferent, as 703 is about *where* to auto-insert non-breaking spaces whereas this request is about *how*.

In French (yes, again, sorry), double punctuation such as colons, semicolons, question marks, etc must be preceded by non-breaking (and thin), so I configured NovelWriter to handle this.

However, I have the habit of *typing* these spaces.

So, say I type something like `o`, `u`, `i`, _spacebar_, `?`.

What NovelWriter actually inserts is `o`, `u`, `i`, _normal space_ (typed), __non-breaking thin space__ (auto-inserted), `?`.

That's one space too many, and it forces me to manually edit out the normal space.

Would it be possible to make NovelWriter check for, and remove, normal spaces before it auto-inserts a non-breaking space?

**Comment by vkbo** [comment]
Sure, I can add this as an extension to the other feature. I would just make sure it strips any existing spaces before triggering this feature. It could also be an option of #1045 in addition in case some are missed.

I have a pretty big backlog of features now, grouped into three upcoming releases, so it may take a while. I can piggyback it on the #1045 feature anyway, so for 1.9.

**Comment by vkbo** [comment]
Turns out this only required three new lines of code, so it has been added now. It will be included in the 1.7 release.
