### ISSUE TITLE
Export to odt keeps the document in English

### ISSUE THREAD

**Issue by Karduin** [vkbo/novelWriter#1073]
Linux Mint 20.3 and Windows 10.

User interface set to French and project set to French.

Exporting to odt keeps the document in English in libreoffice.

![export_to_odt](https://user-images.githubusercontent.com/34542832/170277468-0a07d3a8-b9a4-4eb9-a155-73aae33a4d01.png)

**Comment by vkbo** [comment]
Thanks for reporting this. All the code to set this correctly is in place, but it was either never properly connected or has been broken at some point. It's an easy fix.
