### ISSUE TITLE
Opening document view doesn't work after resizing

### ISSUE THREAD

**Issue by TannersAndRodents** [vkbo/novelWriter#1085]
Resizing the document view all to the right doesn't close the document view, but hides the view instead. Thus, trying to open the document view again results in no visible change.

### Reproduction steps

Open a new project with example files, grab the divider between editor and document view and pull it all the way to the right until it hides. Then, click on a chapter and use "View Document". 

### Expected behavior

Viewer pops up on the right side, taking half the space of the editor. (Like closing the document viewer with the button "Close the document" and then viewing a chapter does)

### Actual behavior

No visible change. The viewer is still open, hidden on the right side, and can be opened again by resizing (grabbing the divider and pulling to the left).

This behavior may be unintuitive, because the sudden resizing at the far right suggests the viewer has been closed.

My ideas:

- Let resizing all to the right actually close the viewer like the button does
- Introduce a minimal size just as the editor has, forcing the user to use the close button
- Keep the behavior of the divider, but let opening the viewer via the Project tree resize the viewer as if it had been closed

**Comment by vkbo** [comment]
Thanks! The resize to zero feature should be disabled for that splitter, but the setting may have been lost at some point.

**Comment by vkbo** [comment]
The setting seems to have been intentional, but I agree that it is inconvenient.

New behaviour is as your second point suggests. The minimum size is enforced and the close button (or menu entry / shortcut) is the only option.

Anyway, fixed in `patch` and `main`. I may make a 1.6.3 release of this if more issues are found.

**Comment by TannersAndRodents** [comment]
Nice, thank you!
