### ISSUE TITLE
"insert non-breaking space before" feature makes synopsis comment feature harder to use

### ISSUE THREAD

**Issue by aaribaud** [vkbo/novelWriter#1090]
* A clear and concise description of what the bug is

When the "insert non-breaking space before" feature is enabled, and one types "% Synopsis:", a space is applied before the colon, causing the comment to not be re recognized as a synopsis comment.

* Steps to reproduce the behaviour:

  * Make sure the "insert non-breaking space before" feature is enabled;
  * Create a scene;
  * Type "% Synopsis:" without a space before the colon.
  * A space was inserted and the comment is not recognized as a synopsis comment.

* A clear and concise description of what you expected to happen

  * No space should be inserted and the comment should be recognized as a synopsis comment.

**Comment by vkbo** [comment]
Hmm, this is a tricky one because the two features are in conflict. The @ tags seem to accept a space before the colon in the syntax, so the simplest solution is to let the synopsis tag do so too.

**Comment by vkbo** [comment]
Fixed. I solved it by instead checking for the special cases where a space should not be inserted before a colon. That is, if the line starts with an `@`, or for the colon in the `% synopsis:` keyword. It was a fairly simple fix after all.

I'll release it as part of 1.6.3 tomorrow or one of the following days.
