### ISSUE TITLE
Appimage Distribution

### ISSUE THREAD

**Issue by Ryex** [vkbo/novelWriter#1091]
## Proposal 
I think it would be great if novelWriter was able to be downloaded as an [Appimage](https://appimage.org/). 

Appimages are a self contained runtime much like how OSX applications are distributed but for Linux that is Distro agnostic. With an Appimage you simply download a single exactable file and run it. A filesystem is transparently mounted in the background allowing the program to run with all of it's dependencies contained.

Thanks to the tools around Appimage the only real hard part is getting a python build build that is easily portable.

Good thing the hard work has already been done for us with [python-appimage](https://github.com/niess/python-appimage)

https://python-appimage.readthedocs.io/en/latest/apps/#simple-packaging

## Initial Testing

I made a simple directory `appimage/novelwriter` under the project, copied the relevant files into it and made some small edits to them, provided the absolute path to the source via a `requirements.txt`, and ran the command
```
~/Projects/novelWriter/appimage $ python-appimage build app -p 3.11 novelwriter  
[2022-07-07 17:02:31,604] EXTRACT  python3.11.0-cp311-cp311-manylinux2010_x86_64.AppImage
[2022-07-07 17:02:34,551] BUNDLE   novelwriter.desktop
[2022-07-07 17:02:34,552] BUNDLE   novelwriter.png
[2022-07-07 17:02:36,504] BUNDLE   ~/Projects/novelWriter/
[2022-07-07 17:02:42,183] BUNDLE   entrypoint.sh
[2022-07-07 17:02:42,183] BUILD    AppDir
```

and out popped a working `novelWriter-x86_64.AppImage` running with python 3.11 that integrated with my Gnome desktop correctly via [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher)

from this It should not be difficult to automate the creation of the metadata folder and subsequent building for an Appimage

### `appimage/novelwriter/entrypoint.sh`
```
{{ python-executable }} -sE ${APPDIR}/opt/python{{ python-version }}/bin/novelwriter "$@"
```

### `novelwriter.appdata.xml`
```
<?xml version="1.0" encoding="UTF-8"?>
<component type="desktop-application">
    <id>novelWriter</id>
    <metadata_license>GNU General Public License v3</metadata_license>
    <project_license>GNU General Public License v3</project_license>
    <name>novelWriter</name>
    <summary>A markdown-like text editor designed for writing novels and larger projects of many smaller plain text documents.</summary>
    <description>
        <p> novelWriter is a plain text editor designed for writing novels assembled from
            many smaller text documents. It uses a minimal formatting syntax inspired by
            Markdown, and adds a meta data syntax for comments, synopsis, and
            cross-referencing. It's designed to be a simple text editor that allows for
            easy organisation of text and notes, using human readable text files as
            storage for robustness.
        </p>
    </description>
    <launchable type="desktop-id">novelWriter.desktop</launchable>
    <url type="homepage">https://novelwriter.io/</url>
    <provides>
        <binary>novelWriter</binary>
    </provides>
</component>
```

### `novelwriter.desktop`
```
[Desktop Entry]
Type=Application
Name=novelWriter
Comment=A markdown-like text editor for planning and writing novels
Exec=novelwriter %f
Icon=novelwriter
Categories=Qt;Office;WordProcessor;
Terminal=false
MimeType=application/x-novelwriter-project;
```

### `requirements.txt`
```
~/Projects/novelWriter/
```

### `novelwriter.png`

copied from `setup/novelwriter.png`

**Comment by Ryex** [comment]
I've made a pull request with the added functionality.

I also made it so that the `build-appimage` command can configure the python build it uses in the resulting app-image

```
$ python setup.py build-appimage -h

Build Appimage
==============

usage: build_appimage [-h] [--linux-tag [LINUX_TAG]] [--python-version [PYTHON_VERSION]]

Build an Appimage

options:
  -h, --help            show this help message and exit
  --linux-tag [LINUX_TAG]
                        linux compatibility tag (e.g. manylinux1_x86_64) see https://python-appimage.readthedocs.io/en/latest/#available-python-appimages and
                        https://github.com/pypa/manylinux for a list of valid tags
  --python-version [PYTHON_VERSION]
                        python version (e.g. 3.10)

see https://appimage.org/ for more details
```

Just finished cleaning up the code a bit and double checking for anything I overlooked

**Comment by vkbo** [comment]
Thanks a lot! I'm in the middle of moving, so I'll look at it as soon as I have a chance.
