### ISSUE TITLE
Insert non-breaking space

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1118]
Sometimes it is necessary to insert an undivided space after words that have only one character. I would like to use the option in Tools - Preferences - Automation - Automatic Padding - Insert non-breaking space after, but this function with setting words (u, k, o, s, v, z, a, i, U, K, O, S, V, Z, A, I), nor (u,k,o,s,v,z,a,i,U,K,O,S,V,Z,A,I) works as I would need. In version 1.6.2 it always inserts spaces for these letters also in words, in version 1.6.3 it immediately shows this error when writing defined letter:

Environment:
novelWriter Version: 1.6.3
Host OS: linux (4.15.0-192-generic)
Python: 3.6.9 (0x30609f0)
Qt: 5.9.5, PyQt: 5.10.1
lxml: Unknown
enchant: 2.0.0

AttributeError:
'GuiDocEditor' object has no attribute 'allowSpaceBeforeColon'

Traceback:
  File "/usr/lib/python3/dist-packages/novelwriter/gui/doceditor.py", line 1097, in _docChange
    self._docAutoReplace(self.document().findBlock(thePos))

  File "/usr/lib/python3/dist-packages/novelwriter/gui/doceditor.py", line 1990, in _docAutoReplace
    if self.allowSpaceBeforeColon(theText, tCheck):

- - - - -
Linux Mint 19.2, Xfce

**Comment by vkbo** [comment]
Yeah, I spotted a bug there in the code. The call to `allowSpaceBeforeColon` is missing an underscore. I'll make a fix later today and release a 1.6.4 bugfix.

**Comment by vkbo** [comment]
As for the first part of your issue, are you asking if you can use this feature to insert spaces after single character words? If so, the answer is no. This is not the intended use for this feature. It only makes sense to use for punctuation, not letters. The feature is intended for adding spaces to quote marks and punctuation in for instance French and Spanish.

It works by checking the last typed character, and inserts a space before or after depending on your spec. It doesn't check anything before this character, so it would not know if the character is a part of a word or not. Essentially, it just replaces the typed character with a 'space + char' or 'char + space' for any char defined in the settings.

**Comment by snden** [comment]
Thank you for the explanation. No problem, after exporting to Libreoffice I can edit the text automatically there.
