### ISSUE TITLE
The Book Title Page is limited to two paragraphs

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#112]
My guess is that this is an undocumented feature of the _Book Title Page_ layout, that is, it's limited to two paragraphs. Any more are ignored when the manuscript is exported.

**Comment by vkbo** [comment]
Hmm, no, this is a bug. There are no such limitation coded into it.

I checked it, and it's not that it's limited, but that it drops the last paragraph if there's no line ending.

**Comment by vkbo** [comment]
Fixed in #113 

Title and partition pages have a page break added to it, which is currently only processed by the LaTeX converter. The page break was accidentally overwriting the last entry of the data array storing the tokenized text. The page break is now appended to it instead.
