### ISSUE TITLE
Pre-fill

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1123]
Would it be possible to give the user the option to pre-fill the newly created file? Some form, for example in Document - Pre-fill (I don't know what such a function is called exactly in English), so that the user can define somewhere in the form what could be in the newly created file. For example:

 \### New File
 \@ location:
 \@ char:
 \@ pov:
 \@ time:
 \@ object:
 \@ focus:
 \% Synopsis:

Or anything else he would write on the form.

**Comment by snden** [comment]
Or make copies of the file using ctrl + drag and drop.

**Comment by vkbo** [comment]
There is one suggestion already to add templates (#996) which I was thinking about implementing on both the project and document level.

There has also been discussions about making a new document wizard, or an advanced editor that can edit the meta data in a sort of GUI. However, the entire point of the plain text approach is to be able to avoid having to deal with GUI forms.

In the next release, the feature to add new documents will be enhanced to include some predefined options that will make it simpler to do these things. However, they still don't include the @ type keywords. A template could fix that. They will vary from project to project of course.

Release 1.9 will be focusing on the text editor. I will add some form of helper tool to assist in looking up defined tags. Possibly something similar to what you usually find in code editors. Like a dropdown list that helps you find relevant tags when you start typing after a @ keyword.

The ctrl + drag'n'drop is a good idea by the way. Could you please add that as a new feature suggestion? A copy document feature may be useful in general. I could even add a Templates root folder to pull them from. Hmm.

**By the way**, when you use the @ symbol in a post here, you usually end up tagging a bunch of people on GitHub, so you may want to wrap the line in backtick symbols `, which will avoid this.

**Comment by snden** [comment]
Thanks for the @ tagging warning, I can't quickly find a way to prevent this, just adding a backslash before the @ doesn't prevent it, so sorry I didn't realize that. Then I added a space after the character. Basically any other text could have been there.

**Comment by vkbo** [comment]
I think this issue can be closed. A lot of the complication of setting up the references has been reduced with the new auto-complete feature. It is also possible to auto-create new notes from undefined references.

Feature #996 will also take care of the more complex use cases, and templates are fully customisable. Documents can also currently be duplicated (although they have to be dragged and dropped afterwards) so I think when templates are added, this request is satisfied to a reasonable extent.
