### ISSUE TITLE
Custom inclusion of meta data in manuscript build

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1132]
Ref discussion in #801

It should be possible to select which meta data categories to include in the manuscript build. The writer may use some of the more specialised categories like Objects and Custom to track things only relevant to the writer, but of no direct value in the manuscript itself.

**Comment by vkbo** [comment]
FYI @snden, I'm adding this feature for the 2.4 release.

**Comment by vkbo** [comment]
Feature added for inclusion in 2.4

**Comment by snden** [comment]
Thank you, this is excellent news at the right time, as I will soon be sending the text of the book, which includes pictures, to the publisher. So I'll insert links to them directly in Novelwriter and it won't be necessary to make additional adjustments in the exported file. This is really a big help!

**Comment by vkbo** [comment]
Hmm, this is not about images or links though.

**Comment by snden** [comment]
Ah, I responded to our discussion #801
When I send a book to a publisher, I need to let him know where the image will be, what its file name is, or directly the path where it can be found, and its description in the text. So far I'm doing this by using a comment of the form:

% Note: [image-path] ../obrazky/chleba_se_slunecnicovymi_seminky.jpg
% Note: [image-description] Chleba se slunečnicovými semínky
% Note: [to-book-editor] Obrázky oříznout podle potřeby a barevně korigovat. Děkuji.

Then in Libreoffice I'll find all %Notes other than these three using a regular expression and delete them, and for these three I'll delete %Note: [image-path], %Note: [image-description], %Note: [to-book-editor ]. All that remains is the path, the description and a note to the editor.

When I need to see the images in a given place for review to check if they are physically present in the given location and the editor gets complete documents from me, I export the text in Novelwriter to html and add <a href ...> tags and save the html. It's laborious, but it works. Maybe we can find a way to automate it, preferably when exporting to .odt. Ideally with a choice whether to export the path as text _../obrazky/chleba_se_slunecnicovymi_seminky.jpg_ or as a visible image. The publisher needs everything in text form, and I also need to check it visually in some way. I don't know if it is understandable from my explanation, my English is not that good.

Do you think it can be solved somehow? Maybe using the @ custom tag?

**Comment by vkbo** [comment]
Sorry, I missed that response. It's better to start a new discussion than to post in a closed thread where I may not see it. I'm not sure I understand what it is you are requesting here. But start a discussion and maybe we can find a solution.
