### ISSUE TITLE
Add a How-To section in the docs

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1141]
Prompted by discussion #801, it may be useful to have a section in the documentation on how to use the features of novelWriter to do certain things new users often ask about. In this case, make notes in the manuscript to where illustrations should go in the finished novel.

Potential HowTos:

- [ ] #1287
- [ ] #1288
- [ ] #1289

**Comment by mvdkleijn** [comment]
Hi @vkbo Just to let you know that I'd be willing to help out writing some of these (or other) docs if desired. If you are interested, let me know.

**Comment by vkbo** [comment]
Sure, that would be helpful. It may make more sense to write these from the perspective of someone who uses novelWriter rather than me as the developer. I can add some of my intended tricks too of course.

I can make a template document for these howtos first, and then we can start adding them. I can probably do that later today. I have an idea how I want to do this.

**Comment by vkbo** [comment]
4 days later, I added the HowTo section 😄

**Comment by mvdkleijn** [comment]
Sooo... considering you marked the items in this list I guess I'll look around the issues for docs items that I can pick up. 😀

**Comment by vkbo** [comment]
Oh, yeah. This issue was just for adding the page in the docs. There were three other issues for specific HowTos, so if you have any ideas for other useful ones, maybe a discussions thread is a good place?
