### ISSUE TITLE
Fails to create a new project with examples

### ISSUE THREAD

**Issue by yurivict** [vkbo/novelWriter#1181]
I've built/installed the project from GirHub and it fails like this:

![image](https://user-images.githubusercontent.com/271906/196060284-99b00754-0111-4931-beef-8ae34d812a15.png)

novelwriter-1.6.5
Python-3.9
FreeBSD 13.1 STABLE

**Comment by vkbo** [comment]
Yeah, it means that the sample project is missing from the installed source. In the cloned repo it exists as a `sample` folder at the root of the repo, and for the release files, it is saved as `novelwriter/assets/sample.zip`. The new project wizard will look for either one of those.

If you use pip install, or `setup.py install`, you need to build the sample project first in order for it to be included in the install. You do that by running `setup.py sample` before running the install command.

I see that this is not mentioned in the Install from Source section of the [documentation](https://novelwriter.readthedocs.io/en/latest/int_source.html). I'll fix that.

**Comment by vkbo** [comment]
It is not really recommended to install from source except for testing and development. Both the sample project, the PDF manual, and the language files all need to be built before an install in order for it to be complete. These components require a bunch of dev tools to be installed. The manual needs LaTeX and sphinx, and the language files need the Qt5 dev tools.

**Comment by yurivict** [comment]
This is for the FreeBSD port which has to build from source.

**Comment by vkbo** [comment]
Ah, great! I read your bio and realised it may be. Hence my second comment.

I suggest having a look at the `setup/make_*` scripts for what needs to be built. All components can be built via the `setup.py` script. If you need any additional build steps there, that can be added.

I will update the docs anyway, as this info should really be there.
