### ISSUE TITLE
Wizard: Disable the "Add example notes" input toggle when all other toggles are off

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1192]
In the "Custom project options" page of the new project wizard, when all the "Add folder" input toggles are off, the "Add example notes" input toggle has therefore no purpose and should be disabled (and untoggled, not to confuse the user).

TLDR: This should not be possible:

![This should not be possible.](https://user-images.githubusercontent.com/16073344/196791013-5f2a140d-9963-437a-b462-f0f99f9f2850.png)

**Comment by vkbo** [comment]
It follows logically that nothing will be added, so I'm not sure it "should be impossible", But I can add the logic to disable the last switch if the others are off.
