### ISSUE TITLE
Following tags with spaces doesn't work

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1195]
From discussion thread:

> Hi folks, am loving novelWriter but have a question / issue:
>
> 1. Say I have a file called 'History of Saturn' under the 'Timeline' directory.
> 2. In the 'History of Saturn' file I add a tag: `@tag: History of Saturn`
> ![Screenshot from 2022-10-19 21-14-16](https://user-images.githubusercontent.com/52103420/196795206-b4b223a7-1a11-4cb3-a894-50213ba9be61.png)
>
> 3. I then reference that tag elsewhere in my notes: `@time: History of Saturn`
> ![Screenshot from 2022-10-19 21-15-15](https://user-images.githubusercontent.com/52103420/196795204-ab754c47-5d54-48ef-93af-d31b819f5127.png)
>
> There are no wiggly lines, and the tag seems to be reference correctly, but I can't follow that tag. Instead, I get: `Could not find the reference for tag 'Saturn'. It either doesn't exist, or the index is out of date. The index can be updated from the Tools menu, or by pressing F9.`
>
> ![Screenshot from 2022-10-19 21-15-59](https://user-images.githubusercontent.com/52103420/196795777-df38ba9a-77a3-40c2-9418-62a4f26fe2af.png)
>
> Does novelWriter support tags with spaces? Or should I use camelcase tags with no spaces?

_Originally posted by @wickertongue in https://github.com/vkbo/novelWriter/discussions/1194_

**Comment by vkbo** [comment]
By the way, which version are you running, @wickertongue?

**Comment by vkbo** [comment]
Note to self: The problem is in the `_followTag` function of the editor class.

**Comment by wickertongue** [comment]
Hi @vkbo! Thanks for getting back to me so quickly, here are the details you asked for:

Version: 1.6.5
Dated:  13/10/22
OS: PopOs (Linux)

**Comment by vkbo** [comment]
Thanks. I may fix it in the 1.6.x series too then. It will be a while longer until 2.0 is ready.

**Comment by wickertongue** [comment]
Another discovery! In case this helps, I get the error when trying both:
* ctrl + enter
* ctrl + click

On any tag.

I'll use underscores in the interim :)

**Comment by vkbo** [comment]
Should be fixed now. I just uploaded release 1.6.6.
