### ISSUE TITLE
Wording on property of files marked "exported"

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1196]
About the ["Toggle Exported"](https://crowdin.com/translate/novelwriter/1047/engb-es419#130060) string (and any similar ones), I don't like the wording of the "exported" property. It's a flag that _will matter_ potentially when building the document but it's currently referred to in _past tense_. That makes it confusing at least to me.

Not sure what a better wording is. "Marked for building", "Include during export", "Ready to export", or some such.

**Comment by vkbo** [comment]
I agree. I am actually planning to change it to Active/Inactive instead, which is more descriptive. 

You are right that it only makes sense in the context of building the project. But Active/Inactive makes it more of an allround flag that also makes sense during writing. It's intended as a less intrusive way of excluding a document without having to move it to "Archive".

I'll queue this up for the next release candidate.
