### ISSUE TITLE
novelWriter won't snap to 50% of screen when dragged to left or right hand screen edge

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#121]
I'm running GNOME on Linux. Most application windows, when dragged to the left edge of the screen will snap to occupy exactly half of the left hand side of the screen. Drag a window to the right hand edge of the screen and it snaps to fill the right half of  the screen. I make heavy use of this feature.

novelWriter refuses to honor this. 

It will go fullscreen when dragged to the top of the display.

**Update**. This is an artifact caused by [issue 120](https://github.com/vkbo/novelWriter/issues/120). When the Label field is very wide novelWriter can't fit the editor and document panes into the width equal to half a screen. When the Label is reasonably short novelWriter snaps both ways just fine.

Fix Issue 120 and you fix this issue as well.

**Comment by vkbo** [comment]
This too works just fine on my computer. Debian 10 with Gnome 3.30.
I don't control the behaviour of the window provided by the desktop environment, but if it's related to the other issue, then let's try fixing that first.

**Comment by vkbo** [comment]
Let me know if PR #122 fixed this issue as well.

**Comment by johnblommers** [comment]
That did the trick. You swatted two bugs with a single blow.

**Comment by vkbo** [comment]
Excellent!
