### ISSUE TITLE
Create a makedeb script for Debian based distributions

### ISSUE THREAD

**Issue by sbstn87** [vkbo/novelWriter#1226]
Hi,

could you perhaps create a [makedeb](https://www.makedeb.org/) script for novelWriter and publish it to [MPR](https://mpr.makedeb.org/)?

It would allow easy way of the installing latest version of novelWriter on all Debian based distributions. This works similar to AUR for Arch-based distros.

**Comment by vkbo** [comment]
I have looked at the link and the documentation, and I still have no idea what this is supposed to do.

I already release debian packages that work on at least Debian, Ubuntu and Mint.

**Comment by sbstn87** [comment]
Thank you for providing the .deb packages, appreciated.

Using makedeb and MPR allows automatic packaging of the latest available release for every Debian based distribution (so also Ubuntu and Mint), without adding new repositories or downloading a .deb file from the website.

User also does not have to rely on repository maintainers to add the application to the distribution's repository and update it afterwards.

**Comment by sbstn87** [comment]
By the way, trying to add the repository for Debian from here:
https://novelwriter.readthedocs.io/en/latest/int_started.html

prints an error with the GPG key.

**Comment by vkbo** [comment]
The Launchpad solution is already there, and I am very reluctant to add more solutions for the same kind of release. It's already a lot of distribution channels to maintain. AppImage is the alternative solution for Linux besides the Launchpad one. For Windows, I make the installer, and Mac still needs help from someone who could set it up on Homebrew. It is also on PyPi for users who don't mind launching from command line. This works on any OS.

I know there have been activity on getting it on Arch and Free BSD, but I really don't have the capacity to do all of this myself.

**Comment by vkbo** [comment]
> prints an error with the GPG key.

You have to be more specific.

**Comment by sbstn87** [comment]
This is what I get:
gpg: failed to create temporary file '/root/.gnupg/.#lk0x0000557cadc88200.mx.3482': No such file or directory
gpg: connecting dirmngr at '/root/.gnupg/S.dirmngr' failed: No such file or directory
gpg: keyserver receive failed: No dirmngr
deb [signed-by=/usr/share/keyrings/novelwriter-ppa-keyring.gpg] http://ppa.launchpad.net/vkbo/novelwriter/ubuntu focal main

I checked, dirmngr is installed. Perhaps this is issue on my side, but I cannot troubleshoot it.

**Comment by vkbo** [comment]
Yeah, I've seen this before. I can't remember how I solved it. It is a client side issue during the import of the key. The regular "add-apt-repository" approach is deprecated, but it may still work. It gives the sign key too much authority to verify packages though.

**Comment by sbstn87** [comment]
Thanks, so for now I will be using the provided .deb file directly. 

Luckily, my current distro maintainers agreed to add novelWriter to its repository.

Thank you.

**Comment by vkbo** [comment]
It's a bit annoying that Debian doesn't have a Launchpad solution, but I understand the reasoning for it. The current solution is supposed to be the recommended workaround, at least last time I checked. I guess it assumes you have the needed key infrastructure set up already. I'll see if I can resolve it and post the solution when I update the docs.

**Comment by vkbo** [comment]
I'm closing this, since I don't think I will add yet another release channel for Debian distros. I am open to replacing the current one if needed, but not at the moment.

**Comment by vkbo** [comment]
Just ran into the problem again, and the trivial solution is:

```bash
sudo mkdir /root/.gnupg-test && sudo chmod 700 /root/.gnupg
```

It seems the folder is sometimes missing on a fresh install.
