### ISSUE TITLE
Ability to rename a file in the project tree (no dialog box)

### ISSUE THREAD

**Issue by marek-lach** [vkbo/novelWriter#1233]
This is really only a minor thing, for convenience...

While it is already possible to Change label for a Chapter, or a Scene in the Project content pane, would it be possible to also change/rename a label by double clicking on a file name with the left mouse button as well?

Scrivener uses this approach, for example.

But I wish to stress, that this should obviously be of low priority really.

**Comment by vkbo** [comment]
It's been requested a few times, and the main reason why it's not currently possible is deliberate. Both single click, double click and middle click already trigger other actions, and I don't really want to alter that behaviour.

The alternative is to let pressing F2 do it, but if you're a keyboard user, then it is the exact same sequence of keypresses needed to edit a label in the box as it would be directly in the tree. Press F2 > type label > press Enter.

**Comment by vkbo** [comment]
I've re-labelled your issue ticket and will leave it here for later. Maybe it can be solved in a workable way, but I'm gonna leave it in the backlog for now.

I really do suggest using the keyboard shortcut if you have to rename multiple items rapidly. I've deliberately made it so that the old text is highlighted so that you can immediately start typing the new label.

**Comment by marek-lach** [comment]
> I've re-labelled your issue ticket and will leave it here for later. Maybe it can be solved in a workable way, but I'm gonna leave it in the backlog for now.
> 
> I really do suggest using the keyboard shortcut if you have to rename multiple items rapidly. I've deliberately made it so that the old text is highlighted so that you can immediately start typing the new label.

The `F2`shortcut is fine for this, I just had no idea from the documentationv[documentation](https://novelwriter.readthedocs.io/en/stable/usage_shortcuts.html), that renaming is what `F2` does.

**Comment by vkbo** [comment]
The discrepancy is due to the documentation not having been updated yet for 2.0 functionality.
