### ISSUE TITLE
Background color of the editor remains white

### ISSUE THREAD

**Issue by jgauby** [vkbo/novelWriter#1244]
On Debian XFCE (v. 1.6.4), the background color of the editor remains white, whatever the chosen theme.

By the way, to change the background color of the editor, what is the value to modify in the conf file of the theme?

**Comment by vkbo** [comment]
Did you also change the syntax theme, or just the GUI theme?

**Comment by jgauby** [comment]
Only the GUI Theme, there is no mention of "syntax theme" in the GUI :
![Capture d’écran_2022-11-15_19-38-16](https://user-images.githubusercontent.com/381837/201999412-a7d5d683-3b92-4c20-af72-8247f9097015.png)

**Comment by vkbo** [comment]
![image](https://user-images.githubusercontent.com/1619840/202018606-4124f75a-2313-4ecf-a186-2ecab4447ac7.png)

**Comment by jgauby** [comment]
Thank you for your assistance!

**Comment by vkbo** [comment]
No problem :)

In 2.0 the setting is moving to the same place as the main theme setting.
