### ISSUE TITLE
Missing icons: "Could not load icon theme settings" on 2.0

### ISSUE THREAD

**Issue by nyex** [vkbo/novelWriter#1263]
I tried both pip and appimage versions. I'm on Manjaro using bspwm and I use mostly gtk apps, so I admit I don't get along with qt all that well. But it seems I might be missing some icons, since I see the drop-down arrow in the sidebar but not what they are about:

https://imgur.com/wzcavN4

I opened novelwriter from the command line and got this error:

```
ERROR     Could not load icon theme settings from: /home/olivia/.local/lib/python3.10/site-packages/novelwriter/assets/icons/icons.conf
ERROR     FileNotFoundError: [Errno 2] Arquivo ou diretório inexistente: '/home/olivia/.local/lib/python3.10/site-packages/novelwriter/assets/icons/icons.conf'
WARNING   Did not load an icon for 'status_lang'
WARNING   Did not load an icon for 'status_stats'
WARNING   Did not load an icon for 'status_time'
WARNING   Did not load an icon for 'status_idle'
WARNING   Did not load an icon for 'cls_novel'
WARNING   Did not load an icon for 'cls_archive'
WARNING   Did not load an icon for 'cls_plot'
WARNING   Did not load an icon for 'cls_character'
WARNING   Did not load an icon for 'cls_world'
WARNING   Did not load an icon for 'cls_timeline'
WARNING   Did not load an icon for 'cls_object'
WARNING   Did not load an icon for 'cls_entity'
WARNING   Did not load an icon for 'cls_custom'
WARNING   Did not load an icon for 'bookmark'
WARNING   Did not load an icon for 'up'
WARNING   Did not load an icon for 'down'
WARNING   Did not load an icon for 'proj_document'
WARNING   Did not load an icon for 'proj_chapter'
WARNING   Did not load an icon for 'proj_scene'
WARNING   Did not load an icon for 'proj_note'
WARNING   Did not load an icon for 'proj_folder'
WARNING   Did not load an icon for 'add'
WARNING   Did not load an icon for 'menu'
ERROR     Decoration with name 'deco_doc_more' does not exist
WARNING   Did not load an icon for 'refresh'
WARNING   Did not load an icon for 'edit'
WARNING   Did not load an icon for 'search'
WARNING   Did not load an icon for 'maximise'
WARNING   Did not load an icon for 'close'
WARNING   Did not load an icon for 'status_lines'
WARNING   Did not load an icon for 'search_case'
WARNING   Did not load an icon for 'search_word'
WARNING   Did not load an icon for 'search_regex'
WARNING   Did not load an icon for 'search_loop'
WARNING   Did not load an icon for 'search_project'
WARNING   Did not load an icon for 'search_preserve'
WARNING   Did not load an icon for 'search_cancel'
WARNING   Did not load an icon for 'search_replace'
WARNING   Did not load an icon for 'backward'
WARNING   Did not load an icon for 'forward'
WARNING   Did not load an icon for 'sticky-on'
WARNING   Did not load an icon for 'sticky-off'
WARNING   Did not load an icon for 'bullet-on'
WARNING   Did not load an icon for 'bullet-off'
WARNING   Did not load an icon for 'reference'
WARNING   Did not load an icon for 'proj_title'
WARNING   Did not load an icon for 'proj_section'
WARNING   Did not load an icon for 'view_editor'
WARNING   Did not load an icon for 'view_novel'
WARNING   Did not load an icon for 'view_outline'
WARNING   Did not load an icon for 'view_build'
WARNING   Did not load an icon for 'proj_details'
WARNING   Did not load an icon for 'proj_stats'
WARNING   Did not load an icon for 'settings'
WARNING   Did not load an icon for 'noncheckable'
WARNING   Did not load an icon for 'unchecked'
WARNING   Did not load an icon for 'checked'
WARNING   Did not load an icon for 'cls_trash'
ERROR     Decoration with name 'deco_doc_h0' does not exist
ERROR     Decoration with name 'deco_doc_h1' does not exist
ERROR     Decoration with name 'deco_doc_h2' does not exist
ERROR     Decoration with name 'deco_doc_h3' does not exist
ERROR     Decoration with name 'deco_doc_h4' does not exist
```

Similar error when opening the appimage version, only location was different.

Is it something on my side or something missing in the package?

**Comment by nyex** [comment]
I do, but I did try loading it with the default theme and got the same error.

**Comment by vkbo** [comment]
I changed the theme system so that the theme itself decides which icon set to load. It is clear from the output there that the value is blank, therefore it cannot load the theme.

It should work if you change to one of the built in themes and restart the app.

**Comment by vkbo** [comment]
That's strange, because the built-in themes all have that setting. Are you sure the themes are loaded from the actual package and not from your custom themes folder?

**Comment by nyex** [comment]
Aha, that might be it. For some reason I had a copy of all themes in my custom themes folder! Thanks :) Will add that line to my custom theme as well!

**Comment by vkbo** [comment]
Yeah, that's the reason. Then it doesn't matter which package version you run from, since these are all loaded from your user profile.

That said, the app should be able to handle these cases, so I'll add a check that pops up a notification.

**Comment by vkbo** [comment]
ToDo: Add a check that an icon theme is actually set by the GUI theme, and if not, pop up a message alerting the user.

**Comment by marek-lach** [comment]
Just noticed that the icons here a completely missing:

![Screenshot from 2023-01-18 17-42-09](https://user-images.githubusercontent.com/45913977/213247018-4e811ba5-4cd5-498d-8510-e47770f14df9.png)

A mouse hover does reveal the appropriate functionality, but the icons are simply blank. This might be related to the removal of custom icon themes, but unfortunately running the console does not reveal anything relevant this time.

I tried changing my icon theme, but this only changes the icons in the dialog boxes,like here:

![Screenshot from 2023-01-18 18-12-08](https://user-images.githubusercontent.com/45913977/213248850-33a2e323-54d9-41bf-9b30-8c4b77d32193.png)

These window icons however, always do show up fine.

**Comment by vkbo** [comment]
Which version are you running?

The dialog box icons are loaded by Qt, not by the custom theme, so they will always work.
