### ISSUE TITLE
no module named novelwriter.gui?

### ISSUE THREAD

**Issue by mbadros** [vkbo/novelWriter#1273]
I got the following error in a fresh (re-)installation of novelwriter 2.0.1 -- 

> Traceback (most recent call last):
>   File "/usr/bin/novelwriter", line 33, in <module>
>     sys.exit(load_entry_point('novelWriter==2.0.1', 'gui_scripts', 'novelwriter')())
>   File "/usr/lib/python3/dist-packages/novelwriter/__init__.py", line 239, in main
>     from novelwriter.guimain import GuiMain
>   File "/usr/lib/python3/dist-packages/novelwriter/guimain.py", line 41, in <module>
>     from novelwriter.gui.theme import GuiTheme
> ModuleNotFoundError: No module named 'novelwriter.gui'
> Error in sys.excepthook:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
>     with os.fdopen(os.open(pr_filename,
> FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_novelwriter.1000.crash'
> 
> Original exception was:
> Traceback (most recent call last):
>   File "/usr/bin/novelwriter", line 33, in <module>
>     sys.exit(load_entry_point('novelWriter==2.0.1', 'gui_scripts', 'novelwriter')())
>   File "/usr/lib/python3/dist-packages/novelwriter/__init__.py", line 239, in main
>     from novelwriter.guimain import GuiMain
>   File "/usr/lib/python3/dist-packages/novelwriter/guimain.py", line 41, in <module>
>     from novelwriter.gui.theme import GuiTheme
> ModuleNotFoundError: No module named 'novelwriter.gui'
> 

I'm on a Linux machine 
Linux XXXXXXX-XPS-8700 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

Thanks for looking into this issue!

**Comment by vkbo** [comment]
Yes, there was a packaging issue on Linux. It's been fixed. I've uploaded new .deb package and .AppImage, and pushed a post release to PyPi. The Launchpad packages were also pushed a while ago, but they take longer to get through. It seems they were released 5 minutes ago.

Just do an update, and you should be good to go.

**Comment by vkbo** [comment]
Some of you are really fast to update though. The broken package was up for just 55 minutes!

Just close this issue when you've updated and confirmed it works. I did on my own computer, so it should be ok.

**Comment by mbadros** [comment]
Thanks so much!  Appears to be working -- I don't always upgrade so quickly, but I was curious to upgrade from the v1.7 to see what v2.0 was like! Great work!
