### ISSUE TITLE
HowTo: Converting from yWriter to novelWriter

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1289]
Add a HowTo section reference to the https://github.com/peter88213/yw2nw tool by @peter88213 for converting yWriter projects to novelWriter, and vice versa.

**Comment by peter88213** [comment]
I have released version 0.9, which converts the test data without errors. I'll leave it at that for now. 

This is the page that could be linked: 
https://peter88213.github.io/yw2nw/

Some points: 
- When converting the test data from file format version 1.3 with novelWriter 2.0.2, one of the original two author entries was deleted in each case. 
- I assume that in version 1.5 the "active" attribute has the meaning of the "exported" tag in version 1.3. It is not clear from the file format specification, but in the result it seems to fit.
