### ISSUE TITLE
Entering label for status/importance color lists locked after save

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1290]
After saving a combination of color and text, it is not possible to change the label. This goes for both status and importance dialogs.

Reproduction steps (same for status and importance dialogs):
1. Open dialog (either status or importance)
2. Click the item in the list you want to change (for example "new")
3. Click save
4. Try to change the text.

result: you cannot change the text in the text edit anymore.
expected result: I am still able to change the text after I save.

Workaround:
1. Click on one of the other listed items
2. Click on the item you wanted to change initially.
3. You can change the text again.

Version information:
Novelwriter 2.0.2
qt 5.15.7
python3-pyqt 5.15
python3-lxml 4.8.0
python3-enchant 3.2.0

distribution: kde neon (user edition)

**Comment by vkbo** [comment]
It's not a bug. It's supposed to lock the item once your changes are saved. But I agree that if you want to change it again, it's not intuitive that you have to deselect and reselect the same item. The edit box is locked in any other case than immediately after a selection event to prevent you from typing text when you shouldn't.

I'll see if I can implement a more intuitive solution.
