### ISSUE TITLE
Opening a deleted project from the recent list re-creates the project folders

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1300]
Opening a deleted project from the list of "Recently Opened Projects" re-creates the deleted project folder and sub-folders, all empty.

Steps to reproduce:

1. Create a new project.
2. Close the project and/or novelWriter.
3. Delete the project files from your computer (or move or rename the project folder).
5. Open novelWriter.
6. Try to open the deleted project from the list of recently opened projects.
7. Error message appears: "Failed to parse project xml."

Unexpected behavior:

- The project folder and sub-folders are re-created on your computer, all empty.

Should probably be:

- Only the error message.
- The current error message also indicates that it's trying to parse the xml file? But the file is not even there, so it should maybe say something like "Project folder or project xml not found", depending on what is true.

**Comment by vkbo** [comment]
This is part of the code I rewrote for 2.0. It probably treats the non-existent folder partially as a new project.

**Comment by vkbo** [comment]
Fixed in the patch branch. Will release soon.
