### ISSUE TITLE
Running novelWriter on the Pinebook64

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#131]
The good news is that novelWriter runs nicely on the Pinebook64, a 64-bit ARM-based laptop running a 64-bit ARM version of Ubuntu 16.04.6 LTS.

But its Python3 environment isn't the same as other Linux distros. The following steps install the necessary dependencies. Some required us to use `apt install` while others installed fine using `python3 -m pip`. Follows are the details. Consider incorporating some of this information in the novelWriter installation instructions.

```
sudo apt install python3-pip
sudo apt install pandoc
python3 -m pip install setuptools --user
python3 -m pip install pypandoc --user
python3 -m pip install latexcodec --user
sudo apt install python3-pyqt5 python3-pyqt5-qtsvg python3-appdirs \
                 python3-lxml python3-enchant
```

With the dependencies in place it's a simple matter to download and unzip the novelWriter ZIP file from its repository and run it out of the resulting directory.

**Comment by vkbo** [comment]
Thanks for testing it. Will add it to the readthedocs documentation. I'll probably shorten the one in the README too so I don't have to maintain two versions of the same info.

**Comment by johnblommers** [comment]
novelWriter also works under the 32-bit Raspbian operating system on the Raspberry Pi 4.

**Comment by vkbo** [comment]
Cool!

As long as the platform has Python 3.6 or above, and is supported by Qt5, it should work anywhere. The only required non-standard dependency now is the lxml package.

**Comment by johnblommers** [comment]
I've revisited my Raspberry Pi 4 B and can confirm that novelWriter runs perfectly well under the 64-bit Kali Linux operating system on the Raspberry Pi 4. I know it's expected given the open cross-platform nature of Python. Still "trust but verify" is good policy :smile_cat:

**Comment by johnblommers** [comment]
**Update** 

novelWriter 0.7.1 install and runs just fine on the new 8 GB Raspberry Pi 4B running the Raspberry PI  64-bit OS.

It also continues to run fine on macOS Catalina and Ubuntu 16.04 as well as Ubuntu 19.10.

I have to add  that it's nice that the dependency on Pandoc and LaTeX are no linger requirements. Producing PDF, HTML and ODF files is enough for most writers, I would think.

**Comment by vkbo** [comment]
Thanks for the update!

I regularly test on Debian 10/11, Ubuntu 16/18/20.04 and Windows 10. I try to keep it running on all these.

I think dropping the dependencies was worth it. I've looked into dropping lxml too, in favour of the standard Python XML library. The only thing I actually use from lxml is the pretty print feature. It indents the XML. The standard library adds no line breaks and indents at all. It is completely unreadable, removing one of the benefits of using XML.

**Comment by johnblommers** [comment]
Today I had the chance to try out [Salient OS XFCE](https://salientos.github.io/), a distro based on Arch Linux. I was delighted to discover that novelWriter worked out of the box. All of the dependencies were already installed by default.

**Comment by vkbo** [comment]
As for the original point in this issue, I will soon start working on a website for novelWriter. I will transfer the documentation to this site, and use a separate repository where I will use GitHub Pages / Jekyll and Markdown for writing the documentation files. I will look into adding more detailed instructions at that point. I will also take PRs for the documentation section on the website.

**Comment by vkbo** [comment]
After a number of the dependencies have been dropped, I don't see that the install instructions here are any different from the general instructions now in the documentation and on the website. I'm closing this.

Thanks again for testing!
