### ISSUE TITLE
Unhandled error when closing AppImage from terminal

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1318]
I was prompted to put this here.

1. Run the AppImage from terminal
2. Terminate in the terminal with Ctrl+C

I didn't expect anything when I did that, but apparently there is an unhandled error?

```Environment:
novelWriter Version: 2.0.3
Host OS: linux (5.4.0-136-generic)
Python: 3.10.6 (0x30a06f0)
Qt: 5.15.2, PyQt: 5.15.7
lxml: 4.9.2
enchant: 3.2.2

KeyboardInterrupt:


Traceback:
  File "/tmp/.mount_novelWMy7TJ5/opt/python3.10/lib/python3.10/site-packages/novelwriter/guimain.py", line 1541, in _timeTick
    @pyqtSlot()
```

---

Aside, when the "Open Project" window is open, it will visually z-index on top of the aforementioned error message, but the error message is regarded as the "active window" with priority. So to speak.

---

~~Aside aside, when running the AppImage from the terminal, there seems to be a slight delay before novelWriter opens, with this information in the terminal. What would that mean?~~

> ~~(python3.10:30312): dbind-WARNING **: 02:35:06.054: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.~~

Edit: Found it's unrelated to novelWriter.

**Comment by vkbo** [comment]
A keyboard interrupt is treated as an exception in Python. All exceptions that are not explicitly handled in-place are captured at the entry point where novelWriter's Qt process is started. The handler is the error dialog that you saw pop up. This is not a bug, it is the point where the interrupt is caught.

novelWriter will try to do a proper and controlled shutdown when an exception is caught, but it runs on a C++ Qt library, which has it's own event loop, threads, and garbage collector that are separate from Python's. This may cause issues when there is a crash or interrupt, depending on where it happens to occur.

You should not close novelWriter with a keyboard interrupt. I could add a handler for it, but there wouldn't be much point as the current error handler does exactly the same thing: attempts a controlled shutdown.
