### ISSUE TITLE
Implement Find and Replace for all matching strings

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1328]
String replacement _for all found matches_ is currently missing. The user has to click through every single match found in the document/project. Some search results can be in the hundreds... That's too much clicking.

Text editors usually allow the user to click a separate "Replace All" button, which is along the lines of what I'm requesting here.

**Comment by vkbo** [comment]
This is a duplicate of #545. The feature is coming 😄

**Comment by tmarplatt** [comment]
Weird, I did search before submitting. 😐

**Comment by vkbo** [comment]
Yeah, the search here isn't always great. I knew there was a request for it, so I just looked through the pages.
