### ISSUE TITLE
Embed markup gracefully when formatting a single auto-selected word

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1333]
**The problem**

In the editor, a writer should expect that the text cursor stays outside any applied markup when they require the current word to be formatted, provided word auto-selection is enabled.

But as it stands, novelWriter leaves the cursor inside the newly embedded markup, even when it is placed at a word boundary. The user is forced to move the cursor before resuming, interrupting their writing flow.

This is but one small _paper cut_-like issue, which I have explained [in a discussion thread](https://github.com/vkbo/novelWriter/discussions/1323). Not critical but also great if it's taken care of.

**The request**

When all of these are true:

* Automation option "Auto-select word under cursor" is enabled, and
* the user commands novelWriter to apply formatting, and
* no text is selected, and 
* the cursor is at a word boundary;

then novelWriter should embed the required markup but move the cursor to the outside, so that the user may keep typing whatever comes next.

**Comment by vkbo** [comment]
Excellent write-up of the discussion. I'll queue it up for the 2.2 release that will focus on editor features.

**Comment by vkbo** [comment]
Implemented in #1600, but only when the cursor is at the end of the word. See the PR for implementation details.
