### ISSUE TITLE
Project Details: Editing Time is ambiguous

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1335]
In the "Project Details" window, my editing time is stated as `887:49`. I'm guessing from context this means 887 minutes. It might mean hours, because I idled *a lot*. I'm none the wiser. It would be more readable to, as soon as the editing time exceeds 60 minutes, format this number with hours. As soon as it exceeds 24 hours, we could add days.

That said, apparently it is indeed idle time. Maybe the active time would be a preferable display here.

I guess I'm using novelWriter wrong when I keep it running in the background while I'm doing other stuffs :sweat_smile:

**Comment by vkbo** [comment]
It's hours. It mimics what LibreOffice does:

![image](https://user-images.githubusercontent.com/1619840/216367527-96547cd5-61e6-48fb-8d8b-d91d3246bef0.png)

**Comment by vkbo** [comment]
I could use the formatting function that is used for the clock in the status bar though. It formats in days (optionally), hours, minutes and seconds: `D-HH:MM:SS`

**Comment by vkbo** [comment]
Fixed and scheduled for inclusion in 2.0.5
