### ISSUE TITLE
Project Details always displays info from first opened project

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1336]
Project Details displays `Title`, `Working Title`, and `Author` always as they are in the first project that is opened in that instance of novelWriter. Updating either of these fields in the Project Settings has no effect. Closing the project and opening a different project  in this novelWriter instance still displays the outdated information from the first opened project. This does not affect the stats in this window.

**Comment by vkbo** [comment]
By the way, you're right in #842 that it's is related to that issue in the sense that it is the Qt library caching the values. The novelWriter code is loading it all properly. I just need to extend that fix to also reload these values when the dialog is reopened, overwriting what Qt has cached.

This is probably an issue with Qt and Python running separate garbage collectors, and they are not synced properly. I've tried explicitly destroying the dialog after it's closed, but the Qt library doesn't seem to care 😆

**Comment by vkbo** [comment]
Fixed and scheduled for inclusion in 2.0.5
