### ISSUE TITLE
Focusing issues in the Novel Tree View panel

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1369]
**The problem**

![An Image Is Worth A Thousand Words.](https://user-images.githubusercontent.com/16073344/220193440-bdb1a414-d5ec-4186-9106-41ae7dc24008.gif)

In the **Novel Tree View** panel, when you select a document and hit `Enter`, said panel changes as if it had visually defocused: the document is no longer visually selected as if the user was meant to act upon its controls, instead the selection greys out. But if you press the `Up` and `Down` keys, novelWriter will act as if the panel was still focused, and you can invisibly navigate your way across documents without any visible changes, except you can see the document information subpanel at the bottom changing along to reflect the different document being invisibly selected.

If you click back into the panel, visual focus will be restored.

If you access a document from the **Outline View** panel in the same fashion, it switches to the Novel Tree View triggering the same behaviour described above.

**What I expect**

Some visual indication that the Novel Tree View panel is still focused and actionable, and which document I am currently selecting in the tree.

**Comment by vkbo** [comment]
What you're seeing is that the project tree receives focus by default when a document is opened in this manner. So what you're navigating with the arrow keys are now the project tree entries instead. Since the trees are just stacked on top of each other, they are both actually there and can receive focus.

That is indeed a bug.

**Comment by vkbo** [comment]
I found the issue. The focus switch to the project tree was done by the call to change which item is selected. The decision to switch focus has been delegated to the main GUI a while back, and individual GUI components should not be doing this. Removing this line fixed the issue.

Focus bugs are hard to test for when running automated tests as these are usually run without rendering the GUI, which also means they never receive actual focus.
