### ISSUE TITLE
Add export option to use Novel title instead of Project name as default build filename

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1390]
**The problem**

Currently, novelWriter builds projects and sets a default filename using the project title, which is set in stone at the project creation stage. The novel title though, that one's more than likely to change during the author's journey towards ending their work.

It's more likely the user wants a default filename which reflects the current novel title choice than the first one-time project title. If they build often, they will have to manually change the title every single time, without a choice.

**The solution**

To add a new option in the project build modal under _Export Options_, checked by default, to use the _Novel title_ (as configured under the _Project settings_, assuming it's not left blank or made of illegal filename characters) as a default build filename.

Alternatively, perhaps this whole thing should be the only behaviour when building the project.

**Comment by vkbo** [comment]
The whole build tool is in the process of being replaced (see #1269). The new tool will be able to write documents in a bunch of different ways, so the file name will need to be generated based on multiple parameters.

Until then, I won't be making any changes to the current tool as it will be deleted.

**Comment by vkbo** [comment]
I can elaborate a little perhaps. The project structure changes in 2.0 makes it necessary to be able to build subsections of the project in different ways. In part because the project can have multiple novel root folders. The suggested file name will have the option to pull labels from the project structure as well as the project meta data.
