### ISSUE TITLE
AppImage 2.0.6: GLIBC_2.28 missing

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1391]
`novelWriter-2.0.6-py3.10-manylinux_2_28_x86_64.AppImage` fails to start in Lubuntu 18.04 with the following error message in the terminal:

> /tmp/.mount_novelWr0AdAK/opt/python3.10/bin/python3.10: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_novelWr0AdAK/opt/python3.10/bin/python3.10)

Version 2.0.4 worked fine. Is this a problem with the AppImage, or is it finally finito with my distro version?

**Comment by vkbo** [comment]
I was wondering if that was going to happen at some point. I changed to manylinux_2_28 in 2.0.6 because the older ones have reached end of life. See https://github.com/pypa/manylinux

As a general rule I try not to ship anything that has reached EOL, Glibc 2.28 was released in 2018, and Ubuntu 18.04 comes with 2.27. I did check this, but since novelWriter doesn't support Ubuntu 18.04 any more in general due to Python 3.6, I decided it was fine. Especially since 18.04 reaches end of life as well next month.

You can build your own AppImage from the source with:

```bash
setup.py build-appimage --linux-tag manylinux_2_24_x86_64 --python-version 3.10
```
This should run on your system.

**Comment by vkbo** [comment]
I could consider switching to 2.24 until the end of April, to support the remaining Ubuntu 18.04 users, but then I would definitely switch back to 2.28.

The last version officially supporting Ubuntu 18.04 was release 1.6.6.

**Comment by HeyMyian** [comment]
> As a general rule I try not to ship anything that has reached EOL.

That's absolutely reasonable. Is there a possibility to alert the user of the above error and what's going on with a little more detail? Currently novelWriter 2.0.6 fails silently if not executed from terminal.

**Comment by vkbo** [comment]
I don't think so as rhe execution fails on the AppImage side of things. All I can do is to add a note on the download page. I'm working on a brand new website for novelWriter, so I can make a note there.

The AppImage package setup was implemented by @Ryex, so maybe she can correct me or add to what I said.

**Comment by HeyMyian** [comment]
> Edit: If you're curious, the new site will live here until it's ready smiley https://vkbo.github.io/novelWriter.io/index.html

Oh hey! That looks good.

> ./setup.py build-appimage --linux-tag manylinux_2_24_x86_64 --python-version 3.10

I'm getting the error:
```
ERROR: Package 'python-appimage' is missing on this system.
       Please run 'pip install --user python-appimage' to install it.
```
even though when running the command, python-appimage seems to be installed:
```
Installing collected packages: python-appimage
Successfully installed python-appimage-1.2.5
```
:shrug: Do you have any pointers?

**Comment by vkbo** [comment]
Hmm, strange. The error is printed by this section:

https://github.com/vkbo/novelWriter/blob/9fdfe7616ceac11e3d12a622459adf40eefa067f/setup.py#L945-L952

What happens if you try to import `python-appimage` from a Python console or fro ipython?

**Comment by HeyMyian** [comment]
Python 3.6.9:
```
>>> import python_appimage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'python_appimage'
```

Python 2.7.17: nothing happens:
```
>>> import python_appimage
>>> 
```

**Comment by vkbo** [comment]
That is strange.

Anyway, I still have the virtual machine that I used to build the images with, so I added one with manylinux_2_24 to the releases page: https://github.com/vkbo/novelWriter/releases/tag/v2.0.6

Se if that one will run on your system.

**Comment by HeyMyian** [comment]
Thanks, that one works.

I'll look into building my own AppImage again later, that sounds like a cool and useful thing to be able to do. If all fails, I'll *have* to get familiar with the idea of leaving 18.04 behind for good.

**Comment by vkbo** [comment]
I can probably build both versions for the 2.0.x release cycle.

They are built by a GitHub action, so adding one more is little effort, and all the download links are generated by a script from GitHub API data for the new website, so it's minimal effort to add a section for it there too.

**Comment by Ryex** [comment]
If the appimage is missing a libc there is no way to make it not fail silently. that's just the realities of how app images work. it's the equivalent (or nearly) of missing a vcredist on windows. 
There *might* be something we could do with the entry script to make the error more loud but I'm not sure what.
