### ISSUE TITLE
Invalid

### ISSUE THREAD

**Issue by Ryex** [vkbo/novelWriter#1401]
The Alt+a keybinding to add clients to tabgroups is currently masked by the global keygrabber at lines `959` and `975` in `config/keys/lua`.

pressing Alt+a brings up the layout switcher whcih stays up for as long as you hold a. howerver the keybinding Mod+a is isted as adding client to tab groups in the keybindings listed in the `F1` keybindings page  as the first item in the `client` group.

I've remapped the layout switcher key to x in my own configs for now as it didn't seem to have other mappings.

As an asside I think it would be nice to do a bit of themeing adjustment for the bling Tabbed module to reduce the heige of the tabs.
looking at the setting `theme.tabber_*` setting in theme.lua lead to be setting the font size to 9 and wrapping the height call with `dpi` which worked nicely for me to bring it inline with my setup.

def not a priority though.
This config is really polishing up nicely.

**Comment by vkbo** [comment]
Sorry, what?

**Comment by Ryex** [comment]
. Wait what? How did this get duplicated *here* of all places?

Sorry. This was posted to another repo.

**Comment by vkbo** [comment]
Weird!
