### ISSUE TITLE
Project Tree context menu consitency

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1403]
The "Change Label" entry in the project tree menu should say "Rename" instead to be consistent with the main menu.

**Comment by HeyMyian** [comment]
Thanks, I was irked by that every time I changed "the label".

**Comment by vkbo** [comment]
It's been a while since I used novelWriter for actual writing myself (as opposed to just testing new code) and I immediately noticed it while writing again today as I was intuitively looking for "Rename" 😆 

I updated the German translation based on the one you made for "Rename Item" in the menu. So I think it should be fixed already.
