### ISSUE TITLE
Viewer renders escaped markdown syntax, Builder renders the backslash instead

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1412]
**The problem**

When you escape Markdown syntax using backslash `\`, as you would in other editors, the Viewer does indeed render the document as expected by intuition:

![nwviewer](https://user-images.githubusercontent.com/16073344/230757011-273058cf-9e1f-4e8e-b322-aefa27953368.png)

If you try to render the project, the Builder will both preview it and build it without parsing the escape code, rendering a backslash instead.

![nwbuilder](https://user-images.githubusercontent.com/16073344/230757080-655ec158-9960-4618-890c-bc111ddf918b.png)

**The expectation**

There may not be a bug here but this behaviour _appears_ inconsistent. I'm not sure if escaping is meant to be a novelWriter feature but I hope it is.

In the event of an unfortunate coincidence in text, the author may need to be able to escape Markdown syntax. I actually met this unfortunate coincidence myself with a double asterisk repeating in the same paragraph.

**Comment by vkbo** [comment]
No, that's a bug. The renderer for the build preview and the document viewer is the same one, but the stripping of escaped characters is a separate step that must be called. It should be called on some formats, like HTML and OpenDocument, and not on others like Markdown. There is probably an if-statement either missing or misconfigured somewhere in there.

**Comment by vkbo** [comment]
The issue turned out to be that the stripping of escapes after formatting parsing was done after the generated output was added to the document buffer. The buffer is what is used in the build tool, but the document viewer doesn't use this buffer as it is just a single page, hence it was working in the viewer.

In #1418 I'm just changing where this is dune so that it is handled on the paragraph level.

**Comment by tmarplatt** [comment]
To be thorough:

> I'm not sure if escaping is meant to be a novelWriter feature but I hope it is.

The reason for that uncertainty is because I could not find anywhere on the docs something to clear this up. Is there a thread to discuss the nW manual contents?

**Comment by vkbo** [comment]
Ah, right. I'll add a note about it. You can just open a regular ticket about it if you find anything, but I happen to have a PR in progress with some documentation changes, so I added a Tip to the "Text Emphasis" section of the "Formatting Your Text" page.

![image](https://user-images.githubusercontent.com/1619840/233771298-1aa92d3e-c54c-4b30-8852-a1531b3e1f3e.png)

Not sure when I'll push it out to the live docs, as I want to go through a few things, but it has been added to the source at least.

**Comment by tmarplatt** [comment]
It looks great, thanks!
