### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1422]
In the Czech Republic, at the beginning of the block are used quotation marks in the form 99 and at the end in the form 66.
https://prirucka.ujc.cas.cz/?id=162&dotaz=uvozovky
When I use them in Novelwriter, the text highlighting is incorrect. Also, when writing, Novelwriter does not allow to use this kind of quotation marks. Replacement is laborious. Novelwriter has an excellent feature: Format - Convert Single/Double Quotes. It would be great to be able to replace any other quotes with these Czech 99-66. My next request is related to this. The search and replace feature has a great option to use a regular expression as well. I would be able to replace the quotes with a regular expression, but it would need to allow the use of variables $1 $2 $3 … Is it possible to use variables in the search-replace function? It is also suitable for other additional text editing. Thank you.
`## uvozovky

‘single quotes,’ 

“double quotes,”

‚Czech single quotes,‘

„Czech double quotes,“

in text:
Xxx. „Czech double quotes,“ Uvozovky na začátku bloku ve tvaru 99 a na konci ve tvaru 66. 

Xxx. ‚Czech single quotes,‘ Quisque rutrum. Aenean imperdiet. Etiam ultricies nisi vel augue. „Czech double quotes,“ Curabitur ullamcorper ultricies nisi. Nam eget dui. Etiam rhoncus.

-----
Screenshot from Novelwriter:
Xxx.`
![Výběr_287](https://user-images.githubusercontent.com/61266290/232462480-e688f040-2dbd-43c4-8377-bdf3516fab07.png)

**Comment by snden** [comment]
Thank you for your help. I set the correct quotes in the preferences, then also adjusted the settings in the Highlighting section. Everything is OK now.

**Comment by vkbo** [comment]
Sometimes it helps to check the Preferences 😄 

The feature has been there since version 0.1. My main language doesn't use the English quote style either.

**Comment by snden** [comment]
Yes, it was my fault for not looking into the settings better. Sorry for the unnecessary comment.
As for variables in regular expressions - do they work in Novelwriter? Or would it be possible to add this option?

**Comment by vkbo** [comment]
> Yes, it was my fault for not looking into the settings better. Sorry for the unnecessary comment.

Oh, don't worry about that. It can be tricky to find things in software preferences. I do try to keep the Preferences tool simple, but there are still a bunch of options to look through.

> As for variables in regular expressions - do they work in Novelwriter? Or would it be possible to add this option?

The reg ex feature in novelWriter is built on the [QRegularExpression](https://doc.qt.io/qt-5/qregularexpression.html) class from Qt, so it can handle whatever the class can do. I haven't looked deeply into its abilities.

**Comment by tmarplatt** [comment]
I believe what @snden was asking (and I would ask as well) is if the _replace_ feature supports regular expression capture groups. QRegularExpression does support capture groups, but that's at the _search_ stage. 

In text editors you would normally reference a capture group in the _replace_ field by entering its number prepended by a symbol (sometimes a dollar sign `$`, usually a backslash `\`), for example:

**Original text:** `Test string: A Dog and a Fox.`

**Search input (regex):** `A (Dog) and a (Fox)`

**Replace input:** `The Quick Brown \2 Jumped Over The Lazy \1`

The program substitutes the first reference (`\2`) with the second capture group (`Fox`), then substitutes the second reference (`\1`) with the first capture group (`Dog`).

The substituted string is what the text editor replaces the entirety of the matched string (at the _search_ stage) with:

**Text after replace:**`Test string: The Quick Brown Fox Jumped Over The Lazy Dog.`

As of right now, novelWriter does not seem to parse references to regex capture groups when replacing text.

**Comment by snden** [comment]
@tmarplatt: Yes, exactly, thank you.

Some applications also use the $ character for an expression in parentheses. (_$1_, _$2_, _$3_, ...)

I also miss the change of case of  letter option. To change a letter to uppercase, the expression \U is used in the regex, and to lowercase \L , when using variables. I tried it in Novelwriter search and replace dialog and it does not work.

I would need to replace the space after the letters _a, i, o, u, k, s, v, z_ with a nonbreaking space.
I would use a regexp:
_\b([aiouksvz])_ 
to search
and replaced it with the variable _$1_ followed by a _non-breaking space_.
I don't know how to put nbsp in the replace dialog. I tried \u00A0, I couldn't find anything else on the internet for the nbsp character. This expression does not work.

For global replacement, it would be very helpful if Novelwriter could search the entire document system without having to confirm another item. So that the selected replacement takes place at once in the entire novel with one click (replace all).

**Comment by vkbo** [comment]
> I believe what @snden was asking (and I would ask as well) is if the _replace_ feature supports regular expression capture groups. QRegularExpression does support capture groups, but that's at the _search_ stage.

Ah, no, it doesn't. I just pass on the QRegularExpression object to Qt's own find function, which only highlights a piece of text in response. It does not support groups AFAIK. It is a pure string search function which then uses a plain delete and insert. In other words, only the search bit is regex, not the replace bit.

As for supporting unicode escape sequences, I can look into processing that as I have full control of the replace text here.
