### ISSUE TITLE
Add last edit time to documents

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1423]
It would be useful to record the last edit time for documents. This has been suggested before, but not been added.

The edit button at the top of the document editor is pretty much redundant now as all it does is change the label. The position could instead be used for a button that opens a hover box with details about the document, including when it was last edited. This would also be a new usage of the fuzzy time function that already exists.

**Comment by HeyMyian** [comment]
Will this be the "Date modified" of the file on disk, or the true last modification time of the document within novelWriter? I find that information valuable as well, but unfortunately lost it a couple of times because my files were newly synchronized (from GitHub or otherwise) with the current date. So that would be neat to have as accurate metadata within novelWriter.

**Comment by HeyMyian** [comment]
Do you also consider adding the document creation date?

**Comment by vkbo** [comment]
Yeah, I may as well when I'm adding the update date.

**Comment by marek-lach** [comment]
I would only add that some software doesn’t use a precise date like _Last updated 10/05/2023_, but a more general way, such as: _Last updated today_, _Last updated yesterday_, or _Last updated 2 weeks ago_ for example. It may be prefferable to give the user some choice over how to display such information.

**Comment by vkbo** [comment]
So, PR #1509 updates the document file meta data to the following:

```
%%~name: Making a Scene
%%~path: 6a2d6d5f4f401/636b6aa9b697b
%%~kind: NOVEL/DOCUMENT
%%~hash: 053cc65631403c15ddc112849dc7fcae44eb9d63
%%~date: Unknown/2023-08-25 16:56:11
```

The hash value is the sha1 hash of the text, and is used to check against overwrites of files that have changed outside of novelWriter. The date value consist of creation date before the slash and update date after it. The date is *only* updated if the hash changes, so it's a more accurate change date than the file system date.

Of course, for existing documents, the creation date is unknown. I cannot assess it either based on file system info, because zipping, copying, git, etc can all modify that date. It will only be added to new documents created after this is released,

I'll add a GUI box to display this information as well.

**Comment by HeyMyian** [comment]
Is it possible to open existing nwd files in an external editor and manually edit the dates in?

**Comment by vkbo** [comment]
Sure, you could do that. Just make sure to use the same version of the ISO8601 format. Otherwise it may not display correctly on the GUI.
