### ISSUE TITLE
Include a possibility to have clickable URLs in notes.

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1426]
I need to reference external resources in my notes, and sometimes it's just too much to copy into NovelWriter. A separate note-taking application would just mean another distraction while I'm working on my story. When I'm working on my story I like to have as few as possible applications open, to limit distractions.

I would love to insert an URL in my notes and be able to click them. A solution would, for example, be an expansion on the comment tag, much like the `%synopsis:` tag, for example: `%url:`. The following text would then open the OS' default browser when clicked.

For possible bonus points this url could be included in the outline view and be clickable there too. Another solution for the outline view would be to have a button for each url in the outline view. When the on hover event occurs on such a button, the url could be displayed in a tooltip.

**Comment by vkbo** [comment]
I've added this request to the Editor Shortcodes epic, and it could be implemented as something like:

```
[url=https://github.com]GitHub[/url]
```

**Comment by xahodo** [comment]
How about keeping this consistent with how things are done with, say, synopsis? e.g. `%url: https://some.site/page

**Comment by vkbo** [comment]
Well, clickable links is formatting. However, a solution is to add regex recognition of URLs to the preview, and just make them clickable as-is. I've considered this too. But the shortcode formatting also makes it possible to include well formatted links in the manuscript. Which to be fair makes little sense for fiction writing.

But recognising URLs in-text is certainly easier, and maybe I should limit the scope to do just that.

**Comment by vkbo** [comment]
I've created an implementation that simply recognises URLs in the text as links, as long as they start with http or https. They are highlighted as links, you can follow them from the editor via the right-click meny or by ctrl+clicking them, use regular mouse click in the viewer and manuscript preview, and export them to HTML, ODT, PDF and DocX.
