### ISSUE TITLE
Python importlib fails on Arch Linux (not sure what any of this could mean?)

### ISSUE THREAD

**Issue by marek-lach** [vkbo/novelWriter#1435]
File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/novelwriter", line 33, in <module>
    sys.exit(load_entry_point('novelWriter==2.0.7', 'gui_scripts', 'novelwriter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/novelwriter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for novelWriter

**Comment by vkbo** [comment]
As far as I can tell this is not failing anywhere in novelWriter. It seems to me to be an issue somewhere in the code that setuptools generates to start novelWriter, that is, in `/usr/bin/novelwriter`.

How was novelWriter installed?

**Comment by vkbo** [comment]
I just tested in a virtualenv to install both the pip wheel and directly from setup.oy. Both methods seem to work, although the latter creates an .egg zip file which fails to load the assets. That I will fix, but it doesn't have anything to do with this issue.

**Comment by vkbo** [comment]
Hah, I got the exact same error message as you when I deleted the novelwriter installed folder in my virtualenv. So whatever is causing this, you have a launcher script that is trying to start novelwriter from a location where it no longer exists.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vkbo/Envs/NWTest2/bin/novelwriter", line 33, in <module>
    sys.exit(load_entry_point('novelWriter==2.0.7', 'gui_scripts', 'novelwriter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vkbo/Envs/NWTest2/bin/novelwriter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for novelWriter
```

In the mean time, I'm fixing a couple of issues with the setup.cfg file.

**Comment by vkbo** [comment]
Hah, I got the exact same error message as you when I deleted the novelwriter installed folder in my virtualenv. So whatever is causing this, you have a launcher script that is trying to start novelwriter from a location where it no longer exists.

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user123/Envs/NWTest2/bin/novelwriter", line 33, in <module>
    sys.exit(load_entry_point('novelWriter==2.0.7', 'gui_scripts', 'novelwriter')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user123/Envs/NWTest2/bin/novelwriter", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for novelWriter
```

In the mean time, I'm fixing a couple of issues with the setup.cfg file.

**Comment by marek-lach** [comment]
@vkbo So I uninstalled and reinstalled the whole program from scratch, instead of just updating it over old files, and everything seems to work fine now. Must have been some change in path from the previous version as you pointed out.

Closing this now.

**Comment by vkbo** [comment]
Just out of curiosity, how do you install novelWriter?

**Comment by marek-lach** [comment]
> Just out of curiosity, how do you install novelWriter?

Not through PyPi.

This has been an issue on my side, as some Python packages like libfprint and pyenchant for example have been rebuilt against version 3.1.1 system-wide and any package dependant thus also had to be rebuilt from source, not to point to an older, unavailable Python version. So in fact not really anything to do with this project as such, essentially.
