### ISSUE TITLE
Automatic capitalization of the first letter in new sentence and daily word target

### ISSUE THREAD

**Issue by laryngologrodzicom** [vkbo/novelWriter#1441]
Dear novelWriter developers,

Thank you so much for the great software.
I would be very thankful for autocorrection feature in novelWriter, including automatic capitalization of the first letter in new sentence.
It would really improve typing.

The second feature request is daily and weekly/monthly word target counter in the editor.
It would affect acquiring the word target.

I would be very very thankful for these features. Once again thank you for the great software.

Sincerely,
Laryngolog

**Comment by vkbo** [comment]
Thanks!

First of all, please don't combine unrelated feature requests in the same issue ticket. It makes it impossible to track them through implementation. It is not a problem to make two!

**Automatic Capitalisation**

This has already been request in #1358, and it will be implemented. So this is a duplicate feature request.

**Daily Word Target**

This has been requested before. The word count progress for the current writing session is also shown in the status bar at the bottom. Everything related to daily word count statistics is also available in the Writing Statistics tool where you can select and filter the stats in multiple ways, including showing daily aggregated numbers, and even export them to a spread sheet and process them further. If you want to track your daily progress, everything you need should be there already.

**Comment by vkbo** [comment]
Since the first issue is already covered, and the stats for tracking daily progress is already there, I will close this issue. Let me know if I have misunderstood the requests. I can always open the ticket again.

I do not plan to add any visual progress bar for word counts to the main window, which has been requested before.
