### ISSUE TITLE
"Toggle active all" for all documents in a folder

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1448]
This is a suggestion for the context menu on a document or folder in the project tree. I'd find it useful to be able to toggle the active status for all documents inside a folder or inside another document at once.

**Comment by vkbo** [comment]
What's the use case here? Taking out an entire chapter for instance?

Would it be recursive? I generally avoid destructive recursive features. Here, "destructive" is merely on the active setting, so it's not a big deal, but ...

**Comment by vkbo** [comment]
Yeah, that's what I expected. After the next release, the need to toggle the active/inactive state will be significantly reduced.

Here's an example of the selection feature of the new tool. It will look slightly different, but this is what it will do.

https://github.com/vkbo/novelWriter/assets/1619840/da7cee72-3758-493a-8dcc-7b1a151c8576

**Comment by vkbo** [comment]
You will probably also find this feature useful when it is added: #1001

**Comment by HeyMyian** [comment]
I'm looking forward to it ☺️ I'm going to export ALL THE THINGS

**Comment by vkbo** [comment]
I'm scheduling this request to be closed when the new build tool is merged. It will solve the underlying issue as I understand it.

**Comment by vkbo** [comment]
I think the new build tool should solve your issue. I posted a video in #971 if you want to have a look 😄
