### ISSUE TITLE
Cannot install under Windows 11

### ISSUE THREAD

**Issue by perekoo** [vkbo/novelWriter#1449]
When trying to install novelwriter-2.0.7-py3.10.11-win10-amd64-setup.exe, Windows Defender refuses to install, citing an unknown publisher. I have tried the appropriate file both from the website and from the repository. I am using a current Win 11 without additional antivirus programs.

**Comment by johnblommers** [comment]
IIRC the usual fix is to:

1. Right click  on the novelWriter installer
2. Choose Properties
3. Select the General Tab
4. Loot at the bottom pane labeled Security
5. "This file came from another computer blah blah"
6. Check the Unblock box
7. Try installing again

**Comment by perekoo** [comment]
Yes, this workaround works. However, not everyone will want to install a program from an "unknown" source. So hopefully it is not the final solution.

**Comment by johnblommers** [comment]
You did not download the novelWriter installer from an unknown source. You downloaded it from a trusted source, from GitHub, a Microsoft property. 

novelWriter is developed by  Veronica Berglyd Olsen, a trusted, reputable, long-time open source contributor on the GitHub platform.

The Windows 11 message is clearly missing the mark here.

**Comment by perekoo** [comment]
Sorry if my post was misleading. I installed the program because I was aware of the trustworthiness of the source. My comment referred to an inexperienced user reading Microsoft's warning and therefore canceling the installation. That would be a pity.

**Comment by vkbo** [comment]
Microsoft unfortunately makes it very expensive to be considered a "trusted developer" as far as they're concerned. Which is why I haven't done anything about this yet. I plan to eventually sign the releases also on Windows, but currently I only do so for Debian packages on Launchpad.

If anyone know of an affordable way to sign packages for Windows, I'm happy to do so. The ones I've found so far all have a yearly cost far exceeding the donations to this project.

**Comment by perekoo** [comment]
Perhaps a first step could be to add a clear reference to the warning message and a brief explanation of the background on the web page below the installation file?

**Comment by vkbo** [comment]
I don't have access to Windows 11, so I don't know what is actually needed. It's sounds like it's different than on Windows 10. But yes, I agree there should be some instructions. Probably also for Mac, but I will add a signature to Mac releases soon. I just haven't gotten around to dealing with all the AppleID and dev account stuff.

**Comment by vkbo** [comment]
I asked around again, and this time I got some more sensible answers: https://mastodon.online/@veronica/110433799115008142

There is one suggestion that is within budget, if it is usable for my purpose.

**Comment by vkbo** [comment]
The best recommendation from the above mentioned thread is simply to submit it to the Microsoft App Store, which I now have. I had to pay a modest one time fee, which is not a problem. It was a lengthy process to create the listing, but hopefully it's all there and it will pass review. I can post back here when it's available, so you can test it. If everything is OK, I'll add the direct link to the novelWriter website as an option for Windows.

![image](https://github.com/vkbo/novelWriter/assets/1619840/24d8e1a1-040b-4ac4-8115-205bf12ef9b7)

**Comment by vkbo** [comment]
... and that's the end of that:

> Your submission does not have a valid code signing certificate.
>
> On June 16, 2022 we announced an update to Store policy. Win32 apps are required to be digitally signed, with a code signing certificate that chains up to a certificate issued by a Certificate Authority (CA) that is part of the Microsoft Trusted Root Program.
>
> New app submissions will not be allowed without an appropriate signature after May 1, 2023. Existing apps must be updated to include a digital signature per this policy before January 15, 2024. 
>
> Previously, all Microsoft Store apps (native UWPs for example) were hosted and signed by the Microsoft Store and received a Microsoft signature. With the change to our policy enabling Win32 apps to be listed in the Microsoft Store, and the removal of the waitlist for submitting Win32s, the new policy requires those apps to be digitally signed, and ensures all apps that customers acquire and download from the Microsoft Store have a trusted digital certificate.

**Comment by vkbo** [comment]
If anyone with access to a Windows 11 computer could be so kind and write up a step-by-step list of how to allow novelWriter to be installed, I will add it to the website.

Either add it here, and I'll make the changes, or make a pull request directly against this file in the documentation:
https://github.com/vkbo/novelWriter/blob/main/docs/source/int_started.rst

**Comment by vkbo** [comment]
For now, I've added this page: https://novelwriter.io/download/help_win.html

It's in the Downloads section, but it's linked from the front page as well:
![image](https://github.com/vkbo/novelWriter/assets/1619840/7a41aaaf-281b-40ad-9ad8-8f443cb37eca)

Does this look reasonable?

It's pretty much all I can do right now. I'm not prepared to dish out several hundred US dollars per year for a signing certificate. If the donations pick up, I can do it, but it's nowhere near enough to pay for this right now in addition to other costs.

**Comment by perekoo** [comment]
I think the explanations on the website are very helpful. Thanks for that.
