### ISSUE TITLE
Show file size on a successful backup

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1453]
Currently, when you do a manual backup and it concludes sucessfully, an alert dialog reports the file path of the backup file. The status bar changes to reflect the same report.

A simple but sustantially informative change would be to append the resulting backup file size e.g. ` (640KiB)`, in both messages.

In increasingly large projects, which on a HDD can take a noticeable delay to complete, these filesizes become noteworthy.

**Comment by vkbo** [comment]
Good idea. I'll add this.
