### ISSUE TITLE
Font settings not changing editor

### ISSUE THREAD

**Issue by chasrmartin** [vkbo/novelWriter#1467]
* A clear and concise description of what the bug is.
Just installed novelWriter the first time, set the editor font size to 20, and set the font to Courier New. Yhe editor font is some sans-serif font and the size is tiny. Screen shot attached.

* Steps to reproduce the behaviour

Inital setup
![Screen Shot 2023-06-18 at 5 50 21 PM](https://github.com/vkbo/novelWriter/assets/86798/6c1dd6c1-5b3c-4077-91cf-34c635d0bdc2)

**Comment by vkbo** [comment]
Hi,

There is a separate settings for the font for the document editor and view in the "Documents" tab in "Preferences".

The default size is 12 pt, which I should think was pretty standard. Unless there are accessibility reason to increase it or you have a large screen without GUI scaling enabled. In any case, you can also control the editor/viewer font size from there.

![image](https://github.com/vkbo/novelWriter/assets/1619840/81e9627d-fada-4a97-8e92-786617c09788)

**Comment by vkbo** [comment]
> Yeah, I'm old. 12py is way too small. Thasnks

Oh, sure. My vision isn't great either. I was just wondering if it was a screen scaling issue. The framework novelWriter is built on isn't great with high resolution screens.

In any case, I take it you got the font size issue fixed, so I'm closing this.

**Comment by chasrmartin** [comment]
Yup, I got it. Thanks.
