### ISSUE TITLE
Mouse wheel scrolling in focus mode does not work when hovering outside the editing margins

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1474]
**The problem**

Under _Focus mode_, when attempting to scroll up or down the current document being edited, if the mouse cursor is placed outside the Editor's text margins (e.g. with a maximised program window) the text will not scroll anywhere.

**The expectation**

Mouse wheel scrolling should work regardless of the mouse cursor position, as long as it remains inside novelWriter's Document Editor.

**Comment by tmarplatt** [comment]
Sigh. I suck at searching Github issues.

Very well!

**Comment by vkbo** [comment]
Oh, this one was not at all obvious since it's discussing an apparently different issue with the exact same cause. In any case, it's on my short list of issues to look into.

**Comment by vkbo** [comment]
Found a way to resolve this by using an event filter to catch all mouse scroll events on the editor window and forward them to the central editor text area. It should not only work on the margins now, but also when hovering over the header, footer and even search box when it's open.

Should be included in release 2.1.
