### ISSUE TITLE
Customization of backup file name

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1476]
I'm envisioning a one-line input field in the `Preferences` > `Projects` > `Project Backup` window that will control the file name of the backup zip files. Allowed input would be strings, variables for project name / title / author as set within novelWriter, and time formatting like `Y m d H i` etc.

It could maybe even allow further variables for total word count or other such things people might find valuable in file names. I'm not sure, I'm spitballing.

So, an example input could look like this:

```
backup_{$project_name}_Y-m-d
```

For an output file name:
```
backup_exampleproject_2023-07-19.zip
```

My problem is mainly that the project name is not present in the file name, making it impossible to find out at a glance which project the backup is for if it's unpacked or if it's not inside its parent folder anymore.

Thanks for your consideration :slightly_smiling_face:

**Comment by vkbo** [comment]
I think having the user define the backup file format is a bit overkill. I can add the project name back into the file name though, as I can see the issue with not having it there even if the folder is named after the project.
