### ISSUE TITLE
Losing scroll pos when entering/exiting Focus Mode after having scrolled

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1478]
**The problem**

This one is not so easy to reproduce. Sometimes after switching documents in the Editor, sometimes after scrolling on the same document inside the Editor, when entering Focus Mode the window will be scrolled to a new position, much farther beyond the actual previous scroll, like an exaggeration.

It seems to happen when editing long documents (more paragraphs than fit into a screen height or two, including Focus Mode). It seems to be easier to reproduce using larger font sizes in the editor (novelWriter Settings -> Documents -> Font size).

When no manual scroll has happened, the Editor will keep the scroll height across modes.

**The expectation**

I am not sure what is the best solution, considering Editor width can change dramatically across modes, which affects inner Editor height (and thus scroll height).

The Editor viewport scroll after entering/exiting Focus Mode should remain either at:

- a position respecting vertical height of the cursor as it was before the switch _as long as it is visible_;
- an equivalent vertically centered position across Modes, always;
- at the same scroll height as the topmost visible entire line;
- at the top or bottom of the document if either was fully visible before the switch;
- at exactly the same scroll height as the Editor was _before the previous_ mode switch (as long as there remains text)

The last one being somewhat expected by the user but also problematic when there has been a large edit and things have changed dearly in the text structure.

**Comment by vkbo** [comment]
Related to #1302, and can be implemented to solve both.

**Comment by vkbo** [comment]
In 2.2 I'm switching the editor to use Qt's plain text editor. This is a technical detail, but it means I can take advantage of some of the features in it designed for writing code, like scrolling by whole lines. I'm going to add a check that if the cursor was visible before a size change, it will be visible also after the change too.
