### ISSUE TITLE
Unexpected dialog when canceling a document import

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#148]
In version 0.4.2, when you:

1. Click a document in the tree view, 
2. Do a `Menu - Document - Import from file...` and then 
3. Click `Cancel`, 

an unexpected dialog appears:

> Could not read file. The file cannot be a binary file. [Errno 2] No such file or directory: ''

The dialog is harmless and may be dismissed.

**Comment by vkbo** [comment]
It's probably always been like that as I haven't touched that code since I wrote it.

It was just lacking a check that you didn't select an empty file string, which is what is returned on cancel. Posting a fix now.

**Comment by vkbo** [comment]
Should be ok now.

Need to redo this entire feature at some point, as it isn't a very elegant solution to imports. The better solution really is to copy/paste from another editor/viewer as the QTextDocument class has the necessary features to properly reformat on paste.

**Comment by johnblommers** [comment]
Confirmed. The unexpected dialog has indeed been vanquished.
