### ISSUE TITLE
Closing font dialog closes build tool on Mac

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1494]
On Mac: in the Build Tool, either editing the default My Manuscript build or adding a new build, under Format, Font, selecting a new Font and pressing OK in the font dialog causes the Build window to simply shut down (without saving any of the changes made).

_Originally posted by @novakwh in https://github.com/vkbo/novelWriter/discussions/1491#discussioncomment-6587263_

**Comment by vkbo** [comment]
Actually, @novakwh , the Build window is not shut down, but sent to the background. At least when I tested it. When I moved the main window to the side, the settings window was still there.

Could you check this? This should be easy enough to fix. I've seen this problem before, I just forgot about it.

**Comment by novakwh** [comment]
You're right, it sends the build tool "behind" the main window, but this never occurred to me to check as there's no way to guess that behavior would happen. When you press the build button again, it brings the build tool window back to the front, but not the edit build dialog, which remains open in the background; click to edit the My Manuscript build, and it opens another edit build dialog -- so now there are two of these dialogs open, though there's no way to know this since the first window remains in the background, and basically you could continue this in an infinite loop with edit build dialog windows.

**Comment by vkbo** [comment]
This is a weird quirk with Qt and Mac. Whenever you open a system dialog, any non-modal dialogs get sent to the back when you close the system dialog. It's a little tricky in this case because this also seems to propagate up the chain of parent dialog windows.

Anyway, the reason these dialogs are non-modal is so you can keep them open while working on the others. When making this, I found it very clunky to have to open the Build Settings every time I wanted to test a change, rather than just have it open and click "Apply" and then "Preview" in the Manuscript dialog.

**Comment by HeyMyian** [comment]
> Anyway, the reason these dialogs are non-modal is so you can keep them open while working on the others.

That's a great tip. Is there a way to bring the preview window into the foreground when clicking on it while the "Manuscript Build Settings" are open? It stays in the background.

**Comment by vkbo** [comment]
I've resolved the issue on Mac somewhat, but it works.

My research has revealed that dialogs work a little differently on MacOS in general, apparently? They don't have a parent/child relationship like they do on Windows and Linux, where it wouldn't even be possible to send them to the background like MacOS does. I've converted the non-modal dialogs to what Qt calls a "Tool" window, which on MacOS is called a Panel. It changes the title bar a little, but otherwise they seem to work as intended.

> That's a great tip. Is there a way to bring the preview window into the foreground when clicking on it while the "Manuscript Build Settings" are open? It stays in the background.

The Build Settings window is a child of the Manuscript Tool, so it stays on top. You need a screen big enough to drag them next to each other. I can look into fixing it so the settings don't have to stay on top of the manuscript tool. I'd have to redesign some code that handles them, but I may have to do that anyway.

**Comment by vkbo** [comment]
The fix has been merged. Since there was also an issue with the previous DMG package, due to MacOS not liking semantic versioned pre-releases, I made a new DMG release with this fix also included. I've replaced the previous DMG file on the releases page and website. The new package has been given a post-release number, so it's labelled 2.1b1-post1. This one installed much more smoothly on my MacOS VM with Catalina anyway.

**Comment by novakwh** [comment]
Thank you! The new DMG installed (just one usual security warning this time), and the Build tool seems to work well! One thing: after you complete the build by pressing the "Build" there is no feedback to indicate that it worked (even though it did); the window just stays in the same place (so you can keep clicking the build button if you want) and there's no message to indicate that it completed (at least not until you click build again, and then you get an overwrite message). It was a little confusing.

**Comment by vkbo** [comment]
There should be a progress bar along the horizontal of the dialog that rolls by when the build is running, then it stays for a bit and is automatically reset. It should be coloured blue, so it should be fairly visible. I made it narrow for a sleeker design, but maybe it's not visible enough.

The reason there is no other feedback is that I didn't want to block the user interface with another dialog you have to click away. The same Build dialog will be used for other things as well that I plan to add later, so I tried to minimise the number of clicks needed.

**Comment by novakwh** [comment]
Ah, it flashes up and then disappears so quickly that I didn't even notice it (perhaps because it's the short sample file I am building). 

I ran through all of the other bullets in the usability and features in your original discussion post on the Mac beta and everything seems to work well. (Since I'm a writer and not a coder, I can't speak to all of the other improvements.) Thanks again for this amazing software!

**Comment by vkbo** [comment]
Thanks!

Yeah, for full releases I usually put all the features in the release notes part, and keep the technical notes below. Maybe I should split into a further category with user-relevant changes separate from the technical bits. In the past, this was only published here on GitHub, but since it's imported into the website, I probably should leave out some of it and just link back here.
