### ISSUE TITLE
changing scene title and item name simultaneously

### ISSUE THREAD

**Issue by magicalskye** [vkbo/novelWriter#1503]
Hi, this is a very minor thing but it would be so cool. I am a hopeless pantser so I often create a new scene item with a ??? title and once i know where I’m actually going I have to change it, but then I have to change both the item name and the title so that they are coherent and it’s a little bit annoying because I am also a hopeless squirrelbrain and i _forget_ (or i put a completely different value for both and then i get very, very confused at some later point)

So this would be a really neat thing to have. Maybe a project-global “always keep these 2 the same” checkbox would also solve the problem

Thank you for your time.

**Comment by vkbo** [comment]
Firstly, keeping the document label (in the project tree) different from the first title within the document is deliberate and a feature on its own. Just like a file name of a document can be different than the content. So keeping them in sync is not a feature I'm considering. One of the design principles of novelWriter is that the app itself will never change the content of your text documents when they're not being edited, so changing the label cannot then change the title within the document.

That said, what I can add do is the opposite: add a way to set the document label to be the same as the title from within the document *when* the document is open. I can add an option for that when I work on improving the editor functionality, which I plan for the 2.2 release.

**Comment by magicalskye** [comment]
yes that sounds very reasonable! i would be super happy about this solution as well :) and like i said it’s a very minor low-priority thing, but i figured, minor low priority things are quality of life, especially for a program that i like so much and spend so much time in, so i just thought i’d ask. thank you so, so much for all of it!

**Comment by vkbo** [comment]
Sure. This has been requested before in connection with other things, so it was on my todo list anyway. It's good to have a separate issue for it. It makes it easier to track :)

**Comment by vkbo** [comment]
I've added new feature where you can right-click *any* heading within a document and select "Set as Document Name" from the context menu. This will open the Item Label dialog with the heading text already filled in. All you have to do is click "OK" and the document name is updated.

This will be included in release 2.2.
