### ISSUE TITLE
Export outline as spreadsheet

### ISSUE THREAD

**Issue by novakwh** [vkbo/novelWriter#1507]
Hi, I know that I can use the (current) build tool to essentially export an outline of my scenes to a text document (I turn off body text, include everything else, etc.) -- but is there a way, or have you considered adding a way, to export the outline directly into a spreadsheet format? (I suppose CVS or, preferably for me, ODS). 

I just find it easier to review, manipulate, add and delete scenes in a spreadsheet when I am finished one draft and working on the next. If there is already a way to do this and I've missed it, my apologies!

**Comment by vkbo** [comment]
Hmm, not a bad idea. I guess a general feature to export the project structure without the text, to a data file. In this case it would have to be CSV, because writing Open Document ODS files really is a much bigger feature. I could add it as a part of #1108.

You may also be able to import the ToC.txt file found inside your project folder. It is a fixed width file, which I know LibreOffice can import. For the sample project, it lokes like this:

```

Table of Contents
=================

File Name                  Class      Layout    Document Label
-------------------------------------------------------------------
content/53b69b83cdafc.nwd  NOVEL      DOCUMENT  Title Page
content/974e400180a99.nwd  NOVEL      DOCUMENT  Page
content/edca4be2fcaf8.nwd  NOVEL      DOCUMENT  Part One
content/6a2d6d5f4f401.nwd  NOVEL      DOCUMENT  Chapter One
content/636b6aa9b697b.nwd  NOVEL      DOCUMENT  Making a Scene
content/bc0cbd2a407f3.nwd  NOVEL      DOCUMENT  Another Scene
content/ba8a28a246524.nwd  NOVEL      DOCUMENT  Interlude
content/96b68994dfa3d.nwd  NOVEL      NOTE      A Note on Structure
content/88706ddc78b1b.nwd  NOVEL      DOCUMENT  Chapter Two
content/ae7339df26ded.nwd  NOVEL      DOCUMENT  We Found John!
content/bacb7059e3083.nwd  NOVEL      DOCUMENT  Title Page
content/a520879ca0b45.nwd  NOVEL      DOCUMENT  Chapter One
content/14298de4d9524.nwd  CHARACTER  NOTE      John Smith
content/bb2c23b3c42cc.nwd  CHARACTER  NOTE      Jane Smith
content/b3e74dbc1f584.nwd  WORLD      NOTE      Earth
content/f1471bef9f2ae.nwd  WORLD      NOTE      Space
content/5eaea4e8cdee8.nwd  WORLD      NOTE      Mars
content/8a5deb88c0e97.nwd  ARCHIVE    DOCUMENT  Old File
content/b8136a5a774a0.nwd  TRASH      DOCUMENT  Delete Me!
```

**Comment by novakwh** [comment]
For me, getting all of the other stuff -- synopsis and all of the keywords and their data -- would be pretty important, as opposed to just the ToC. Thanks for considering! And CSV should work fine, I think.

**Comment by vkbo** [comment]
Perhaps an export option for the Outline View is what you're after really?

**Comment by novakwh** [comment]
Yes, I think that's exactly it! I'd like my spreadsheet columns for keywords, synopsis, etc. Even if the export was part of outline view and would just, for example, export the columns you've selected to display. But I'd also accept a complete spreadsheet dump of all columns and data in outline view, whatever works.

**Comment by vkbo** [comment]
I've added an export button to the toolbar in the Outline which will write a CSV file exactly copying the content of the visible outline table. CSV files can be opened by Excel, LibreOffice Calc, and other spreadsheet applications.

**Comment by novakwh** [comment]
Fantastic, thank you so much!

**Comment by vkbo** [comment]
No problem 😃 

It was the last task in my 2.3 Beta task list, so I plan to make the beta release tomorrow if I have the time.
