### ISSUE TITLE
Reordering Compilation Settings

### ISSUE THREAD

**Issue by AlanDunaway** [vkbo/novelWriter#1542]
Would like to suggest adding the ability to reorder compilation settings in the Build menu.
Right now, I have multiple books in a single project, as the project is a compilation of stories per volume.
![image](https://github.com/vkbo/novelWriter/assets/96152972/6882b1c2-32ec-44b1-8c65-92f6b55ef7f6)
I have those three compilation settings, which one is the public, second one is only synopsis and third one is the full book plus all data(characters, locations and such).
I'd like to be able to create the settings and reorder them as needed, to sit like the book order I want. Could be with a simple drag and drop, no complex thing.
I don't really know if it will be feasible to do it right now.

**Comment by vkbo** [comment]
Yeah, that should be fairly easy to do. I'll look into it.

**Comment by AlanDunaway** [comment]
> Yeah, that should be fairly easy to do. I'll look into it.

Oh, that's nice to hear.
