### ISSUE TITLE
compile without pip

### ISSUE THREAD

**Issue by FrostKnight** [vkbo/novelWriter#1543]
I have this pkgbuild I used to use, which I could build from. It was for the 2.0.7 build.
[PKGBUILD.txt](https://github.com/vkbo/novelWriter/files/13059538/PKGBUILD.txt)

I used to be able to build it this way, wondered what code you removed that made this not work.

And if so, if you could restore it.

It stops building with the error setup.py not found. Not sure why.

Operating system is hyperbola btw. If this is unreasonable to you, then my bad...

I merely want a simpler way to compile, without pip preferably.

Something like ./configure, make, make install or the above

I uploaded PKGBUILD with .txt or it wouldn't have been uploadable.

**Comment by marek-lach** [comment]
It seems that the command `python -m build --wheel` is causing some issues also.

**Comment by vkbo** [comment]
`setup.py` is deprecated, and has been for a long time. The instructions in the documentation to use it for builds also caused issue for people, since setuptools are not actively maintaining this approach. This is the very old way to build Python packages, and a remnant from distutils, which has now been completely removed from Python.

For release 2.1, the package build of novelWriter has been brought up to date more or less. I still need to replace the `setup.cfg` file with a complete `pyproject.toml` file, but that's less urgent. The special features for novelWriter in `setup.py` have been moved to `pkgutils.py`. Even keeping the `setup.py` file around was causing issues.

The supported way to build novelWriter now is with `python -m build --wheel`. The [documentaion](https://novelwriter.io/docs/tech_source.html#build-and-install-from-source) has been updated accordingly. Please use the approach detailed there.

I'm not aware of any issues with this approach, @marek-lach. This is how novelWriter's wheel packages are currently being created. Could you provide more details on the issues you're seeong?

**Comment by vkbo** [comment]
> I merely want a simpler way to compile, without pip preferably.

That's not really feasible. `pip` is the official tool, and setuptools will no longer support what they call "frontend" features, that is, command line usage. It's a build backend.

There's a full explanation on this here: [Why you shouldn't invoke setup.py directly](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html), written by one of maintainers of setuptools.

The cleanup of `setup.py` for novelWriter is detailed in #1437 and #1438, and implemented in #1483.

**Comment by FrostKnight** [comment]
@vkbo fair enough, I will try the other method then.

**Comment by vkbo** [comment]
Yeah, sorry for having to make this change, but it is needed due to change by PyPA and setuptools. The old approach is already partially broken, and will only get worse.

I'm glad we're finally moving towards a standardised way of handling packaging with Python, and not just a bunch of competing third party tools.

**Comment by vkbo** [comment]
> edit: yeah,
> 
> python -m build --wheel
> 
> isn't working for some reason...

What's the error?

**Comment by FrostKnight** [comment]
> > edit: yeah,
> > python -m build --wheel
> > isn't working for some reason...
> 
> What's the error?

 python -m build --wheel
/usr/bin/python: No module named build.__main__; 'build' is a package and cannot be directly executed

I have python build too... which makes it strange...

**Comment by vkbo** [comment]
Ah, you may have a folder named `build` in the source. If so, delete it.

**Comment by FrostKnight** [comment]
> Ah, you may have a folder named `build` in the source. If so, delete it.



> Ah, you may have a folder named `build` in the source. If so, delete it.

Don't see a folder named build though that's peculiar.

**Comment by vkbo** [comment]
Hmm, ok. There are a few other suggestions here: https://github.com/pypa/packaging-problems/issues/439

It's a bit unfortunate that they picked a name as generic as `build` for the tool. It causes import conflicts.

**Comment by FrostKnight** [comment]
> Hmm, ok. There are a few other suggestions here: [pypa/packaging-problems#439](https://github.com/pypa/packaging-problems/issues/439)
> 
> It's a bit unfortunate that they picked a name as generic as `build` for the tool. It causes import conflicts.

Hmm... I wonder...

**Comment by vkbo** [comment]
I do not. It's probably an issue with the environment setup. I've seen the issue myself, and I had a `build` folder left by pip or setuptools or something, that I had to delete.

It's likely trying to load something other than the actual build tool. Could you try in a venv?

**Comment by FrostKnight** [comment]
> I do not. It's probably an issue with the environment setup. I've seen the issue myself, and I had a `build` folder left by pip or setuptools or something, that I had to delete.
> 
> It's likely trying to load something other than the actual build tool. Could you try in a venv?

How would I do that, just curious

**Comment by vkbo** [comment]
This should create a Python virtual env in /tmp
```bash
python -m venv /tmp/nw-build
source /tmp/nw-build/bin/activate
```

Then when the env is activated (it should change the terminal prompt) run:
```
pip install build
python -m build --wheel
```

**Comment by vkbo** [comment]
Also, seems `python-build` creates a `build` folder, so it may not be the reason alone. It still runs fine if I run it again.

**Comment by FrostKnight** [comment]
> Also, seems `python-build` creates a `build` folder, so it may not be the reason alone. It still runs fine if I run it again.

looks like it worked. Do you know what I would need to do, to make that pkgbuild work with the new parameters?

**Comment by vkbo** [comment]
Any particular reason why you don't just run `pip install novelwriter` in the first place? Or, you can download the wheel file from either GitHub or the main website (same link).

> looks like it worked. Do you know what I would need to do, to make that pkgbuild work with the new parameters?

You can use the above approach in the script. The `nw-build` env is isolated and can be deleted afterwards.

**Comment by FrostKnight** [comment]
> Any particular reason why you don't just run `pip install novelwriter` in the first place? Or, you can download the wheel file from either GitHub or the main website (they're all the same file).
> 
> > looks like it worked. Do you know what I would need to do, to make that pkgbuild work with the new parameters?
> 
> You can use the above approach in the script. The `nw-build` env is isolated and can be deleted afterwards.

Hmm... I guess I could, I just don't have a huge desire to use pip that's all.

**Comment by vkbo** [comment]
What's the issue with `pip`? It's the official Python tool and under the control of PyPA. This is why other tools like `setuptools` are stopping providing the same features as the official tool.

**Comment by FrostKnight** [comment]
> What's the issue with `pip`? It's the official Python tool and under the control of PyPA. This is why other tools like `setuptools` are stopping providing the same features as the official tool.

Hmm... yeah good point. It was more about is it as safe as having it directly installed, that's all.

**Comment by vkbo** [comment]
Sure, that's a valid point. `pip` can also install from local sources, and doesn't have to pull anything from the public package index. I generally avoid using it myself outside of virtual environments. If you build the wheel file locally with `python-build` from source, and install the local file with `pip install`, then you have the same process as before with `setup.py`.

**Comment by FrostKnight** [comment]
> Sure, that's a valid point. `pip` can also install from local sources, and doesn't have to pull anything from the public package index. I generally avoid using it myself outside of virtual environments. If you build the wheel file locally with `python-build` from source, and install the local file with `pip install`, then you have the same process as before with `setup.py`.

Fair point, I guess close this then. No worries.
