### ISSUE TITLE
Hunspell doesn't properly recognise words with an apostrophe in it

### ISSUE THREAD

**Issue by quasipedia** [vkbo/novelWriter#1544]
# Problem
On my system (_Fedora Linux_ running _novelWriter 2.1_ as an AppImage, the spell-checking functionality being provided by _hunspell_), I can't seem to find a way to type words like `father's` or `doesn't` without the British spell-checker raising an error.

The following is a screenshot of what the problem is:

![image](https://github.com/vkbo/novelWriter/assets/309045/6d2e1dea-aa56-47eb-9d4f-dc93c3065400)

However, if I switch to US English the behaviour is different, with the default typing looking correct.

![image](https://github.com/vkbo/novelWriter/assets/309045/6ea61791-98f0-4d10-a735-cafbe72f37b8)

Ideally, I would like me typing `doesn't` and the spell-checker accepting that formulation, or automatically changing it to the correct typographical symbol suggested by the spell-checker.

This is particularly annoying because for words like `doesn't` I can just type `doesnt` and then accept the suggestion from the spell-checker.  But the trick doesn't work with most words with an `s` after the apostrophe, as - for example - `fathers` is the correct plural of the word and a suggestion for `father's` won't be shown.

**Comment by vkbo** [comment]
Yeah, I've noticed this with hunspell too. I also use UK English, and with the UK English aspell dictionary it looks fine. I think the main issue is how the different dictionaries handle the proper apostrophe symbol as opposed to the straight apostrophe that the keyboard produces.

This isn't really a novelWriter bug, but a shortcoming of the spell checker. I can in principle do a search/replace on the text sent to the spell checker, but having a lot of them tend to slow it down a lot and I already have one to remove underscores.

I'll investigate possible solutions. I'm revamping the spell check feature for the next release, and maybe I can add a feature to set spell check provider affinity. This is a feature of the spell check library in use. I think aspell is favoured already though.

**Comment by vkbo** [comment]
The alternative apostrophe is a special unicode symbol that isn't really recognised by spell checkers. It's only included in novelWriter to help correct for mistakes by the syntax highlighter, which will sometime assume apostrophes at the end of words as the end of a single quoted region of text. There should be no need to use it inside of words.

Like in this example:
![image](https://github.com/vkbo/novelWriter/assets/1619840/d17e4ec3-e661-460e-8c4e-0ada1de52f62)

**Comment by quasipedia** [comment]
Hi @vkbo !  Thank you for the detailed and useful answer.  Given your input I simply fix the issue myself by `sudo dnf install aspell-en`... Works like a charm now, given that novelWriter automatically switched to `aspell` once installed.  Thank you so much for the quick support (and for novelWriter in general, which is pretty cool).

**Comment by vkbo** [comment]
Ok, so I've tested the British English hunspell dictionary, and I can't reproduce the issue now.

![image](https://github.com/vkbo/novelWriter/assets/1619840/73f73d17-0c09-430b-9933-1e4ab8e8c0ad)

Tested on both Debian 12 and Windows 10. I'm not sure what causes it in your particular case. But since there is a solution in installing aspell dictionaries, I don't think I'll pursue this further.
