### ISSUE TITLE
Initial size of Manuscript Build Settings window

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1551]
After the update (both beta and final) the first time the Manuscript Build Settings are opened, it has a funky width that is not wide enough to display any document names. This is easily helped by dragging the middle section wider. But maybe it should have a reasonable initial width.

This is on Windows. I can't remember if the same issue appeared on Linux.

![2023-10-18___01_04_44](https://github.com/vkbo/novelWriter/assets/60368695/513e2e56-9c15-4604-8df9-f0f2f106d579)
(ignore the missing icons)

**Comment by vkbo** [comment]
Hmm, it is set to size to content. I think maybe your issue is actually caused by the missing icons. There is a column of icons that are missing, and it seems to mess with the auto-sizing.

**Comment by HeyMyian** [comment]
I've since fixed the icons (I think?) and the issue persists. It also seems to be per project that I need to resize the middle section.

![2023-10-23___22_34_35](https://github.com/vkbo/novelWriter/assets/60368695/d4b14ce9-d4c5-4083-b23c-4ad35ab6a808)

**Comment by vkbo** [comment]
The second and third column is set far too wide for some reason. It is hard coded to be fixed width plus a small margin, but for some reason they're getting too much space. I'll look into it.

**Comment by vkbo** [comment]
Hmm, I tested on Windows 10, and the columns are wider than they should be, but not as wide as on your PC.

![image](https://github.com/vkbo/novelWriter/assets/1619840/e7bcd02d-ec5c-49fc-89bf-816b868e342c)

Do you by any chance have a high DPI screen?

**Comment by vkbo** [comment]
> It also seems to be per project that I need to resize the middle section.

Yes, these settings are saved in `meta/options.json` in each project.

**Comment by HeyMyian** [comment]
My screen has 109ppi (27″ 2560x1440). Currently there are two of them side by side active.

I just reset my novelWriter folders in Local and Roaming. This screenshot also has 10px UI font size compared to my previous 12px. The middle section is still too narrow and compared to your screenshot, the icon column takes up too much space?

![2023-10-23___23_14_52](https://github.com/vkbo/novelWriter/assets/60368695/ba21546b-632e-4a3a-88cc-da7406f7f7a6)

**Comment by vkbo** [comment]
Are you able to run novelWriter from source? I changed the minimum column width, and it reduced the size of the icon columns on my VM with Windows 10, so I was wondering if you can test it on yours.

**Comment by vkbo** [comment]
Basically, in the file `novelwriter\tools\manussettings.py`, insert the line:

```python
treeHeader.setMinimumSectionSize(iPx + cMg)
```

So that it looks like this:

![image](https://github.com/vkbo/novelWriter/assets/1619840/b1b9567e-5350-47b4-b334-41b0eec2b296)

**Comment by HeyMyian** [comment]
Yes, thank you. With your line added, this is what two new projects look like for my settings (dark) and with default settings (light). I think the right section could be the one who does the shrink in favor of the central section. But it's definitely much better now (if a bit crammed for the "included" icon?).

![2023-10-23___23_39_26](https://github.com/vkbo/novelWriter/assets/60368695/19b89608-2468-45f2-bd24-9d5e1fe96ffa)
![2023-10-23___23_40_22](https://github.com/vkbo/novelWriter/assets/60368695/7370982f-a7f4-4b23-a067-8543d6683173)

**Comment by vkbo** [comment]
Yeah, this is not theme related. I think the default minimum column width is different on each platform in Qt. I remember having to fix this for the project tree too, and I hadn't added that specific line in this dialog. I probably forgot why I added it elsewhere. This problem doesn't show up on my platform (Debian 12 + Gnome), so I never noticed.

There are a few minor issues around, so I'll do a 2.1.1 release very soon.

I'll also try to tune the initial size allocation for the splitter there. It should default to 50/50, but it clearly doesn't.

**Comment by HeyMyian** [comment]
Thanks for taking care of this, and so fast too. It's really a non-issue from my point of view because it's easily fixed by just dragging the section wider once per project, and then it never occurs again. I thought I report it anyway for that certain *software polish*, to leave a better impression for first-time users.

**Comment by vkbo** [comment]
The icon column width is definitely a usability issue, if not exactly a bug. I'm guessing there are some design standards Qt is following or something. But it is a waste of space to have this much margin. I guess the intention is that there should be text next to the icons.

I've fixed it so that when you resize the dialog, the middle section is receiving the additional size too, as it is likely the reason the dialog is resized. The right-most section will rarely need resizing after the initial size is set.
