### ISSUE TITLE
Spell checking not refreshing on word list change

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1559]
In the new version 2.1, spell checking with Project word list does not work properly. All words inserted into the list still remain underlined.
In novelWriter-2.0.7-py3.10-manylinux_2_24_x86_64.AppImage, everything is fine.

**Comment by snden** [comment]
Thanks, F7 helps. In version 2.1, compared to the previous ones, refresh spell checking is therefore required after inserting a word into the Word list.

In previous versions, all I had to do was insert a word and save the list, the word highlighting changed automatically according to the list.

**Comment by vkbo** [comment]
Yeah, there is a bug in the auto-refresh. It's the same issue as #1535. I'm renaming this one to reflect that.
