### ISSUE TITLE
Project word list export import

### ISSUE THREAD

**Issue by snden** [vkbo/novelWriter#1560]
Creating a Project word list sometimes takes a lot of time. An option to export and import the list would be useful.
For now, I'm doing it by copying directly between files, but it's a bit impractical.

**Comment by vkbo** [comment]
Yeah, since it's just a JSON file, it should be fairly easy to do. An import/export feature will also be needed when the single project file format is added, as it will be more tricky to get to the word list file in those cases.

**Comment by snden** [comment]
I also have a question about inserting words. I will start a new topic when needed.
Would it be possible to insert words into the Project word list using the context menu directly in the text? It would speed up the work a lot.

**Comment by vkbo** [comment]
You can already do this when it is underlined.

**Comment by snden** [comment]
Why didn't I notice this?? Oh, how inattentive I am. I'm constantly discovering how much Novelwriter has to offer. Good work. And the great thing is that you are constantly improving something on it. Thanks.

**Comment by vkbo** [comment]
Keep in mind that this function selects the word in a slightly different way than the spell checker, which sometimes means it includes characters it shouldn't, so you may have to occasionally edit them in the word list.

This has been fixed in #1525.

**Comment by vkbo** [comment]
Added import and export buttons for the upcoming 2.3 beta release. Should be available soon.

The import will literally take anything as long as it is a plain text file. I imported Moby Dick, and it added all unique words (with punctuation) in the novel to the word list. Good stress test. The app did freeze up a while churning through it, but it succeeded after a bit! 😃
