### ISSUE TITLE
Most recent translations missing in 2.1

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1563]
Regardless of what language I configure novelWriter's GUI to use, several translations are missing and appear in default English, in the latest release version.

**Steps to reproduce**

0. On a clean system (no novelwriter config directory), either running the AppImage or directly from source:
1. Open the preferences dialog, choose a non default (non English) GUI language, like Spanish ("Español Latinoamericano").
2. Accept and restart novelWriter
3. Start/Open a project, then open the Build Manuscript dialog.
4. Click on "Edit Selected Build"
5. Notice some/all of the left-hand menu strings normally translated.
6. Notice most/all of the right-hand options using untranslated/default strings.

I've not checked other installations methods. I have reproduced this issue with French and Portuguese before opening this ticket.

**Comment by vkbo** [comment]
Confirmed. The translations are there, but since these are constants, not dynamic strings, they need two passes through the translation framework when used on the GUI. It's a simple fix.
