### ISSUE TITLE
AppImage: default GUI language appears as German (Deutsch)

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1564]
Running a clean novelWriter install (no config directory) and using the 2.1 AppImage build, for some reason the selected language when opening the Preferences dialog shows up as "Deutsch", even though the entire GUI is in English.

**Comment by vkbo** [comment]
The config defaults to the locale of your system, but if that isn't available in the list of translations, the dropdown will simply stay on the first on the list, which happens to be Deutch at the moment. It doesn't mean the setting is Deutch.

The Preferences dialog should probably pick "British English" if the language code isn't recognised.

This is not a recent change.
