### ISSUE TITLE
Add a hideable formatting toolbar for shortcodes

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1585]
With a lot of formatting options incoming, it may be time for adding a toolbar to the document editor. I propose that it is vertical along the left edge, and only visible when the user wants it to. So, there needs to be a toggle button for it. The current edit button, which is pretty much redundant now, can be replaced with a show/hide toolbar button.

**Comment by vkbo** [comment]
Implementation in #1584 looks like this now:

![image](https://github.com/vkbo/novelWriter/assets/1619840/76a70eff-1cd0-4d9f-babe-4c89460ee1f9)

**Comment by marek-lach** [comment]
> With a lot of formatting options incoming, it may be time for adding a toolbar to the document editor. I propose that it is vertical along the left edge, and only visible when the user wants it to. So, there needs to be a toggle button for it. The current edit button, which is pretty much redundant now, can be replaced with a show/hide toolbar button.

I only wanted to ask, if it could be adjustable through settings if the formatting toolbar would be on the left (by default), or the right edge...

**Comment by vkbo** [comment]
It appears below the three dots button. Any particular reason to put it on the other side? You wouldn't usually have it open. The only reason I didn't just add it as a dropdown menu, as I originally had intended, is that this is easier to use and access.

**Comment by marek-lach** [comment]
> It appears below the three dots button. Any particular reason to put it on the other side? You wouldn't usually have it open. The only reason I didn't just add it as a dropdown menu, as I originally had intended, is that this is easier to use and access.

It's a nice design. And no big deal to leave it where it is. I was just thinking about left/right handed people...
