### ISSUE TITLE
Multiselect for labeling

### ISSUE THREAD

**Issue by tinkicker** [vkbo/novelWriter#1592]
I have searched using "multi select" and don't see a suggestion quite like what I'm thinking about.

* A clear and concise description of what the problem is.
I began a project with a template with some chapters, scenes, etc. I wanted to begin with every item labeled "First Draft".

* A clear and concise description of what you want to happen.
I selected a chapter and assigned the "First Draft" label. I expected all sub items to be labeled "First Draft" at that point. They were not. I expected to be able to multi select every item I wanted to label "First Draft". I could not. I had to select an item, assign the label, and then select every other item one-by-one. This is very time consuming.

* A clear and concise description of any alternative solutions or features you've considered.
To be able to select all sub-items by selecting the top-level item would be efficient. To be able to CTRL-select multiple items would also be efficient.

Thank you for reading this!

**Comment by vkbo** [comment]
I'm planning to allow for this when I add the multi-select feature in #1549.

That said, it won't propagate settings to sub-items. There are clear cases where you don't want this to happen, so I think this is best achieved with multi-select too.

**Comment by vkbo** [comment]
Feature has been added for the upcoming 2.2 release.
