### ISSUE TITLE
Formatting buttons should always insert formatting symbols

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1598]
Clicking on the formatting buttons in the new toolbar currently does nothing when
1) no word is selected or
2) the cursor is not inside of or at the end of a word.

The expected result however is to insert the formatting symbols with the cursor placed inside them, ready to type.

_Originally posted in https://github.com/vkbo/novelWriter/discussions/1596#discussioncomment-7547018_

**Comment by vkbo** [comment]
Fixed in #1600, along a general improvement of how formatting is applied. Needs testing to see that there are no corner cases it misses.
