### ISSUE TITLE
Remember last preference tab

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1603]
I would find it very useful it the preference window would remember the most recent tab it was on before it was closed, and open on this tab. This is useful for tinkering with settings. I imagine the information could be stored in novelwriter.conf.

**Comment by vkbo** [comment]
I don't think it makes sense to remember tabs. The use case is pretty marginal as the Preferences has settings you very rarely will change. It may be annoying when you're testing certain settings, but that's a rare occurrence. And I don't think it is a desired effect to have some random tab you opened a month ago suddenly be the default when you open Preferences next time. I also don;t think this is a common practice in software. At least I've never noticed it anywhere.
