### ISSUE TITLE
Edit and View buttons in the References widget

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1627]
Version 2.2 RC 1

In the new References widget, there seems to be a misalignment of the "edit" and "view" klickable buttons with their respective icons.

The blue rectangle in this screenshot is the highlighted button when I click it:
![Screenshot_2023-11-27_04-20-31](https://github.com/vkbo/novelWriter/assets/60368695/80c603d5-90a5-49d4-bedd-b3f3f6c31f84)

It seems to be correct in your own screenshot from Crowdin:
![Screenshot_2023-11-27_04-26-46](https://github.com/vkbo/novelWriter/assets/60368695/2b496d70-528c-4874-af13-9dfbd80e416b)

---

Maybe the buttons should also on hover change the cursor to a pointer. This is because the buttons change the editor/document viewer on a single click as opposed to the usual double-click. Not sure how consistent this is with other buttons and clickable things though.

**Comment by vkbo** [comment]
> Maybe the buttons should also on hover change the cursor to a pointer. This is because the buttons change the editor/document viewer on a single click as opposed to the usual double-click. Not sure how consistent this is with other buttons and clickable things though.

It's not really a button, but an icon, like in the Novel Tree View.

**Comment by HeyMyian** [comment]
> Windows again I presume?

AppImage (regular Linux, not old)

**Comment by vkbo** [comment]
> > Windows again I presume?
> 
> AppImage (regular Linux, not old)

Strange. It shouldn't do that on Linux.
