### ISSUE TITLE
Labels should toggle their button

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1628]
Issue title might be misnamed, sorry. I'm specifically talking about the "Comment" and "Synopsis" toggles in the Document Viewer:

![Screenshot_2023-11-27_04-21-24](https://github.com/vkbo/novelWriter/assets/60368695/7c6f15a4-518b-4f81-b6ed-dc5c67131f5f)

They toggle only when clicked on the tiny icon. The label of the toggle could (should?) function as an extension of the icon. See HTML label tag, which this reminds me of: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label

**Comment by vkbo** [comment]
This is a button though, and *not* an icon. The alternative is to make the whole thing a button, or change it to a switch. HTML behaviour is not relevant. On the UI, clicking labels generally don't activate the function.

**Comment by tmarplatt** [comment]
I believe this to be part of a larger UX issue.

I don't know if they scale with system settings, but buttons in novelWriter are small by default and therefore hard to click. The user wants the GUI to be as navigable as possible, else their creative focus gets interrupted. Clickable labels are one step towards that, even if the user has no accessibility requirements/configuration set.
