### ISSUE TITLE
novelWritter 2.1.1 doesn't work on a MacBook Pro with 10.6.8

### ISSUE THREAD

**Issue by TheVentrux** [vkbo/novelWriter#1644]
I downloaded 2.1.1 version, dmg opens fine, When I double-click on the icon, nothing happens. I found the app opens and closes inmediatly. 

What can I do? What do I miss?

**Comment by vkbo** [comment]
Could you try with the 2.2 version released yesterday?

Unfortunately, I have no access to a Mac, so I cannot debug this. Maybe @Ryex is able to look into it?

**Comment by vkbo** [comment]
Wait, just did a quick search. MacOS 10.6.8 is from 2011? That may be the reason. I have no idea what the cutoff is for the MacOS release, but novelWriter DMGs are built on MacOS 12.

**Comment by johnblommers** [comment]
You have to drag the novelWriter.app program into /applications. Run it from there.

You cannot run novelWriter out of its DMG disk image.

**Comment by TheVentrux** [comment]
It doesn't work from Applications folder either.

I'm thinking in pull the app from PIP but all the chain is - giving me troubles (not a complain, is entertaining) I need to install Xcode -> Homebrew -> PIP -> novelWritter

Any other plan?

**Comment by vkbo** [comment]
I think perhaps your Mac is just too old for the DMG. But as I said, I don't have access to a Mac, and my Mac VM no longer works, so there isn't much I can do.

Installing from pip is certainly always an option. Once it's set up, it should also be easy to update.

**Comment by TheVentrux** [comment]
novelWriter 2.2 from Applications folder nope. 

I tried direct from the terminal and I got an output, hope it give us a clue, it says:

LSOpenURLsWithRole() failed for the application/Applications/novelWriter.app with error -10810

**Comment by vkbo** [comment]
I have no idea what it means, but maybe this helps: https://superuser.com/questions/1564451/macos-catalina-fails-to-open-certain-apps-with-lsopenurlswithrole-failed-with

**Comment by vkbo** [comment]
Since there has been no update on this from you, and this is a really old MacOS version, I'm closing this. As a rule, novelWriter does not support platforms that are no longer maintained, so aside from giving some support, it is not likely that any changes will be made to novelWriter here.

**Comment by TheVentrux** [comment]
I work around installing Homebrew, then Pip. And in some point I realize is something in the build of the app. I work in this on weekends, sorry.

It´s a shame that novelWritter doesn't support old hardware because I was looking for a way to recycle old hardware for novel writers in a free distraction environment. This leave us with Word, Pages and maybe Scrivener which I believe is novelWritter competence and I believe novelWritter it has the potential to be far superior.  :(

**Comment by vkbo** [comment]
Old Hardware is not a problem. However, supporting old operating systems is a major blocker for developing the application. It also requires a lot of resources to test against old operating systems. It is not manageable for a small open source project like this. I don't have a Mac to test against at all either, so it's already really hard for me to fix things that break on MacOS.

If you really want to run on old hardware, the best option is to install Linux on it. Linux is very good at supporting old hardware even on newer Linux distros. The very opposite of Windows and its new Windows 11 hardware requirements nonsense.
