### ISSUE TITLE
Block comments

### ISSUE THREAD

**Issue by novakwh** [vkbo/novelWriter#1687]
I searched and don't think I found this anywhere, if I overlooked it, my apologies.

Is there a way to comment out multiple paragraphs at once without needing to put a single % symbol at the beginning of each paragraph? In Obsidian, for example, I can turn multiple paragraphs into a comment block by putting %% at the beginning and then again at the end; or you can do the same with HTML comments, of course, and those would also work in standard Markdown (although I actually prefer the simplicity of %%).  In novelWriter, it seems I can only comment out one paragraph at a time (and the "toggle comment" command, if used with multiple paragraphs selected, will only comment out the first paragraph.)

The reason I ask is that sometimes I write quite a bit of copy in a scene that I may or may not want to use, but I want to keep it there inside the scene, where it was natural for me to write it and where it would likely go if I decided later to use it. The easiest way to do this, that I can think of, would be to comment out the block, but not if I have to add (and then later remove) a % sign at the beginning of each commented paragraph.

For one example, I might write an exchange between two people and decide to slip a bit of description or memory of backstory in the middle, where it makes sense for me to write it, but I am not sure if I want to actually include it or not. The only other alternative that I can find would be to copy everything to a different note, but I'd rather not have to do this if possible. 

Thanks for your time and consideration!

**Comment by vkbo** [comment]
Yes, there is already this request: #1042, which would cover what you're asking for.

You can comment/uncomment a paragraph with `Ctrl + /` on Linux and Windows, and whatever is the equivalent on Mac. You don't have to type the `%`, or remove it, manually.

**Comment by vkbo** [comment]
The feature in #1042 is scheduled for the next release by the way, and I think I will be able to include it.

**Comment by novakwh** [comment]
Yes, the Ctrl / "toggle comment" command is easier than typing and removing %, but you still have to do it one paragraph at a time, which is what I hope to be able to avoid if you add block commenting in the future. Thanks very much! I really do love this software.

**Comment by vkbo** [comment]
There will not be block commenting, like you describe it, any time soon. The format parser in novelWriter treats the text one line at a time. However, being able to toggle comment mode on all selected text, including multiple paragraphs, should make this much simpler.

**Comment by vkbo** [comment]
PR #1690 adds a new "ignored text format" which is just a `%~` instead of `%` in front of the paragraph. This modified version will always exclude the text from manuscript builds even if you include comments. It's just an optional feature, and something I want for my own writing.

In any case, in the context of adding that, I made the comment, ignore text, and reset format commands apply to multiple paragraphs, Since the first two are toggle commands, they will make the decision based on the first of the selected paragraphs, and apply it to the remaining in the selection.

I hope this is good solution to this request.

**Comment by novakwh** [comment]
This sounds great, thanks!
