### ISSUE TITLE
Make inactive controls invisible in Welcome dialog

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1705]
In the new Welcome dialog, when using "Copy an existing project" or "Create an example project", the slider knob things under "Project Notes" are correctly greyed out and inactive. There seems to be no according Qt style for input boxes under "Chapter and Scenes".

The idea is to just make all inactive controls invisible.

_Originally posted in https://github.com/vkbo/novelWriter/discussions/1699#discussioncomment-8501485_

**Comment by vkbo** [comment]
The reason they weren't made inactive in the beta is that every single item has to be toggled, since it isn't possible to hide rows in the form layout. I'll look into if there is a better way of doing this.
