### ISSUE TITLE
Spell-checking character or place names

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1722]
Observation: 90% of the entries in my custom word list are character or place names.

Consider this character:
`@char: Supreme Chief Frodo d'Arcolena`

novelWriter already knows the character. All components of the name could be automatically added to the custom word list:
`Supreme,Chief,Frodo,d'Arcolena`

Remarks:
- duplicating words already in the English dictionary (`Supreme` or `Chief`) shouldn't do harm.
- auto-added words do not need to appear in the saved per-project custom word list, as they are already defined in the project notes
- this suggestion does not consider declension (fortunately not many languages have this problem)

If for some reason automatic add is not desirable, manual add might work. I would like the ability to put something like this in the project note for this character:

```
@tag: Supreme Chief Frodo d'Arcolena
@spell: Frodo,d'Arcolena
```
(the `@tag` line is already auto-created if novelwriter creates a project note)
This keeps the character (place,...) definition and its spell-checking words in one place, `@spell` would be a new tag to allow defining a custom word directly within a document.

**Comment by vkbo** [comment]
> novelWriter already knows the character. All components of the name could be automatically added to the custom word list

Hmm, is it really that much work to right-click and add them? I don't like the idea of the app assuming something is spelled correctly and adding it to a custom dictionary.

> * auto-added words do not need to appear in the saved per-project custom word list, as they are already defined in the project notes
> * this suggestion does not consider declension (fortunately not many languages have this problem)

The spell checking is provided by a third party library, and not a noverlWriter code. The custom word list is fed to this library when the project is open, and everything from there on is handled by it. Beyond that, all novelWriter does is ask for each word in a document whether the word is correct or not. Any processing is handled by the library.

This library is a wrapper for a set of standard open source spell checker tools available in all sorts of office type software. Their behaviour is pretty standard, and I can't really do much about how they work,

> If for some reason automatic add is not desirable, manual add might work. I would like the ability to put something like this in the project note for this character:
> 
> ```
> @tag: Supreme Chief Frodo d'Arcolena
> @spell: Frodo,d'Arcolena
> ```

That seems to me to be more work than just right-clicking on them.

**Comment by awqk** [comment]
> Hmm, is it really that much work to right-click and add them?

Now that you mention it, there is indeed this menu item on the context menu. In hindsight, it appears hard to overlook.

**Comment by vkbo** [comment]
> In hindsight, it appears hard to overlook.

The power of hindsight right there 😄 

I think it would be easier to use that than any of the other solutions proposed, and I don't particularly like the idea of populating the custom dictionary automatically.

Can this feature request be closed then?

**Comment by awqk** [comment]
> I don't particularly like the idea of populating the custom dictionary automatically.

I don't either, but I also think it might be neat to have it work without the words actually appearing in any dictionary. novelWriter already has this information, so it could be used. This might be an idea to keep somewhere in the back of your head.

> Can this feature request be closed then?

Yes, please go ahead.

On another note, perhaps the menu item labels can be improved, and the documentation as well. One and the same thing is referred to using different terms: dictionary, custom words, and project word list.

**Comment by vkbo** [comment]
I think "Add Word to Dictionary" is about as clear as it can get. It is actually added to the dictionary, even though between sessions it is saved in a different file (which is an implementation detail). I don't think that is the limiting factor here. Almost all software I use has this menu entry in a similar way. It is pretty standard.
