### ISSUE TITLE
Main GUI wording improvements

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1726]
There are places in the main GUI where wording and its consistency can be improved. Here are some instances taken from Crowdin plus some of my own observations. (It's hard not to do English QA while translating, but it's also cumbersome to create a new GH issue for every single observation.)

# Headers / Headings

_Heading_ is the word [used in the documentation](https://novelwriter.io/docs/int_glossary.html#) in reference to section titles. But _headers_ and _headings_ seem to be used interchangeably. I suggest to stick to _headings_ when it refers to titling (e.g. “Heading level 1”), and to _headers_ in reference to the page header across the different Views (e.g. “Show full path in document header”).

If this suggestion was accepted, then all strings mentioning _headers_ in the Split Document window must be changed to _headings_. No further changes needed.

This will simplify translations as well. Since there is already a singular string for _Headings_, it will be then unambiguous to translators.

# Partition / Title

Pointed by @HeyMyian on Crowdin: the documentation refers to the topmost section heading as a “Partition”, but in the Split Document window dropdown list, a string referring to _Partition_ mentions _Title_ instead:

> Key: GuiDocSplit['Split on Header Level 1 (Title)']
> ./novelwriter/dialogs/docsplit.py:84

I believe this is the only instance which would need to be changed to _Partition_ in order to preserve consistency.

# Convert quotes

Under Format menu, the single/double quote “conversion” options refer to the ability to replace regular enclosing `'` / `"` quotes with the ones configured as opening and closing quotes, by default typographical choices.

The problem is _convert_  does not fully express what the feature actually does (and the documentation doesn't cover it) and so its purpose remains obscure and possibly unused. Some suggestions for improving those strings:

- _Streamline single/double quotes_
- _Embellish single/double quotes_
- _Post-process single/double quotes_
- _Stylise single/double quotes_

# Duplicate From Here

In the Project Tree, item context menu option, only shows for parent items. The action taken is merely a duplication of the item and all of its sub-items. In general, for other applications, _From Here_ means not children but siblings in increasing sort order.

In any case, duplication in itself implies a copy of the item and its item contents, rather than only the single parent item. The implication exists in other software too (think layer groups in non-linear video editing and image editing software, grouped elements in office productivity applications).

My suggestion is to remove "From Here" from the string.

> Key: _TreeContextMenu['Duplicate from Here']
> ../novelwriter/gui/projtree.py:1952
> Project Tree > Context Menu 2

**Comment by vkbo** [comment]
> I suggest to stick to _headings_ when it refers to titling (e.g. “Heading level 1”), and to _headers_ in reference to the page header across the different Views (e.g. “Show full path in document header”).

Agreed

> I believe this is the only instance which would need to be changed to _Partition_ in order to preserve consistency.

Agreed

> The problem is _convert_ does not fully express what the feature actually does (and the documentation doesn't cover it) and so its purpose remains obscure and possibly unused. Some suggestions for improving those strings:
> * _Streamline single/double quotes_
> * _Embellish single/double quotes_
> * _Post-process single/double quotes_
> * _Stylise single/double quotes_

With the exception of the second option, the other three convey little or no in formation about what this does. The words can mean pretty much anything. The second option uses a very uncommon word.

A more friendly text may simply be "Replace Straight Single/Double Quotes".

> My suggestion is to remove "From Here" from the string.

Sure, that makes sense too.

**Comment by vkbo** [comment]
When searching through the code, I found a lot of usages of "Header" and "Headers", and I updated all I found in PR #1727. I also updated code comments and function names for consistency internally in the code. As I mentioned, I'll leave this out of the 2.3 release since it triggers changes in the translations files, and most languages are already completed.

I'm leaving this open for a bit due to the question of how to label the replace quotes feature.

I also found an issue with the multi-select context menu for moving items to trash or deleting them. I made a fix for that as well in #1728, but that's needed for 2.3 since it's a bug. That too required a translation string, but I decided to just reuse an existing one to avoid triggering more translation work.

**Comment by tmarplatt** [comment]
> The second option uses a very uncommon word.

In software in general? Yes, nowhere common. But your novel-writing users are doubtlessly going to know that word (or another of similar meaning). Worst case, they will be glad to find out the meaning of it!

Some of these menu options really call for status-bar description of their purpose on hover. Or perhaps their own documentation entry. But that's another issue entirely.

**Comment by vkbo** [comment]
> In software in general? Yes, nowhere common. But your novel-writing users are doubtlessly going to know that word (or another of similar meaning). Worst case, they will be glad to find out the meaning of it!

Renaming them should make them easier to understand, not harder.

> Some of these menu options really call for status-bar description of their purpose on hover. Or perhaps their own documentation entry. But that's another issue entirely.

They used to all have that, but we actually have a limit on translation words, so I removed them since they are of marginal use beyond learning to use the UI. I've considered a "what's this" help feature that directs to the documentation instead.
