### ISSUE TITLE
[Theme contribution] Cyberpunk Night (an AMOLED black theme)

### ISSUE THREAD

**Issue by alemvigh** [vkbo/novelWriter#1730]
I've created an AMOLED black/Cyberpunk style theme that is easy on the eyes and perfect for late night writing sessions.

![image](https://github.com/vkbo/novelWriter/assets/162419588/be825e45-3d23-414c-9992-d04a7e98ab41)

![image](https://github.com/vkbo/novelWriter/assets/162419588/6901c895-566a-405c-a884-9006d53083be)

Feel free to include it in the default selection of themes since there's currently a lack of dark mode themes, especially AMOLED black ones.

[cyberpunk_night.tar.gz](https://github.com/vkbo/novelWriter/files/14506531/cyberpunk_night.tar.gz)

**Comment by vkbo** [comment]
Looks great, I'm happy to take this as a contribution. Could you possibly make a pull request for it? There are a few review points to go through for new themes.

**Comment by vkbo** [comment]
I realise you may not be familiar with GitHub, since you just created the account. If so, I can of course do it.

**Comment by alemvigh** [comment]
@vkbo You're right. I'm not that familiar with Github or with any special requirements for this project, so if you could do it that would be appreciated. :+1:

I noticed that there's a new version upcoming, so if anything changed regarding the way themes work let me know and I'll update accordingly and test it with the AppImage of the new version.

Also feel free to let me know if anything looks broken on systems other than Linux since I've only got that to test with.

**Comment by alemvigh** [comment]
Updated the syntax theme because it was missing the "optional" tag as it isn't included on https://novelwriter.io/docs/int_customise.html - I only found it by inspecting one of the original themes. :smiley: 

[cyberpunk_night.tar.gz](https://github.com/vkbo/novelWriter/files/14508861/cyberpunk_night.tar.gz)

**Comment by vkbo** [comment]
The "optional" entry is a 2.3 feature, which has not been released yet. That's why it is not in the documentation yet.

**Comment by alemvigh** [comment]
[cyberpunk_night.tar.gz](https://github.com/vkbo/novelWriter/files/14510034/cyberpunk_night.tar.gz)

Changed errorline to be different from spellcheckline (using the color from the night_owl theme).

**Comment by vkbo** [comment]
It would be better if the spell check line was consistent with the other colours rather than copied from a different theme. Also, you can just paste the text here instead of the tar.gz files. Just wrap them in three backticks like so: ```.

I would also prefer if you didn't set multiple colour settings that are used to distinguish different elements to the same colour. It defeats some of the purpose of syntax highlighting.

```
[Main]
name        = Cyberpunk Night
description = A taste of the future 80's
author      = Anders Lemvigh
credit      = 
url         = https://github.com/alemvigh
license     = CC BY-SA 4.0
licenseurl  = https://creativecommons.org/licenses/by-sa/4.0/
icontheme   = typicons_dark

[Palette]
window          = 0, 0, 0
windowtext      = 150, 150, 150
base            = 0, 0, 0
alternatebase   = 0, 0, 0
text            = 150,150,150
tooltipbase     = 50, 0, 180
tooltiptext     = 255,255,255
button          = 0, 0, 0
buttontext      = 150, 150, 150
brighttext      = 255,255,255
highlight       = 50, 0, 180
highlightedtext = 255,255,255
link            = 77,77,255
linkvisited     = 255,0,255

[GUI]
statusnone      = 50, 50, 50
statussaved     = 0, 255, 0
statusunsaved   = 255, 77, 77
```

```
[Main]
name       = Cyberpunk Night
author     = Anders Lemvigh
credit     = 
url        = https://github.com/alemvigh
license    = CC BY-SA 4.0
licenseurl = https://creativecommons.org/licenses/by-sa/4.0/

[Syntax]
background     =   0,0,0
text           =   150,150,150
link           =   77,77,255
headertext     =   180, 180, 180
headertag      =   50, 0, 180
emphasis       =   0,255,255
straightquotes =   0,255,0
doublequotes   =   0,255,0
singlequotes   =   0,255,0
hidden         =   128,0,128
shortcode      =   255,0,255
keyword        =   0,255,255
value          =   255,77,77
spellcheckline =   255,77,77
errorline      =   173,219,103
replacetag     =   0,255,255
modifier       =   255,0,255
optional       =   180,180,180
```

**Comment by alemvigh** [comment]
@vkbo I'm editing the colors to create more separation between the tag types. Is there a sample text I can use? There are some tags like "replacetag" that I haven't been able to test yet.

**Comment by vkbo** [comment]
You can create an example project from "new project" which will have everything demonstrated.

**Comment by alemvigh** [comment]
@vkbo Thanks! One tag I can't find is "modifier" - how can I make some text that uses it? Also, I'm not sure which tag that corresponds to non-breaking spaces. It seems to use a color that I haven't defined.

**Comment by vkbo** [comment]
"modifier" is the colour applied to the "%Synopsis:" part of your screenshot. It is referring to the special modifiers for comments.

**Comment by vkbo** [comment]
You can insert non-breaking spaced from the inert menu. They should be shown with a different background colour than the regular background. It's the same thing that LibreOffice does. That's where the feature is from.

**Comment by alemvigh** [comment]
@vkbo I figured out that non-breaking spaces take their color from the "emphasis" tag. Not sure if that's intended or something I should raise an issue for, but at least it allows me to complete the theme now. :smile: 

`emphasis       =     255, 0, 0`

![image](https://github.com/vkbo/novelWriter/assets/162419588/3c263ebc-c5a1-441b-97f0-c0bf5ef450c5)

**Comment by vkbo** [comment]
Yeah, that's probably right.

The theme files are processed here in the code: https://github.com/vkbo/novelWriter/blob/a3bd0d38a4826f93c460fcf8a4317b43463efe5f/novelwriter/gui/theme.py#L276

And applied to the document here: https://github.com/vkbo/novelWriter/blob/a3bd0d38a4826f93c460fcf8a4317b43463efe5f/novelwriter/gui/dochighlight.py#L77

You can track which colour is used for what. There are many colours that are used for multiple things.

**Comment by alemvigh** [comment]
I've tried to create some more visual separation between the tag types here, and hopefully I managed to catch everything:

```
[Main]
name       = Cyberpunk Night
author     = Anders Lemvigh
credit     = 
url        = https://github.com/alemvigh
license    = CC BY-SA 4.0
licenseurl = https://creativecommons.org/licenses/by-sa/4.0/

[Syntax]
background     =     0,  0,  0
text           =   150,150,150
link           =    77,077,255
headertext     =   255,255,255
headertag      =    50,  0,180
emphasis       =     0,255,255
straightquotes =     7, 27,219
doublequotes   =     0,255,  0
singlequotes   =     0,140,255
hidden         =    50, 50, 70
shortcode      =   255,255,  0
keyword        =   255,100,255
value          =   255,150, 10
spellcheckline =   242, 72, 23
errorline      =   186,218,  4
replacetag     =   0,  0,  180
modifier       =   144,142,176
optional       =   180,180,180

```
![image](https://github.com/vkbo/novelWriter/assets/162419588/f0b0a8a6-425a-49a4-9ceb-2eaac003c242)

**Comment by vkbo** [comment]
Looks good! I still think the comments need to be a bit easier to read.

Also, for the GUI theme, you must set window, base and alternatebase to different shades. In particular alternatebase is used for showing which headings are in the currently open document in the Novel view. If it's the same colour as the background, this feature doesn't work. It is less of a problem that window and base are the same shade.

**Comment by alemvigh** [comment]
After trying a few variations I will need to stick with "0,0,0" for "window" and "base" to keep the AMOLED Black approach, but I can see what you mean regarding "alternatebase" and put together a new version of the GUI theme (some other tags were slightly tweaked for increased visibility as well):

```
[Main]
name        = Cyberpunk Night
description = A taste of the future 80's
author      = Anders Lemvigh
credit      = 
url         = https://github.com/alemvigh
license     = CC BY-SA 4.0
licenseurl  = https://creativecommons.org/licenses/by-sa/4.0/
icontheme   = typicons_dark

[Palette]
window          =   0,  0,  0
windowtext      = 150,150,150
base            =   0,  0,  0
alternatebase   =  30, 20, 45
text            = 150,150,150
tooltipbase     =  40, 20, 70
tooltiptext     = 255,255,255
button          =  5,  0,  10
buttontext      = 150,150,150
brighttext      = 255,255,255
highlight       =  50, 30, 80
highlightedtext = 255,255,255
link            =  77, 77,255
linkvisited     =  50,  0, 80

[GUI]
statusnone      =  50, 50, 50
statussaved     =  77,255, 77
statusunsaved   = 255, 77, 77
```

**Comment by alemvigh** [comment]
@vkbo Once you need updates for 2.4, could you please create an issue and assign it to me? Thanks!

**Comment by vkbo** [comment]
Sure, no problem. Do you mind just creating a fork of this repo and contribute it as a pull request? There may be future changes as well. I believe this is simple enough that you can edit the theme files directly on your fork of the repo on the GitHub website and don't need the full git setup on your computer to do it.

**Comment by alemvigh** [comment]
I'll try to figure that out.
