### ISSUE TITLE
Space (" ") shows up as a spelling error continuously while typing

### ISSUE THREAD

**Issue by alemvigh** [vkbo/novelWriter#1731]
I'm not sure if this is a drawback in the software or in the spell checking engine, but the space character " " shows up as a spelling error continuously while typing:

![image](https://github.com/vkbo/novelWriter/assets/162419588/642c3a59-fb39-4eba-96b6-1c5fc3561cb4)

I can see why this would make sense if a paragraph ends with a blank space and a new line, but before that new line is added it makes very limited sense to mark this as a spelling error.

It's not possible to right click the underlined space and add it as a recognized "word" in the spell checker either.

This issue shows up both in the current stable version and in 2.3 RC 1 (tested as AppImage under Manjaro).

**Comment by alemvigh** [comment]
This can be closed. I just realized that this is a feature enabled by "Preferences / Text Editing / Highlight multiple or trailing spaces".

**Comment by vkbo** [comment]
Yes, it's a feature. I assume you're using your own theme here, and the underline should not be red for these errors. That needs to be fixed in the theme. They need to be distinct from spell errors.
