### ISSUE TITLE
console_scripts entry point is not installed (typo in setup.cfg)

### ISSUE THREAD

**Issue by sstandre** [vkbo/novelWriter#1732]
There is a typo in setup.cfg that results in novelwriter-cli never being installed.

Setuptools documentation on entry points says that the allowed keys for script entry points under `[options.entry_points]`are `console_scripts` and `gui_scripts`
https://setuptools.pypa.io/en/latest/userguide/entry_point.html

Howerver, setup.cfg uses `console_script` (without final s) which is not recognized, and so novelwriter-cli is not installed.
https://github.com/vkbo/novelWriter/blob/main/setup.cfg#L44

Given that both novelwriter-cli and novelwriter both point to `novelwriter:main` it may be superfluous keeping both

**Comment by vkbo** [comment]
This is just legacy stuff. The CLI entry point has never been used. The GUI entry point is the one in actual use. I'll just remove it.

The original idea was to avoid spawning a GUI in the CLI case, but this is handled inside the main function anyway, so there's no need for the additional entry point.
