### ISSUE TITLE
Crowdin: [empty translation] is overridden by English translation

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1750]
There is a string `Add` that I translated as [empty translation] because no single word here makes sense in German. [empty translation] however did not carry over to the application, "Add" is still displayed. Is there a way to do this?

**Comment by HeyMyian** [comment]
> These are the strings for adding new chapters and scenes on the Welcome dialog I assume?

Yes, that's where it is.

**Comment by vkbo** [comment]
I added a custom layout box that can take a translated string with a `{0}` in it and insert the control widget at the `{0}`. It will handle any positioning in the string, so now it should behave the same way as a translated string with a value inserted.

The strings on the form are now:

* `"Add {0} chapter documents"`
* `"Add {0} scene documents (to each chapter)"`

You should now be able to drop the "Add" bit.

https://github.com/vkbo/novelWriter/blob/ea50ae327994aa111460a32d67a6a1edbe31cec4/novelwriter/extensions/configlayout.py#L275-L293

**Comment by HeyMyian** [comment]
That works, thank you.

**Comment by vkbo** [comment]
It does indeed work. Just tested with your new translation.

![image](https://github.com/vkbo/novelWriter/assets/1619840/2dc22f0f-a926-44fa-8cc1-3e439bc45c17)
