### ISSUE TITLE
Untranslated string in Show File Details

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1752]
> Created: Unknown

"Unknown" is not translated.

![2024-03-12___16_57_56](https://github.com/vkbo/novelWriter/assets/60368695/8d6e23d1-6ec4-487a-8746-d7c6d59ca679)

**Comment by vkbo** [comment]
The created/updated dates are taken verbatim from the raw text document, and the file format is not localised, so this cannot be passed through the translation framework. It is only an issue for old files from before this feature was added, so it will fade away eventually.

See for instance the file from the sample project:
```md
%%~name: Mars
%%~path: 15c4492bd5107/5eaea4e8cdee8
%%~kind: WORLD/NOTE
%%~hash: 0838371bc03e31f503fd12a8617d94ef36e5f7c7
%%~date: Unknown/2023-08-25 16:52:07
# Mars

@tag: Mars
@location: Space

It’s red. Dusty and red.
```
