### ISSUE TITLE
Suppress scene header at start of build output

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1756]
The non-existence of a text paragraph before the scene header should be enough to block scene headers/headings.

In my use case (short story), I do not want either level 1 or level 2 headers, because pandoc and the docx template already take care of title, author etc. The document is built from "standard markdown" build output, prefixed with a [yaml metadata block](https://pandoc.org/MANUAL.html#extension-yaml_metadata_block).

Admittedly, this is nothing serious, only a minor annoyance.
Related: #1704,#1711,#1716

**Comment by vkbo** [comment]
That's fairly easy to fix. Currently the flag to skip next separator is set to False initially, set to True when a level 1 or 2 heading is encountered, and set to False after a level 3 heading has been processed.

All that is needed for your use case is to set it to True initially.

Text paragraphs have no impact on separator decision any more, so with or without initial text, the separator will be skipped. Only a level 1 or 2 heading will cause a skip as it is now.

**Comment by vkbo** [comment]
Another option that could solve such a use case is to add a switch to hide partition and chapter headers from the output. Same as for scene and section. That way you can add the headings if you want to, but just not include them in the output.

I can add both options really. This could be useful for other cases as well.

**Comment by awqk** [comment]
> All that is needed for your use case is to set it to True initially.

This sounds like it would be enough. It's unlikely to break other things, with the benefit that it works out of the box without needing any user interaction.

> [...] add a switch to hide partition and chapter headers from the output. [...]
> 
> I can add both options really. This could be useful for other cases as well.

I can't think of another use case, though it would add some symmetry to the build dialog.

**Comment by vkbo** [comment]
> I can't think of another use case, though it would add some symmetry to the build dialog.

For partitions, there definitely is a use case. I create partitions for each act in my story. They are useful to have in the drafts, but maybe not in the final manuscript.

For chapters, maybe less so. Although you can write chapter-less novels. Terry Pratchett did it all the time. It is still useful to have the option to add such headers as separators for the project tree, even if they're not actual chapters and you don't intend to include them in the manuscript.
