### ISSUE TITLE
placeholders in build settings dialog

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1757]
I've been fooling around with the build settings dialog:

- Headings page: insert and apply buttons should be disabled while not editing, like the editing panel
- Output page: Shouldn't it be possible for things like {Title} to go into the .odt page header?

The same editing mechanism could be used for all of them: a revert to default button, and the insertables could be the same.

**Comment by vkbo** [comment]
> Headings page: insert and apply buttons should be disabled while not editing, like the editing panel

Maybe? Not sure. They don't do anything when there is no heading being edited, but it is useful to be able to see what's in the Insert dropdown.

> Output page: Shouldn't it be possible for things like {Title} to go into the .odt page header?

Which `{Title}` would that be?

> The same editing mechanism could be used for all of them: a revert to default button, and the insertables could be the same.

You mean a revert button for the heading formats?

**Comment by vkbo** [comment]
> It took me a few seconds to realize I need to click edit before the drop down does anything, even with text selected in one of the headings.

Well, as long as you realised fairly quickly, it isn't a big deal. I've considered adding a help text, but the documentation covers it already.

> A muddy issue, especially if there are many titles on a single page (is this possible?). Otherwise, go for the last one seen up to the end of the page. I would suppose there will be only one title selected for a build in most cases. Also, `{Title}` is already ambiguous for the title/chapter/unnamed headings. Maybe `{Text}`, `{Label}`, or `{Value}` would be better?

The header is set once for the entire ODT document, so extracting it for the page isn't really an option with this feature. But you're right, this is very ambiguous. If you don't want the project name inserted, the best option is really just to type the text you want there.

> Exactly. If there is one for the page header, why not for the chapter heading etc.?

They are completely unrelated.

**Comment by awqk** [comment]
I see the problem.

I guess the revert button for the .odt page header is just there to remind users which placeholders are available, and thinking that `{Title}` might work was wishful at best.

You could offer the build name instead, which is known at the start of the build.

**Comment by vkbo** [comment]
Yes, the revert button is only there to show what is available. Adding more options means I need a form to generate it with buttons and everything, which is very much overkill for the use case. I am considering removing everything but the `{Page}` option actually, and just let the user fill in whatever they want.
