### ISSUE TITLE
Support narrator break symbols and highlight rules

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#1771]
**The problem**

In written Spanish we use em dashes `—` as a _double symbol_ to enclose parenthetical narrator breaks in the middle of a dialogue paragraph (among other possible uses).

To illustrate with a [”continuation quote”](https://www.rae.es/dpd/comillas#S138535784160650014) using Spanish punctuation:

> »Oh, a wizard, yeah, I knew that already. —Harry pulled a wand out of thin air, to the astonishment of Hagrid—. And you have trespassed my uncle's home, so I better teach you a lesson, or two».

novelWriter currently does not support narrator breaks. What this means in the example above is the entire paragraph will be highlighted in colour (provided continuation quotes have been configured in place of regular quotes), highlighting the narrator break as if it was spoken dialogue too.

In an equivalent English paragraph, such break would be rendered in neutral text colour. The English rule is to close quotes before breaks, as opposed to using parenthetical symbols, so the problem is absent.

**The solution**

- Allow users to configure narrator break enclosing symbols. These should escape colour coding within a quoted text section.
- Also allow configuring open-ended narrator breaks (without a closing symbol).

**Comment by vkbo** [comment]
The highlighting is done via RegEx. RegEx is not very good at nested processing, but a possible solution would be to reset the text colour of text wrapped in — after quote highlighting is performed. I can test to see what's possible here. As long the dash isn't used in other ways in the same text, it should be fine.

**Comment by vkbo** [comment]
Played around with it a little. It is quite easy to achieve.

![image](https://github.com/vkbo/novelWriter/assets/1619840/a7bbc4c0-768b-4690-8e17-26ac7feb6afc)

Question: Does the second line, with added space padding, qualify according to this rule, or not?

**Comment by tmarplatt** [comment]
> Question: Does the second line, with added space padding, qualify according to this rule, or not?

If you're asking in terms of Spanish punctuation rules, then no: em dashes must not add padding when enclosing a parenthetical text section.

But if you're thinking of “catch all” narrator-break un-highlighting then yes, by all means.

**Comment by vkbo** [comment]
> But if you're thinking of “catch all” narrator-break un-highlighting then yes, by all means.

I think a first implementation should be with Spanish rules, and allowing spaces can be added if needed. I don't want to add it by default as you can have pauses within the text like this, but with either no spaces at all, or spaces on either side. Keeping the Spanish rule will ignore both those cases.
