### ISSUE TITLE
Missing icons when using a custom icon theme

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1780]
When using a custom icon theme, and new novelWriter versions add new icons, these icons will be missing from the UI until I manually copy the icons and their definitions to /AppData/Roaming or Linux equivalent. The same might be true for when updates introduce new definitions for UI colors or syntax highlighting colors. If that is the case, I've simply never noticed.

Ideally, missing icons and other definitions should fallback to either the light or dark standard theme as defined in the novelWriter core files. Is that possible?

**Comment by vkbo** [comment]
Not with the way it's currently set up, no. The theme settings correspond directly to the name of the theme file. Loading multiple themes is not supported at the moment.

novelWriter used to have fallback icons, but it was a real pain to maintain. Theme colours fall back to [fixed colours](https://novelwriter.io/docs/int_customise.html). Icons fall back to a blank icon. I could make the missing icon a little more obvious by falling back to something more visible though. I can add a big red cross fallback icon.

**Comment by vkbo** [comment]
By the way, the documentation now lists when new syntax/theme colours were added, so it's possible to include them.

**Comment by vkbo** [comment]
I've added a very obvious (I hope) placeholder icon.

![image](https://github.com/vkbo/novelWriter/assets/1619840/303d3c70-613b-446a-acaa-c2e9ac58a213)

**Comment by vkbo** [comment]
Merged. I also cleaned up the styling of the new search tool a little.
