### ISSUE TITLE
New Project Wizard Options

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1811]
Setting 'add chapters' to '0' still adds 5 scenes, unless 'add scenes' is also '0'.

Maybe this is a feature no one really needs and you are overdoing things here :smiley:.
I suggest you always add 1 chapter with 1 scene (non-configurable) and let the user create new chapters and scenes as needed.

**Comment by vkbo** [comment]
If you hover the settings field for chapters it says that setting it to 0 will add only scenes. This is exactly how the old wizard worked as well, and it also had 5 as the default. It could of course default to 0, but I don't intend to remove this.

**Comment by awqk** [comment]
> If you hover the settings field for chapters it says that setting it to 0 will add only scenes.

It's still not very intuitive, and requires hovering doing nothing for some time at exactly the right place. Come to think of it, this is the first time a hover box appeared for me. Perhaps my hands are shaking or I am too fast :smiley:.

> This is exactly how the old wizard worked as well, and it also had 5 as the default. It could of course default to 0 or 1, but I don't intend to remove this.

If you don't want to remove it, I suggest default 1 for both fields. It still offers some guidance to new users on how novel documents are supposed to be used, and it is a good start otherwise.

**Comment by vkbo** [comment]
Accidentally generating a few scene documents is anyway not an issue. I know people are using this feature, but it isn't really how I start a new project either. If you create a lot of projects, it's probably better to set up a template project, which is available as another new project option now.

The count of 5 is mostly there as an example. But I can certainly reduce the default number. It's trivially easy to increase it after all.
