### ISSUE TITLE
Add a mentions kewword

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#1822]
I find that I sometimes need to reference tags in my text that aren't actually part of the scene, just mentioned. For instance another character. I usually add them to the `@char` list, but it would make more sense to have a `@mention` keyword for this. It would be useful to know where a character or place is first mentioned even if they're not part of the scene.

A `@mention` keyword could allow any tag of any type to be referenced, and show up as a column in the outline.

**Comment by xahodo** [comment]
Perhaps preface the mentioned tags with what type of tag it is, for example: `CH: Charles de Gaulle` for a character with that name, as opposed to the airport.

**Comment by vkbo** [comment]
Tags are unique already, even across categories, so that is redundant. There can be no confusion as the tag itself must include the distinction if both in your example are in use.
