### ISSUE TITLE
Build Tool Selection Settings

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1838]
I wonder why there's a different icon for the include button vs. the icon shown in the panel? I also fail to grasp the logic of the three buttons: include, exclude, reset. Reset to what? Wouldn't two buttons (include/exclude) suffice? Perhaps the real fix here is in the documentation.

**Comment by vkbo** [comment]
This is already described in the documentation: https://novelwriter.io/docs/project_manuscript.html#document-selection
