### ISSUE TITLE
Build Tool Output Settings and Preview

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1839]
At the moment no output settings are applied to the preview. I wonder about the logic governing this, but the "Preserve Hard Line Breaks" option would be nice-to-have, maybe "First Line Indent", too.

"Preserve Hard Line Breaks" also sounds like it could be applied to all output formats, not only Markdown.

**Comment by vkbo** [comment]
> At the moment no output settings are applied to the preview. I wonder about the logic governing this, but the "Preserve Hard Line Breaks" option would be nice-to-have, maybe "First Line Indent", too.

Output settings are only applied to the specific file formats that support it. The preview is not intended to preview specific output formats, but the text that goes into it. The preview window isn't capable of showing all of them.

"Preserve Hard Line Breaks" can be supported if they are moved up.

> "Preserve Hard Line Breaks" also sounds like it could be applied to all output formats, not only Markdown.

Yes, it should probably be moved up to the Format > Text Options section and applied to all.
