### ISSUE TITLE
The Outline pane always displays 1 in the Line column

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#184]
The Outline pane always displays 1 in the Line column. This may or may not be an issue except that at this stage of novelWriter's development I have no idea what the Line column is telling me. Consider updating the documentation for this feature.

**Comment by vkbo** [comment]
It did this when there was no project opened as the Outline was only built when there was an actual project. I've already changed this to the default view in lack of a project is a single column with the header "Title". This was added in PR #183 and should be fixes. Can you confirm?

The entire view is customisable per project, so it has to be generated as needed.

The documentation will be updated when the tool is complete and before release 0.5.

**Comment by johnblommers** [comment]
Yes, I can confirm:

> the default view in lack of a project is a single column with the header "Title".

**Comment by vkbo** [comment]
Great. Then I can close this.
