### ISSUE TITLE
Regular expression search

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1856]
Regular expression search might be useful in case of larger projects - the kind of stuff NW is aimed at.

Let me give an example use case for regular expressions:

I have written a lot on my project. Turns out a character I had previously thought of as non-important, is actually pretty important. I hadn't written a character note on the character (as I considered it not important), and I don't quite remember what the exact spelling of his name was. Was it Justice or Justin? Was it Doorman, Dormaan, or Dorman... or perhaps it was Dormen? Anyway, I fire up the search, check the regular expression checkbox, and enter the regular expression to filter for any potential candidates. The search returns all results in a nicely clickable list, so I can see where there were matches. This allows me to read the relevant parts and build a consistent note on the character.

Now, reading back would be ok if it were below a certain character count, but above, say, 10.000 words or 3 documents it gets rather tedious. Also, With the 2 options of first names and 4 options of surnames, you potentially end up with a... lot... of search queries with which to look for.

**Comment by vkbo** [comment]
Both the in-document search and the global search tools support regular expressions, and they have been since the features were added. But since it is an "advanced" feature, you have to explicitly enable it by toggling the `.*` search option button.

![image](https://github.com/vkbo/novelWriter/assets/1619840/c8a370b8-796c-4ef7-8b1b-8dcb3bda8bc1)

**Comment by vkbo** [comment]
Both search tools already allow for regular expression search by toggling the `.*` button.

![image](https://github.com/vkbo/novelWriter/assets/1619840/25899059-4517-47f2-85c6-5128748c3e73)
