### ISSUE TITLE
I hope to add the function of a role relationship line chart.

### ISSUE THREAD

**Issue by lianglivi** [vkbo/novelWriter#1860]
**Note**: Feature requests without a description will not be considered.
Please also check if an issue already exists on this feature.
Please provide a description covering the following points, if applicable:

* A clear and concise description of what the problem is. Ex. I'm always frustrated when ...
* A clear and concise description of what you want to happen.
* A clear and concise description of any alternative solutions or features you've considered.
* If applicable, add screenshots to help explain your request.

**Comment by vkbo** [comment]
I have no idea what this is about. As stated in the place-holder text you left here "Feature requests without a description will not be considered."
