### ISSUE TITLE
Cannot add dictionaries using the tool.

### ISSUE THREAD

**Issue by Totobal5** [vkbo/novelWriter#1874]
Trying to install the following dictionary: https://www.softmaker.net/down/hunspell/softmaker-hunspell-spanish-101.sox will produce the following crash:

Environment:
novelWriter Version: 2.4.1
Host OS: win32 (10.0.19045)
Python: 3.12.3 (0x30c03f0)
Qt: 5.15.2, PyQt: 5.15.10
enchant: 3.2.2

FileNotFoundError:
[WinError 3] El sistema no puede encontrar la ruta especificada: 'C:\\Users\\my_username\\AppData\\Local\\enchant\\hunspell'

Traceback:
  File "C:\Program Files\novelWriter\novelwriter\tools\dictionaries.py", line 203, in _doImportHunspell
    hunspell.mkdir(exist_ok=True)

  File "pathlib.py", line 1311, in mkdir

making a custom enchan/hunspell folder in my AppData fix the problem and let me install the dictionary.

**Comment by vkbo** [comment]
I'm guessing the enchant folder doesn't exist by default either. I'll investigate.

**Comment by Totobal5** [comment]
Yes, i made the enchant folder to see if it fix the bug !

**Comment by vkbo** [comment]
Fixed. I'll do a 2.4.3 release soon as there is another bug I want to get fixed too.
