### ISSUE TITLE
Changing font does not persist after closing and reopening novelWriter

### ISSUE THREAD

**Issue by locrianz** [vkbo/novelWriter#1875]
I'm using version 2.4.2 installed via the PPA on Linux Mint 21.3.

I've gone into my preferences and changed the *document* font family and font size. The changes apply successfully. But when I close the app and reopen it, the font has reverted back to default. Oddly, my choices are still reflected when I open preferences again and hitting "Apply" brings them back.

**Comment by vkbo** [comment]
This is probably related to #1862, which I cannot reproduce either on any other OS I've tried on. There's something weird going on with the document font on Mint.

**Comment by vkbo** [comment]
I've set up a Mint 21.3 VM, and can reproduce the error there, as well as #1862. I'm pretty sure what change it's related to, and I'm also pretty sure there is a Qt bug behind it, but I'll figure out a workaround.
