### ISSUE TITLE
indicator per project tree item whether it's saved

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1888]
Recently I made a bug report (#1887), where I made the incorrect assumption that a document, once left, would automatically be saved and changes would automatically trickle through to the outline view.

Now, I can imagine somebody not wanting to save a document for various reasons (f.e. not being 100% sure whether they're happy with the document, whether they want to keep this change) .

So, I think it would be a good idea to add a small indicator to each unsaved item in the project tree. Also, a general icon at the top or bottom of the project tree to make the user aware the project contains any unsaved items at all (in case the list of items in the project tree becomes larger than can be displayed) would be useful. This warns the user there are unsaved documents, which can prevent confusion (as happened earlier with me). It could be achieved with a different icon for each document type which has a small indicator in, say, the top left.

![Image 1](https://github.com/vkbo/novelWriter/assets/85426904/36aea496-45f8-4f50-a1c9-e9de3d2af693) <- saved
![Image 2](https://github.com/vkbo/novelWriter/assets/85426904/0dcb9168-f06a-45c2-8674-45781057113f) <- example icon for an unsaved item.

**Comment by vkbo** [comment]
That would be redundant. Only the document currently open in the editor can be in an unsaved state. All closed documents are saved to disk. There is an indicator in the footer of novelWriter that shows the saved status of the "Editor" and the "Project". The colour of the indicator is theme-dependant, but usually it's red for unsaved and green for saved.

![image](https://github.com/vkbo/novelWriter/assets/1619840/d7b25c35-5cb4-4c43-8e54-76fbe941c0ea)

**Comment by awqk** [comment]
At the moment it's not possible to close without saving, and changes don't stay unsaved for very long, unless you disable auto-save.

Users unsure about saving (for whatever reason) may also be surprised by the fact that the undo history is lost when changing the editor to a different document, like by clicking on a different tree view item, or on a global search result.

#1440 would fix this, once it's possible to have more than one document in an unsaved state. After this improvement, the suggested indicator would be useful.

**Comment by vkbo** [comment]
#1440 will only preserve the undo history for a time, not the unsaved state of the documents. Keeping unsaved data in memory except from in the editor is counter to novelWriter's design philosophy. This is not likely to change. Any implementation that would allow reverting changes would be part of a version history implementation.

**Comment by vkbo** [comment]
> Recently I made a bug report (#1887), where I made the incorrect assumption that a document, once left, would automatically be saved and changes would automatically trickle through to the outline view.

For the record, it is automatically saved and I explained how the outline is updated. Either when you tab to it, or by pressing the refresh button. In either case, the document and meta data is collected automatically. If the auto-save time is too long for your usage, you can change it in Preferences, as I mentioned in the other issue.

**Comment by awqk** [comment]
> #1440 will only preserve the undo history for a time, not the unsaved state of the documents. Keeping unsaved data in memory except from in the editor is counter to novelWriter's design philosophy. This is not likely to change. Any implementation that would allow reverting changes would be part of a version history implementation.

The problem here is that many users expect novelWriter to work similar to other editors, with a bunch of documents in separate files, whereas they should be thinking of the whole project as a single file.

**Comment by awqk** [comment]
Thinking this through:

From a user's point of view, every change can be considered as good as saved (either by auto-save, or save-on-close), unless novelWriter crashes before closing (which hasn't happened to me, yet).

Within a novelWriter session (not considering version control or novelWriter's zip backups), there is some possibility to revert by using undo, limited to the document in the editor, and by the length of the undo history. Once the feature request I mentionened before (#1440) is implemented, this undo may span multiple documents, but it still doesn't offer to choose which document should be saved or not.

Unless you are willing to change something fundamental, the suggested indicator has absolutely no use, and this issue can be closed.

**Comment by vkbo** [comment]
> The problem here is that many users expect novelWriter to work similar to other editors, with a bunch of documents in separate files, whereas they should be thinking of the whole project as a single file.

Yes, and this has been discussed at length in the past. novelWriter isn't a single document editor like Libre Office or Word, it's more like a code editor where you have multiple individual files. Although there are no tabs any more.

While some may be confused by the behaviour, others very much appreciate that data is continuously saved to the disk. It is precisely what I designed it to do for the very point of robustness against data loss. I have no plans of changing this.

That said, #977 will be implemented in such a way that the project is extracted to a temp folder during the session, and zipped back up to the single file after closing. That does give an opportunity to discard changes, which I may add.

But yes, I agree this can be closed. Indicators for each file serve no purpose since it is only the editor that can be in an unsaved state, and it already has an indicator,
