### ISSUE TITLE
Vim-like undo/redo tree

### ISSUE THREAD

**Issue by xahodo** [vkbo/novelWriter#1890]
Situation:
You have entered the following texts (assuming the same line again and again):
- Charlie is drowns Lisa in the ditch. (attempt one)
- Charlie shoots Lisa in the back. (attempt two)
- Charlie hangs Lisa from a tree. (attempt three)

Well, the final product is the third line, but you'd actually want the first line. With regular undo, you'd have to retype everything, but with vim-like undo, you can select, after an undo, which to redo, there could even be an entire tree of such undo options.

Now, such an undo tree could be kept with the document in a separate file. It could even be kept per section (paragraph, sentence, f.e.) basis to make the undo/redo actually useful.

Granted, this won't be particularly useful in Hemmingway mode, but otherwise I see good use for it.

**Comment by vkbo** [comment]
The undo/redo functionality is built into the QTextDocument that renders the text on the screen in the editor. The data and its functionality isn't accessible in the code. For some reason Qt chose to hide it away. Modifying how it works is not an option, so the only option is to write an entirely new undo/redo implementation from scratch in Python. That's not going to happen in the foreseeable future, so I'll just close this right away (sorry).
