### ISSUE TITLE
Saved/unsaved indicators not refreshed when switching theme

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1893]
The saved/unsaved indicator bobbles do not update their colors when switching themes - only when restarting novelWriter. I thought I was broken when I couldn't get their colors to change while experimenting with new themes. It's an extremely minor issue, but it looks to me like an oversight since the theme is supposed to be live-refreshable?

![2024-05-23___23_38_25](https://github.com/vkbo/novelWriter/assets/60368695/d4014a06-bbc2-4038-85ce-4d8854274e8d)

**Comment by vkbo** [comment]
Yeah, these are custom drawn indicators, and need to be recreated when switching theme. It's not a big deal to do. Originally, their colour was not a part of the theme settings, so there was no need to change them.
