### ISSUE TITLE
Remove string "novelWriter" from taskbar button.

### ISSUE THREAD

**Issue by arnehemingway** [vkbo/novelWriter#1910]
Hello, 

The problem I have is that I cannot readily see which project I have open in novelWriter by looking at the taskbar button, so I have two suggestions, to either remove the string "novelWriter" from taskbar button or else move it to be after the project name.  
So in the case of my current project, Ten Days, it would become just "Ten Days" or else "Ten Days - novelWriter".

I prefer the first, because there is already a logo on the left identifying the program, you don't really need the app name as well, plus I find that most other apps don't have their names on their taskbar buttons (novelWriter, Vivavldi, Geany, Nemo, and Brave pictured - only novelWriter shows it's name. 

![image](https://github.com/vkbo/novelWriter/assets/68939268/8664e618-8eac-4b38-a477-be643288d319)

**Comment by arnehemingway** [comment]
If you don't control, then i'm wondering why Cinammon (Mint 21.2) is discriminating only against novelWriter.  If I open Manuskript, then the taskbar button says "Manuskript".  If I open a project called "Ten" then the button changes to "Ten - Manuskript", which is sensible.  It's the same for every other App I've looked at.
And though I appreciate it, there is no need to flip them around just for me if it's no big deal.  Leave it as is and take care of actual issues.

**Comment by vkbo** [comment]
The application window and how it is represented on your desktop is controlled by the system. So what I don't control is what information the desktop environment uses. There is a bunch of settings for an application that you can set from the library novelWriter is built on, but you don't control how they are used, or even if they are used at all. This includes the window icon, window title, app name, app icon and app display name. Clearly Cinnamon on Mint uses the window title value where for instance Gnome uses the app name or app display name.

I can of course change the window title, which is what I did. So by extension I assume Mint will change how it displays it in the task bar as I assume that is where the information is taken from.

**Comment by vkbo** [comment]
> And though I appreciate it, there is no need to flip them around just for me if it's no big deal.

I agree that the naming order you propose is the common one. I also looked through a number of apps to check, so swapping it makes sense. This part of the code was written when the app was new, and then forgotten. Since I only work on Gnome, I've never noticed the discrepancy, and no one has mentioned it before. So I appreciate the feedback.
