### ISSUE TITLE
Build Tool: copy build setting

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1931]
A fancy feature would be the ability to copy an existing build setting (add a copy icon to plus/minus/edit to the builds list).
Applications:
- quickly create a setting for the first 3 chapters of a novel
- quickly create settings for different novels in a multi-novel project

**Comment by vkbo** [comment]
Sure, that's fairly easy as the build settings is wrapped in an object around a single data dictionary linked to a JSON object. Just need to generate a new UUID for the copy, and we're good to go.
