### ISSUE TITLE
Idiots are me.  I made a new 'novel' and it went somewhere else in Linux

### ISSUE THREAD

**Issue by LegolasMirkwood** [vkbo/novelWriter#1933]
I have BOOKS in my home folder in Linux (Mint-but, Linux) dedicated to NovelWriter, I want everything to work and default to there.  

I made a new story after starting NovelWriter and it ended up in my home folder instead of the BOOKS folder, in Linux.  I moved it, no big deal. I suppose that could be improved. I like that you play with this aspect of writing 🏆 💯

**Comment by vkbo** [comment]
It would be helpful if you actually stated what the feature you're ask for is, as I can only guess you want it to remember where your projects are saved. 😄 

If I understand what you are asking, I think #1930 will solve it, so I'm closing this as a duplicate request. Just let me know if I misunderstood, and I will re-open it.

**Comment by vkbo** [comment]
If I understand what you are asking, I think https://github.com/vkbo/novelWriter/issues/1930 will solve it, so I'm closing this as a duplicate request. Just let me know if I misunderstood, and I will re-open it.
