### ISSUE TITLE
"Go to Document" is able to remove focus from document

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#1950]
Reproduce:

1. Open a document in the Editor.
2. If the Document Viewer is open, close it.
3. Focus the Editor.
4. View -> Go to Document.

Contrary to what it says, this will remove the focus from the Editor. If Editor and Document Viewer are open side by side, this toggles between the two panels. But if only one of them is open, "Go to Document" will toggle focus on and off without anything else (to my knowledge?) gaining focus.

I suggest that in this case, the Editor or Document Viewer will simply keep their focus.

**Comment by vkbo** [comment]
It will still toggle to the viewer panel even if it's hidden, so this clearly needs an additional check.

The problem is that invisible items can have focus, as with the other bug you reported. It's not intuitive from a user's point of view, but these are entirely separate flags on a widget,
