### ISSUE TITLE
Add a relationship diagram between roles

### ISSUE THREAD

**Issue by lianglivi** [vkbo/novelWriter#1953]
Can you add a feature to build relationships between characters, represented in the form of charts, to facilitate inspiration for creators, and can also be used on some combined items. I really hope to have this feature, it's really necessary.

example:
![bb625571bc2ae487ea6c6c7eaa09af09](https://github.com/vkbo/novelWriter/assets/169472920/47337896-1fde-455d-b8c2-2f606e9458e9)

**Comment by vkbo** [comment]
This is beyond the scope of novelWriter, so I will close this.
