### ISSUE TITLE
Webdav synchronization

### ISSUE THREAD

**Issue by Leonard0412** [vkbo/novelWriter#1974]
Is it possible to add synchronization via webdav to the software?

I personally have multiple devices, so I want to be able to synchronize my writing progress between multiple devices

**Comment by vkbo** [comment]
Why not use one of the many file synchronisation tools?

**Comment by vkbo** [comment]
If you're requesting some form of collaborative or cloud type feature (not really sure what you mean by "webdav"), then please check #815. There are no plans to add such a feature.
