### ISSUE TITLE
Lock file in the project folder is staying behind when it should be removed.

### ISSUE THREAD

**Issue by arnehemingway** [vkbo/novelWriter#1977]
Hi, 
I use the novelWriter AppImage on multiple machines and they all point to a project on shared storage.  Yesterday I updated one machine to 2.5 and worked on my project.  Today, I opened that same project on another machine using 2.4.3 and received a warning about opening a project created with a newer version of novelWriter.
![image](https://github.com/user-attachments/assets/bf349b48-65bb-4ba6-a895-2a621d5a154d)
I chose "no", exited novelWriter in normal fashion, switched to the new AppImage and was presented with the "another instance is running" warning, showing the hostname and OS of the machine I was on and dated moments earlier.
![image](https://github.com/user-attachments/assets/9c8cac79-6dde-4a55-a0f8-001a4cbe86a3)

I think that, when answering "no" to the first dialog above, the lock file should be removed from the project directory.

I realize that this is a very minor issue.  I bring it to your attention more as a service to you than anything else.

**Comment by vkbo** [comment]
It could be the lockfile is created too early. I'll investigate.

**Comment by vkbo** [comment]
Yes, the lock file is created when the project session object is successfully initiated, but before a number of other checks, including the project format upgrade/downgrade checks. I've rewritten it so that the project is not lucked during initialisation, but after a completed project open process.
