### ISSUE TITLE
Tag Definitions in a Novel Document

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#1990]
As you have noticed, I manage to misunderstand concepts. Here's one example: For a time I created tag definitions in novel documents, only to realize later that there is no way to reference them.

Suggestion: While you are revisiting tags (#1982), disable this possibility. Also, after moving a Project Note to a Novel Folder, you may get non-referenceable `@tag:` definitions again. If there is no use case for this, disable this kind of move as well.

Alternatively, allow referencing tags defined in novel documents. Referencing them as plot tags might be a reasonable idea. You could also invent a new reference type, such as `@document:` or `@novel:`.

**Comment by vkbo** [comment]
I was pretty sure there was already a feature request for referencing novel documents, but I couldn't find any. It's something that can be added for completeness, yes.

As for moving notes around, I could just drop the whole distinction between notes and documents, and just consider all documents in notes folders as "notes" and the ones in novel folders as part of the novel. This current behaviour is a legacy from when there used to be a lot of different types of documents. This is tangential to what you're talking about, but still. The idea of having notes in the novel folder is so you can inject whole documents with plot notes, for instance, in your chapters or acts or whatever. I have never used it myself, but maybe some people do, so I'd prefer to just leave that detail alone.

**Comment by vkbo** [comment]
Added the ability to reference Novel Documents with the `@story` reference keyword. The indexer was already collecting tags in novel document, even if they couldn't be referenced, so this was pretty easy to do.
