### ISSUE TITLE
Directory name confusion

### ISSUE THREAD

**Issue by paulkater** [vkbo/novelWriter#1998]
Today I figured out what was puzzling me for a few days.

I am working on an English manuscript called Breen. The directory for this story is called 'Breen', as you might expect.
A few days ago I decided to try a Dutch translation of the story. I called it Breen-NL. The directory is 'Breen-NL'.

After opening Breen-NL again, on a fresh start of Novelwriter, I didn't see that story in the recently used list. It showed Breen at the top (directory 'Breen'). Clicking that, opened the English version. Closed that file, browsed to the Breen-NL directory and opened the Dutch version.

Just now, I had an idea and renamed the DIRECTORY to NL-Breen, fired up Novelwriter, browsed, opened the Dutch story. Added a word, closed Novelwriter. Started Novelwriter again, and this time Breen-NL (story name in the project, opening from NL-Breen) did show up in the recent list.

Clearly, the recently used list setup gets confused if 2 directories start with the same name and 1 has an addition to it
Breen / Breen-NL

**Comment by vkbo** [comment]
Hmm, not sure I follow. There was a little too much back and forth there.

The project list uses the full path as the key, so projects with different paths should be different entries. The project name does not enter into it. However, the text that is shown in the list *is* the project name, so if they have the same name, it's hard to distinguish without selecting them and comparing the path in the path box.

I'm still not sure if there is a bug here though. On my test machine where I test the new releases, I have 3 version of "Sample Project", and I'm not seeing any mixup.

**Comment by paulkater** [comment]
Let me try to compact this:
When the directories are 
Breen
and 
Breen-NL
the Breen-NL story doesn't show up in the recent list.

When the directories are
Breen
and 
NL-Breen
the NL-story does show up.

I see your edit pop up. Fascinating. If it works for you, then I'll drop this. It does for me too, now. :)
Thank you!

**Comment by vkbo** [comment]
Hmm, strange. It could be something happened and the recent cache file wasn't saved. You can always have a look at the content of `~/.local/share/novelwriter/recentProjects.json` and see if there's a mixup.

**Comment by paulkater** [comment]
Renamed the dir back after a check, opened and closed things a few times, and now the JSON shows the entry for Breen-NL as it should. :+1:
