### ISSUE TITLE
Add Support for Project Language Bengali

### ISSUE THREAD

**Issue by EnigmaticJihad** [vkbo/novelWriter#2000]
I'm a hobbyist writer and I'm liking novelwriter very much. I'd love to have Bengali language support and I bet the Bengali writers' community would love it as well. 

I'd be happy to contribute in translating or anything I can do. I don't have much programming experience, so I'd love to hear some guidelines how I can contribute.

Thanks!!!

**Comment by vkbo** [comment]
As stated in the main readme file, translations are handled on Crowdin. I've added Bengali as an option there.
https://crowdin.com/project/novelwriter

**Comment by vkbo** [comment]
Oh, and here are the translation guidelines: https://github.com/vkbo/novelWriter/blob/main/i18n/README.md
