### ISSUE TITLE
Editor shows Old Italic characters as squares

### ISSUE THREAD

**Issue by lekiet1214** [vkbo/novelWriter#2002]
The editor shows some of Old Italic characters `e.g.𐌀𐌔𐌃𐌂𐌃𐌅` as squares `◻◻◻◻`. I thought it was due to Old Italic not being supported by the font but Georgia does have support for Old Italic; when I open the project file with Notepad, the characters render without any problems.

The editor still renders standard Latin characters in Georgia but does not render Old Italic characters.

My system info:
> Edition	Windows 11 Pro
> Version	23H2
> Installed on	‎05-‎Apr-‎24
> OS build	22631.3880
> Experience	Windows Feature Experience Pack 1000.22700.1020.0
>

**Comment by vkbo** [comment]
Assuming you're on Windows here, since you're referring to Notepad, I suspect this is an issue with character encoding, not font. Are you editing these files also with other Windows applications like Notepad or importing the text from somewhere?

novelWriter works exclusively in UTF-8 format, which is not the standard encoding on Windows.

**Comment by lekiet1214** [comment]
I only edit in NovelWriter, I open the file in Notepad to see if Notepad can render those characters.

The file encoding is UTF-8 as you said.

**Comment by vkbo** [comment]
novelWriter doesn't handle the rendering of text in the editor, that's done by the Qt5 library. If there is a bug here, it's likely with Qt, in which case it needs to be forwarded there. I need to try to reproduce this somehow, so is the text in the original post the actual characters that produces this issue so I can just copy/paste them? On Linux, with the default Debian font, all but one of those characters rendered.

**Comment by vkbo** [comment]
By the way, how do you enter those characters in the first place?

**Comment by lekiet1214** [comment]
> By the way, how do you enter those characters in the first place?

I copied them from [Wikipedia](https://en.wikipedia.org/wiki/Old_Italic_scripts#Latin_alphabet:~:text=%5B17%5D-,%F0%90%8C%80,%F0%90%8C%97,-A), you can try to reproduce with the text in the original post or from the link.

**Comment by vkbo** [comment]
Well, I can definitely not reproduce an issue with this on Linux with the Cantarell font. I'll do some more testing later.

![image](https://github.com/user-attachments/assets/69514944-264d-496e-9cb1-88fd73f38133)

**Comment by HeyMyian** [comment]
The letters display fine here on Windows 10. The Old Italic letter rendering in novelWriter is a bit different from the rendering in Notepad or Notepad++ for me. All editors are set to use Consolas. It does look like it's pulling from two different sources.

novelWriter:
![2024-08-12___21_41_44](https://github.com/user-attachments/assets/f91f5024-f199-4eb3-85e0-d046d0d22f7e)


Notepad and Notepad++ (UTF-8):
![2024-08-12___21_44_37](https://github.com/user-attachments/assets/765993b0-e648-41c9-9f19-77aefeac1a1a)


I'm not sure if this Windows 10 settings window applies to Windows 11, but here I see that Segoe UI Historic is used to render Old Italic on my computer. Is this support maybe missing in your font settings? 
![2024-08-12___21_29_21](https://github.com/user-attachments/assets/00be496b-496c-489a-8f1b-3c6a074ce57a)

**Comment by vkbo** [comment]
novelWriter now supports selecting font style in addition to font family (as of 2.5), so those settings may matter too.

**Comment by HeyMyian** [comment]
If I select the "Runic" writing system in the novelWriter font selection dialog, I'm getting a limited selection of fonts that can natively render Old Italic runes (on my machine Everson Mono and Segoe UI Historic).

novelWriter with Seoge UI Historic - I'd say this is the *correct* correct rendering, identical to Notepad:
![2024-08-12___21_54_12](https://github.com/user-attachments/assets/e7a5906b-630c-4430-8b50-7d311bf3f3b1)

novelWriter with any other font (including Georgia) that does not support "Runic". Wherever this comes from on my system seems to be missing on your system? @lekiet1214 
![2024-08-12___21_38_01](https://github.com/user-attachments/assets/2383a276-6dcc-405a-8494-4aa247955117)


![2024-08-12___21_52_11](https://github.com/user-attachments/assets/64f9e447-68fb-434f-ac99-13201989c9cd)

**Comment by lekiet1214** [comment]
I changed the font of my novelWriter to Segoe UI Historic, and now it renders fine. This font was already on my computer.

I believe Notepad is simply trying to render those letters, regardless of the font selected.

**Comment by vkbo** [comment]
> I believe Notepad is simply trying to render those letters, regardless of the font selected.

Yes, that could very well be. I've seen this happen before.
