### ISSUE TITLE
Allow simple arithmetic in chapter number title variable

### ISSUE THREAD

**Issue by cakenggt** [vkbo/novelWriter#2029]
The feature would allow simple arithmetic (off by one) to be added to rendering the chapter headings using the chapter number variable. This would allow users to add prologue chapters at the beginning of their book, and then have the second chapter be auto-titled on build as Chapter 1.

It would look, perhaps, like this:
![image](https://github.com/user-attachments/assets/8441dde3-6157-4351-8392-91fafb3aa4e2)

**Comment by vkbo** [comment]
There is already an "Unnumbered Chapter" feature for that.

https://novelwriter.io/docs/project_structure.html#unnumbered-chapter-headings

**Comment by vkbo** [comment]
I closed it, as the use case you're requesting is already covered by the mentioned feature.

I'm guessing adding to the number is another possibility, but I can't think of a use case for that.

**Comment by cakenggt** [comment]
Woops, you are very right. Sorry about that.
