### ISSUE TITLE
Always make word counts etc. available in odt output as variables

### ISSUE THREAD

**Issue by awqk** [vkbo/novelWriter#2033]
When odt output is created, it would be nice to have the metadata available as variables for use with templates and LibreOffice Writer's 'Insert Field' command: word counts (text/headings), paragraph count, character count, build date, build settings name, author, title, etc.

This feature should be always enabled (without a configuration option in the build settings).

Inspired by #2023, #2024

**Comment by vkbo** [comment]
Does the Open Document format support this?

**Comment by awqk** [comment]
> Does the Open Document format support this?

Uh..., yes, 'User Field' seems to be the right field type for this. Supports string and float, apparently.
Here's a snippet from an otherwise empty `.fodt`:
```
<text:user-field-decls>
 <text:user-field-decl office:value-type="string" office:string-value="qwerty" text:name="TestUserField"/>
</text:user-field-decls>
```
The definition is saved even if the field is not used in the document.

**Comment by peter88213** [comment]
> word counts (text/headings), paragraph count, character count,

As far as I know, most of this is generated dynamically by LibreOffice. See this **Insert >Field** dialog:

![grafik](https://github.com/user-attachments/assets/8ba78b1a-13ac-4092-980c-8076d2c56d8e)
 



> build date, build settings name, author, title, etc.

Actually, the right place for this is the **meta.xml** file in the *odt* zip archive. Here you can create the fields in the `<office:meta>` area with the ODF standard tags.

**Comment by awqk** [comment]
> > word counts (text/headings), paragraph count, character count,
> 
> As far as I know, most of this is generated dynamically by LibreOffice. See this **Insert >Field** dialog: [...]

Isn't this the document word count, as opposed to the manuscript word count? Maybe I didn't specify the use case well enough, but modifying a generated document by adding/changing a title page shouldn't change the manuscript word count. If you intend to split a fine hair, you could also be interested in the word count without headings etc.

> > build date, build settings name, author, title, etc.
> 
> Actually, the right place for this is the **meta.xml** file in the _odt_ zip archive.

Yes!

**Comment by peter88213** [comment]
> Isn't this the document word count, as opposed to the manuscript word count?

As we know from NaNoWriMo, almost every word processor seems to calculate a different word count.
For LibreOffice tere is at least a definition, see: https://help.libreoffice.org/latest/en-US/text/swriter/guide/words_count.html
If you integrate your exported manuscript in a master document as I suggested in another topic here, you can get separated word counts for the frontmatter/backmatter and the actual manuscript. 
Anyway, because of the inaccuracies mentioned above, I think the word count is more about the dimension than the exact value, isn't it?

**Comment by awqk** [comment]
> [...] I think the word count is more about the dimension than the exact value, isn't it?

Agreed!

> If you integrate your exported manuscript in a master document as I suggested on another topic here, you can get separated word counts for the frontmatter/backmatter and the actual manuscript.

Agreed!

> Incidentally, a static word count property would soon be outdated if the odt document were still being worked on. [...]

The supposed workflow here is editing the manuscript with novelWriter only. Changes to the odt after the build should be as few as absolutely necessary.

**Comment by awqk** [comment]
I'll try to summarize this enhancement request:

1. In the `<office:document>` xml element, add and populate an `<office:meta>` element. This is what it would look like in an `.fodt` file:

```
<office:meta>
 <meta:creation-date>2024-09-30T11:14:40.668845707</meta:creation-date>
 <meta:initial-creator>Firstname Lastname</meta:initial-creator>
 <meta:generator>LibreOffice/7.3.7.2$Linux_X86_64 LibreOffice_project/30$Build-2</meta:generator>
 <dc:title>Title</dc:title>
</office:meta>
```
2. In `<office:text>`, add and populate a `<text:user-field-decls>` element, like this:
```
<text:user-field-decls>
 <text:user-field-decl office:value-type="float" office:value="1234" text:name="ManuscriptWords"/>
 <text:user-field-decl office:value-type="float" office:value="2" text:name="ManuscriptWordsInHeadings"/>
 <text:user-field-decl office:value-type="float" office:value="1232" text:name="ManuscriptWordsInText"/>
 ...
</text:user-field-decls>
```
The second part adds few benefits if novelWriter's `.odt` output is part of a master document, as outlined in #1975.

**Comment by vkbo** [comment]
What's the point of the meta values? These are already populated by novelWriter.

**Comment by vkbo** [comment]
Anyway, the fields were trivial to add. I just made all fields recorded available, and prefixed them with "Manuscript":

![image](https://github.com/user-attachments/assets/2fdc3131-7dac-4579-94e3-91822715c203)

It only took a few lines of code.

```python
        if self._counts:
            xFields = ET.Element(_mkTag("text", "user-field-decls"))
            for key, value in self._counts.items():
                ET.SubElement(xFields, _mkTag("text", "user-field-decl"), attrib={
                    _mkTag("office", "value-type"): "float",
                    _mkTag("office", "value"): str(value),
                    _mkTag("text", "name"): f"Manuscript{key[:1].upper()}{key[1:]}",
                })
            self._xText.insert(0, xFields)
```
