### ISSUE TITLE
Add a PDF output option

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#2046]
Since the Manuscript Build tool now generates a good quality QTextDocument for the preview, rather than a limited HTML4 document, the saveDocument function in it can potentially be used to write a PDF document by using the built-in painter.

This is a simple solution to PDF save, and hopefully enough.

**Comment by HeyMyian** [comment]
The text renders really badly unfortunately. It's just standard Times New Roman, which has no business looking like this. Is this a limitation of the simpleness of this solution?

![2024-11-13___08_43_15](https://github.com/user-attachments/assets/387961ee-8658-4052-b632-8c52a1325b44)

**Comment by vkbo** [comment]
There is nothing I can do about the PDF output. It is generated entirely by Qt based on the same content as shown in the Manuscript preview window. It is basically a restoration of the print to PDF feature that was available in the old Build tool.

https://github.com/vkbo/novelWriter/blob/8c952953e35555010b37ab46c8ded85e3bcc90ea/novelwriter/formats/toqdoc.py#L242-L255

**Comment by HeyMyian** [comment]
I've tested some more. 93,50 % letter width in my case equals: (100 % page width - left margin - right margin) as set in the Manuscript Build Settings. You can check that with all margins set to 0 in the MBS, the letters will come out at the correct 100% width. If the margins are set to something unreasonable like 10cm, the letters will be unreadably squished. That doesn't seem right at all?

As for the letter spacing, is the styling in the Preview done with CSS? If it accepts `letter-spacing`, is it maybe possible to specifically set it to `0` and then see what the PDF does with that?
