### ISSUE TITLE
Support narrator breaks in PT-BR in dialogue highlighting

### ISSUE THREAD

**Issue by nyex** [vkbo/novelWriter#2066]
Right now, I can highlight dialogue by indicating that lines beginning with an _em dash_ are dialogue, but there is no way to alternate the highlighting when there is a narrator break in it.

As mentioned in https://github.com/vkbo/novelWriter/issues/1773#issuecomment-2432138905:

> in Brazilian Portuguese we usually do dialogue like this:
>
> — Tudo bem? — _ele pergunta._ — Você falou com ele?
> — Ainda não — _ela responde._
> — Está ficando tarde.

Italics are narrator breaks. 

Also as mentioned, it would be enough if there was a way to simply alternate the highlighting of dialogue on and off for each _em dash_ (the _em dash_ is the "correct" way of doing it, but I don't know if other people use the _en dash_ when writing).

**Comment by vkbo** [comment]
Ah, thanks for creating a new issue! I will close the duplicate #2065 😄

**Comment by vkbo** [comment]
Ok. this code seems to work, and is reasonably fast:

```python
        if self._dialogLine and text.startswith(self._dialogLine):
            if self._narratorBreak:
                tPos = 0
                for tNum, tBit in enumerate(text[1:].split(self._narratorBreak), 1):
                    tLen = len(tBit) + 1
                    if tNum%2:
                        self.setFormat(tPos, tLen, self._hStyles["dialog"])
                    tPos += tLen
            else:
                self.setFormat(0, len(text), self._hStyles["dialog"])
```

It is run in the syntax highlighter before formatting highlighting is added. It changes the default colour of each section according to the split, and applies dialogue colour to the odd numbered entries, and keeps normal text colour for even numbered entries.

I tested on a couple of lines. I set the dialogue symbol to `=` just to make sure it could handle the distinction.

![image](https://github.com/user-attachments/assets/53971919-aed1-4fe3-891c-4eb79dbb830d)

**Comment by vkbo** [comment]
It is also possible to apply a dedicated style for the narrator bits. I've tested that here:

![image](https://github.com/user-attachments/assets/afc5d6a4-3d15-4ab9-b578-40f4d92281a2)

This will need more settings in Preferences though. Is it always italic?

**Comment by nyex** [comment]
> This will need more settings in Preferences though. Is it always italic?

Oh the italics was just to mark it for you, we don't use italics like that, no. Sorry i wasn't clear.

**Comment by vkbo** [comment]
> Oh the italics was just to mark it for you, we don't use italics like that, no. Sorry i wasn't clear.

Ah, I see. Then forget that. Although it did make sense to me as a way to make i clearer. 😄
