### ISSUE TITLE
Style section of HTML output outside HEAD

### ISSUE THREAD

**Issue by Wysardry** [vkbo/novelWriter#2080]
I just exported the example document in HTML format using version 2.5.2 of novelWriter and found that the (CSS) STYLE section was placed between the HEAD and BODY elements.

It is usually placed inside the HEAD section.

**Comment by vkbo** [comment]
You're right, I never noticed that. Thanks!

![image](https://github.com/user-attachments/assets/b70c287e-0426-454e-994c-2678d224a26f)
