### ISSUE TITLE
Ability to move items in root

### ISSUE THREAD

**Issue by locrianz** [vkbo/novelWriter#2091]
I'd like to be able to move new items that I've created in the root. ~~Right now when I create a new Locations folder, Timeline folder, etc. they wind up down at the bottom, underneath the Archive and Trash, which is aesthetically displeasing to me.~~ OKAY no it turns out to be based on where my cursor is. But it would still be nice to be able to reorder them.

**Comment by vkbo** [comment]
You can reorder them as you wish using the arrows at the top. The only thing you can't do is drag and drop them.
