### ISSUE TITLE
AI-content-writer-feature

### ISSUE THREAD

**Issue by iamagh** [vkbo/novelWriter#2097]
Hello, community.
I am a fan of a novel, skilled in AI programming, who wants to provide Veronica with a new idea.
Willing to provide free AI API, which is not only for small amounts of text but a huge content from one shot.
I have succeeded in AI content writing, and willing to collaborate with your team.

Thank you.
Restless Coder

**Comment by vkbo** [comment]
Thanks for your interest, but AI features, beyond maybe straightforward text analysis, will *never* be added to novelWriter.

**Comment by iamagh** [comment]
Thank you for getting back to me.
it would help if you considered that Someday, novels written by my AI will
compete with human products.

**Comment by vkbo** [comment]
I'm sure people will keep trying to generate low quality content with AI. But this project is for writers, and actual writers write their own material. AI relies on stolen work to generate a cheap imitation of the real thing. It will never be added.
