### ISSUE TITLE
Build Settings: layout for Text Margins setting

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#2098]
2.6 Beta 1

Great new stuff 😃 

I've got a suggestion for the interface in the build settings. The view in the screenshot could maybe best be understood as a table in which the column headers for the last two colums are "top" and "bottom". I guess "T" and "B" are abbreviated because of space issues; turning them into headers might alleviate that. Maybe there are languages where this can't be abbreviated.

Then there would also be space for the unit, which is currently missing.

![2024-11-13___07_56_29](https://github.com/user-attachments/assets/fd5029e4-abf3-46c5-b1bd-5b91bb455bca)

(I have no idea how to title this issue)

**Comment by vkbo** [comment]
Such titles are not possible with the current layout implementation as there is no way to align them with the boxes below. Although they look like they're on a grid, they are not. Each set of controls are aligned completely independently.

I've considered replacing the "T:" and "B:" with icons instead, but need to design them.

**Comment by vkbo** [comment]
In #2102 I'm refactoring how text margins are applied so that they are always in em units. Only DocX used em units, as it specifies its margins as 20 times the font point size. It's a weird unit, but it avoids decimal numbers.

ODT uses physical units, so they have to be converted from DPI, and to whatever unit is preferred. novelWriter uses centimetres internally. For HTML the unit is just em, so that's easy.

**Comment by vkbo** [comment]
Is this better?
![image](https://github.com/user-attachments/assets/eac31803-a4f8-4e66-8ff9-2c8e45004691)

**Comment by HeyMyian** [comment]
I like it better than `T:` and `B:`. The icons look nice.

**Comment by vkbo** [comment]
Here's the full set, with a little tweaking.

![image](https://github.com/user-attachments/assets/8e099bc7-fcff-4f5f-b7a2-8d7ffdb0bf8e)

**Comment by vkbo** [comment]
Ok, done tweaking them. Here's the latest.

![image](https://github.com/user-attachments/assets/72757348-0d48-4e31-944f-facdd3e100f2)

![image](https://github.com/user-attachments/assets/f7875ad1-1a79-4ae3-a5d0-61c2c4a5026a)
