### ISSUE TITLE
Build Manuscript: docx applies extra line height to headings

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#2099]
2.6 Beta 1

The `docx` has additional line height in Chapter headings (and perhaps other headings too). There is a base line height of 1.75 that gets multiplied with the line height as set in the Manuscript Build Settings. I've verified this with a line height of 1.5 in the MBS results in a chapter title line height of 2.63 (rounded).

The `odt` is fine in LibreOffice and MS Word, it sets the line height of headings according to the Manuscript Build Settings.

Is this even fixable or is it just how MS Word really thinks chapter titles should be formatted? I'm on ancient version Office 2007 if that matters.

Line height of 1 results in a line height of 1.75:
![2024-11-13___08_20_25](https://github.com/user-attachments/assets/03378937-aa7d-4242-8813-2eae8bbcf27f)

Compared to line height of 1 in LibreOffice, `odt` and `docx`. Also `odt` in MS Word. This is the correct formatting.
![2024-11-13___08_21_12](https://github.com/user-attachments/assets/5993fcc8-7495-4ae9-b5a1-bd93577ebf1d)

**Comment by vkbo** [comment]
I only have access to the online version of Word, and it did look fine there when I checked, but I'll look into it.

The DocX formater should define complete styles for headings, but maybe line height needs to be set explicitly.

**Comment by vkbo** [comment]
I created the DocX format based on the DocX file that Libre Office generated from the ODT manuscript. Interestingly, Libre Office scaled the line height to the font size of the headings, something Office 365 does not. Hence the larger margins in Office. There is a flag called `w:lineRule = auto` that when added, makes it possible to set line height based on normal font size. This produces the same result in both apps.
