### ISSUE TITLE
Output format dialog defaults to "Close" button

### ISSUE THREAD

**Issue by HeyMyian** [vkbo/novelWriter#2101]
While the initial focus is on "Build", changing any setting in this dialog switches the focus from the "Build" button to the "Close" button. This goes against the intuitive use of hitting <kbd>Enter</kbd> to build the thing after changing some settings.

![2024-11-13___18_37_40](https://github.com/user-attachments/assets/3a6fa7e6-ad4f-43aa-aac2-ecaa8b9df676)

**Comment by vkbo** [comment]
Yes, this is some annoying Qt default nonsense. The Close button is the only standard button on the dialog. I'll try to disable it.
