### ISSUE TITLE
Dialogue highlighting works incorrectly with chinese grammer

### ISSUE THREAD

**Issue by ZEROIC** [vkbo/novelWriter#2131]
I write novels in chinese and this tool is suitable in my own working flow.However I find dialogue highlighting works incorrectly with chinese grammer.
The correct grammer of chinese dialogue is like these:
![QQ20241206-040452](https://github.com/user-attachments/assets/2cbb42a7-4ec7-46db-8fa7-a0c245a24e5b)
Three typical dialogue sences above,only the first one is highlighted properly.Difference from english maybe the lack of a separator.Don't worry,almost all related tools or plugins I met go wrong with this,aha.

My personal resolution is to remove the second \B in dialogStyle regex expression,then it will works as excepted.
There are other things I've done for this locally,such as add a switch like chinese highlighting mode or something else to control the feature.
I haven't known how this would affect in other unfamilar languages yet.You can decide how to implement it on you own maybe.

**Comment by vkbo** [comment]
The dialogue highlighting has been rewritten for 2.6, so perhaps you can test with 2.6 Beta 1?

There are more settings now, so maybe one of the others work. If there is no word boundary, the settings for quote symbols will not work, as you point out, as it does rely on that word boundary to know where to end.

I can certainly add a Chinese mode switch. I just need to know exactly what the rules are.

**Comment by vkbo** [comment]
Also, if you could provide some example text that I can use for testing, that would make it a lot easier. A screenshot, while helpful for illustration, isn't something I can reproduce in the editor.

**Comment by ZEROIC** [comment]
Yeah,I pull codes of the software,just running 2.6b1 right now.I've seen changes about this function.
There should be no separator between the first dialogue and narration in chinese.So I can't customize the separator to make it works. 
![QQ20241206-131154](https://github.com/user-attachments/assets/43c9c3ab-0962-4ea9-b59b-3ababe7bd7a8)

I forgot to provide expamples in a hurry.You can test this with such examples:
他说：『我能吞下玻璃而不伤身体。』
『我能吞下玻璃而不伤身体』他说。
『我能吞下玻璃而不伤身体』他说，『我能吞下玻璃而不伤身体』

**Comment by vkbo** [comment]
I think this can be achieved with a setting that doesn't require the word boundary then.

Technically, the word boundary is anyway only required if the open and close symbols are identical, or the closing symbol doubles as an apostrophe. I tried a quick change to drop the `\\B` if the open and close symbols are different and they are not ambiguous, and it seems to work, but I need to do some more testing to make sure.

```python
    @property
    def dialogStyle(self) -> re.Pattern | None:
        """Dialogue detection rule based on user settings."""
        ambiguous = (nwUnicode.U_APOS, nwUnicode.U_RSQUO)
        if CONFIG.dialogStyle > 0:
            end = "|$" if CONFIG.allowOpenDial else ""
            rx = []
            if CONFIG.dialogStyle in (1, 3):
                qO = CONFIG.fmtSQuoteOpen.strip()[:1]
                qC = CONFIG.fmtSQuoteClose.strip()[:1]
                qB = r"\B" if (qO == qC or qC in ambiguous) else ""
                rx.append(f"(?:{qO}.*?(?:{qC}{qB}{end}))")
                # rx.append(f"(?:\\B{qO}.*?(?:{qC}\\B{end}))")
            if CONFIG.dialogStyle in (2, 3):
                qO = CONFIG.fmtDQuoteOpen.strip()[:1]
                qC = CONFIG.fmtDQuoteClose.strip()[:1]
                qB = r"\B" if (qO == qC or qC in ambiguous) else ""
                rx.append(f"(?:{qO}.*?(?:{qC}{qB}{end}))")
                # rx.append(f"(?:\\B{qO}.*?(?:{qC}\\B{end}))")
            return re.compile("|".join(rx), re.UNICODE)
        return None
```

**Comment by ZEROIC** [comment]
Good idea,chinese quotes are not same.I fixed this with similar way but more complicate.Because I don't know if someone likes writing english novels with chinese quotes.(Just like order fried rice in a bar,oops!)
Never mind,now I realize it's out of grammer!

**Comment by vkbo** [comment]
Basically, the boundary condition is only there to catch cases like these:

![image](https://github.com/user-attachments/assets/d03851e6-0985-486a-9d8d-982dd1d95bf9)

![image](https://github.com/user-attachments/assets/f7805290-2da4-4f02-a7cf-feb83aa8cadb)

As you can see, without it, it doesn't know where the quote ends.

But I think I can turn off this in most cases, so I'll give that a try first.

**Comment by vkbo** [comment]
Oh, and the new implementations seems correct for your example text too:

![image](https://github.com/user-attachments/assets/3897daf7-5ce1-4556-bc85-5ffb340dfa92)

**Comment by ZEROIC** [comment]
Yep，it looks right!
