### ISSUE TITLE
Justify Text feature does not work in Build preview.

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#228]
In novelWriter v0.6:

If the user has selected Menu&rarr;Tools&rarr;Preferences&rarr;Layout&rarr;Justify the text margins in editor and viewer&rarr;&cross; and then proceeds to Build the novel, the Justify text selection only left justifies regardless of its setting.

If the user has selected Menu&rarr;Tools&rarr;Preferences&rarr;Layout&rarr;Justify the text margins in editor and viewer&rarr;&check; and then proceeds to Build the novel, the Justify text selection works properly.

**Comment by vkbo** [comment]
The editor and viewer text preferences do not transfer to the build preview. The build novel project tool has its own formatting preferences. Since the editor is actually plain text, no formatting is applied to the text itself by these settings. The build tool, however, does apply formatting.

**Comment by vkbo** [comment]
Wait, now I get it. It was a bit difficult to parse the meaning here. That is indeed a bug. The export should work just fine, but the preview window actually does use the settings from Preferences. I copy/pasted some of the code from the regular viewer panel, and forgot to replace the settings value.

Will fix!

**Comment by vkbo** [comment]
Fixed in PR #231

**Comment by vkbo** [comment]
You are now posting to a ticket that was closed 5 years ago. If you have a new issue, create a new ticket.
