### ISSUE TITLE
Line break in heading doesn't want percent signs

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#229]
The [documentation](https://novelwriter.readthedocs.io/en/stable/export.html#header-formatting) notes that you can put `%\\%` in  a novel title to break the line. That's a typo.

I find that simply putting `\\` does the trick, and adding `%` around it forces `%` into the output.

So `Scene %chnum%.%scnum% \\ %title%` produces what we want:

**Comment by vkbo** [comment]
Yes, that's a typo from copy/pasting text when updating the documentation. Will fix.

**Comment by vkbo** [comment]
Fixed in PR #231
