### ISSUE TITLE
Characters, Words and Paragraphs count not displayed when a folder is selected

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#235]
This is an enhancement request. 

As the user clicks on documents in the Tree View pane, the number of Characters, Words and Paragraphs are indicated below it. But click on a folder and no counts appear. Here is an opportunity to display the total number of Characters, Words, Paragraphs and documents contained in that folder.

![Example](https://user-images.githubusercontent.com/8484427/82849789-65f0cf00-9eae-11ea-8f21-cec7235daa2d.png)

**Comment by vkbo** [comment]
That is correct behaviour. The panel only shows the meta data for the selected item, and these items don't have counters. Only files do. The tree view tries to keep track by propagating the diff of words to the folders above any given file, but these are calculated on the fly by the wrapper class for the tree widget.

**Comment by vkbo** [comment]
I do notice that it states the code for "Layout None" to be "Xo". This is technically correct, as it is the internal label, but the tree view doesn't display it, and neither should this panel.

I also see that the status icon is misaligned, and that is probably because you're on  0.6. I changed this in 0.6.1, but will double check.

**Comment by johnblommers** [comment]
OK I see your point. The tree view does show the total words underneath a folder. Showing the same information in two places is not a good idea..

**Comment by vkbo** [comment]
I could in principle extract the word count from the tree and display it in the details panel, but there is no such accumulated values for character and paragraph counts. The sums are also not guaranteed to be correct during a session if files are deleted and moved a lot. They are recalculated when a project is opened though, and when the index is rebuilt.
