### ISSUE TITLE
Blank PDF generates if no preview is displayed

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#237]
When the user opens a project, goes to build it (F5), and clicks Saves as&rarr;PDF, in that order, the PDF is blank. You get an empty page.

When the user does a Generate Preview before saving as PDF, the PDF is correct.

**Comment by vkbo** [comment]
This is correct behaviour. The export is only made from the displayed text. I'm about to rename the button to something less misleading.

**Comment by vkbo** [comment]
The button name is a remnant from the first intention – to generate a preview as step one. I just never got around to naming it something more appropriate. I tagged this onto PR #238 which also adds a font family and size selector to the build tool.

**Comment by vkbo** [comment]
PR #238 merged to master, closing.

Thanks for the feedback!
