### ISSUE TITLE
Project backup hangs writing ever-increasing backup file.

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#240]
```bash
novelwriter --version
novelWriter Pre-Release Version 0.6.1 [2020-05-25]
```
I can't replicate this issue with the sample novel. It only manifests using my own project. What happens:

- Launch novelWriter
- Open my project
- Make a  tiny change
- Click the X to close novelWriter
- Click Yes to save the project
- Click Yes to backup the project
- novelWriter does not quit, it has to be force quit, and by that time it's written at least half a gigabyte to the backup file.

Left on its own, novelWriter will keep on writing until $HOME is full. Which is how the issue introduced itself. No harm done, though, because it revealed a clue to share here.

Temporarily I have checked the option to Disable backup on close in the project settings.

I did launch novelWriter on the command line (`novelwriter --verbose`) and no  obvious diagnostic messages appear.

Linux thinks the backup file is a zip file according to the `file` command but it's corrupt and won't open. I've looked at the backup zip file with `hexedit` but the file is filled with random binary data. 

At this juncture I am all ears on suggestions to troubleshoot further. I don't want to share project file though.

PS: I always install novelWriter by downloading the zip file from the Master branch, unzipping it, renaming the folder to `novelWriter`, and moving it to my `~/Applications` folder. In `~/Applications`  I have a symbolic link called `novelwriter` that points to the `novelWriter.py` script. And `~/Applications` is in my `$PATH`.

**Comment by vkbo** [comment]
Hmm, this is strange. The zip file is made entirely by the `make_archive` command fromthe `shutil` package. All I send it is the project path and file name.

I suspect the backup is being written to the same folder that the project is saved in. That may cause an infinite loop of the zip file zipping itself. Can you check if that is the case? The save path should be in your Preferences.

I will check the code to see if there are any bugs that could cause this. I've been using the backup feature myself for months, and never seen this, so I'm guessing you've stumbled onto a corner case here.

**Comment by vkbo** [comment]
Well, that was fast. I just tested setting the backup path to the same folder as the project, and voila, infinite zip loop. Can you confirm?

**Comment by vkbo** [comment]
Can you download this branch and see if you now get an error message?

https://github.com/vkbo/novelWriter/tree/backup_bug

**Comment by johnblommers** [comment]
The backup_bug tree does indeed alert me because my backup file is inside the folder.

In retrospect it's not very smart to put a backup of one's work right in the same work folder! But that's what I was doing.

Problem solved!

**Comment by vkbo** [comment]
Thanks! Good to confirm this was indeed the issue. I will merge the fix then.

I just need to clean up a few things. I try to ensure path inputs from the user is always passed through `os.path.abspath` to ensure no relative paths are used in novelWriter. The check I added here depends on this to find common paths.
