### ISSUE TITLE
Locating the Project Path is Somewhat Convoluted

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#242]
So I had totally forgotten where my manuscript was located. I cast about the novelWriter menus and finally found the information in an unlikely place; in the Open Project menu, almost invisible in the Path text box because it's in a very light grey font.

The first place I looked in was Menu&rarr;Project&rarr;Project Settings and that is where I'd like to suggest this information be presented.

I realize that the **relative** path of a document is displayed at the top of the left document pane. And that is appropriate and good, but it's the folder containing the project that is important to locate.

Perhaps a button/menu labeled "Reveal This Project in the File system" might work.

**Comment by vkbo** [comment]
It makes perfect sense to show the path there when you open projects, but you're right that the information should be retrievable elsewhere too.

I do plan to add a meta data page to the Project Settings dialog, similar to what Libre Office has. I'll get on it for next patch, which will include all the issues you've found the last few days.

**Comment by vkbo** [comment]
The project path is now on a new "Details" tab in "Project Settings". I also added a few other meta values that the project class tracks.

By the way, the document title bar doesn't display the relative path, it actually displays the project path, which is a virtual hierarchy not mirrored on disk.

**Comment by johnblommers** [comment]
Outstanding! You are on fire with all of the  recent fixes, changes and updates you've made to novelWriter. I've been downloading frequently from the Master branch and every build has been remarkably stable and measurably better.

**Comment by vkbo** [comment]
I'm polishing all the GUI tools to try and get to feature completeness :)

As soon as that's done, I will start making release candidates for 1.0, and iron out all the little issues.

Then I have two more major additions for post 1.0 minor releases.
