### ISSUE TITLE
Option for user-defined CSS in HTML build is begging

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#279]
novelWriter now has an option to disable the inclusion of a `<style>...</style>` block.

A natural next step is to include an option to include the contents of a user-defined CSS file in the HTML. There are a lot of really nice CSS files scattered around the Interwebs that might be easily leveraged with this option.

What's not clear to me is if the resulting look of the HTML preview will reflect on the formatting of the PDF, DOCX et. al. products that novelWriter emits.

Thoughts?

**Comment by vkbo** [comment]
Hmm, I was sure I'd responded to this. Maybe I got distracted and lost the comment without submitting it.

Anyway, Qt's support for CSS isn't anywhere near complete or up to modern standards (CSS3), so it would involve replacing the preview window with a full browser. This comes with a host of other issues as they are much more involved elements to add to novelWriter.

In any case, it isn't the purpose of novelWriter to produce print-ready material, so if you really want something custom, you may as well add a stylesheet reference to the HTML output. Stylesheets are  usually external files anyway, and embedding them aren't really the correct way of doing it beyond a few lines like novelWriter currently does.

The purpose of the styles free output is to avoid in-element style tags, which makes it more difficult to customise the look in for instance EPUB maker tools and other tools that take HMTL as input.

**Comment by johnblommers** [comment]
You're right that simply editing the exported HTML's *style* tags portion and replacing it with a reference to a CSS file is the way to go. From there the writer can use any number of file converters such as Prince, Pandoc or `wkhmltopdf` to create other file formats.

And I appreciate your position that novelWriter is not meant to create publication-ready product. Tools exist already for that purpose.

**Comment by vkbo** [comment]
I added the JSON export too as a way to encourage post-processing with for instance Python scripts. It preserves the file structure of the project (not folders) and also preserves the layout as the text tokenizer saw it when processing the content. It can hold both the raw markdown and the generated HTML5, so should be quite a good starting point for all sorts of fun scripting.

**Comment by vkbo** [comment]
I think I will close this. It's beyond the scope of novelWriter, and would in addition involve dealing with the Web Engine, which I have tried to avoid so far as it introduces a lot of issues.

**Comment by johnblommers** [comment]
Make it so ;-)
