### ISSUE TITLE
Two cosmetic issues

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#295]
So I just downloaded the Master branch. If you examine the screenshot below you'll see where I've indicated the areas of concern:

1. The X is too close to the scroll bar
2. The path text has a few pixels shaved off the bottom

![Screenshot at 2020-06-07 16-38-08](https://user-images.githubusercontent.com/8484427/83982758-077c1580-a8de-11ea-97dd-2956a43e8ccb.png)

**Comment by vkbo** [comment]
Huh. Looks fine on Debian. Will check on Ubuntu.
