### ISSUE TITLE
Typo in documentation for Synopsis syntax

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#297]
The [Synopsis Feature](https://novelwriter.readthedocs.io/en/stable/interface.html?highlight=synopsis#synopsis-feature)  documentation reads

> ...add the word “Synopsis:” as the first word of the comment. The “;” is required...

The first part is correct, the second part should read:

> The ":" is required.

Oh for want of a pixel ...

**Comment by vkbo** [comment]
Ah, that damned English keyboard layout putting ":" and ";" on the same key! On our Scandinavian layout "." and ":" share a key. Avoids this issue!

I'll fix it. Thanks!
