### ISSUE TITLE
Session Log Buggy and Design Outdated

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#313]
The tool that displays the content of the session log (a logfile in the project meta folder that tracks when you opened and closed the project, and how many words you added or removed) is a bit buggy. The filtered time summing doesn't actually consider the filters properly, and if you have a long log, it takes a while to open it.

The tool should not load the log while building the GUI. This should be done afterwards, and possibly with a progress bar. In addition, it would be nice if the data could also be presented as a histogram on a time axis.

**Comment by johnblommers** [comment]
The suggestion:

>  In addition, it would be nice if the data could also be presented as a histogram on a time axis.

was the first thing I  thought as I started to read your comment. Hopefully it's not too much work to develop the code but it would be so cool to have this feature.

There is of course plenty of opportunity to invite scope creep. For example, NaNoWriMo participants are interested in plotting word count on a day-by-day histogram.

Let me stop there ;-)

**Comment by vkbo** [comment]
Well, the log file has all that data already, and in a fixed column width file, so importing should be fairly easy.

Anyway, Qt has some nice chart widgets, so it shouldn't be too hard to optionally plot it in a histogram.

**Comment by vkbo** [comment]
I made a simpler histogram in that I just added a progress-bar like column to the table.
I'll add an export to CSV and JSON before I'm done with the PR, but otherwise it seems to be working.

![image](https://user-images.githubusercontent.com/1619840/85631136-41d30a00-b675-11ea-8b5d-374e7c70380b.png)

**Comment by vkbo** [comment]
Merged into `dev` branch. This issue will be closed automatically when it goes to `master`.
