### ISSUE TITLE
Auto-Replace tab column width settings are not saved

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#322]
So I pulled down the dev branch to check those new features novelWriter is getting.

I've been starting to use the Auto-Replace feature in the Project Settings. I move the column divider because a Keyword is `<Protagonist1`  that needs more space to display. But after clicking <kbd>OK</kbd> and opening again this dialog the column width is back to default.

It's useful for novelWriter to remember this setting.

**Comment by vkbo** [comment]
Thanks for reminding me. I've mostly forgotten about those columns. I never use the feature myself other than for testing, so I haven't noticed this in a while. It was made on @Number042's request.

I'll fix it right away. I'm cleaning up a bunch of small issues right now.

**Comment by vkbo** [comment]
Ok, fixed in `dev`. This issue will automatically be closed when `dev` is merged to `master`.
