### ISSUE TITLE
The Project Tree does not follow along as you search and replace documents

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#332]
The new search and replace feature is wonderful. I used to replace the name of my main character to `<Protagonist1>` throughout my project. It kept right on going past the end of my manuscript and into the Trash folder. There I had a sense of deja vu until I realized that I was editing the trash. Oy.

That's when I realized that the project tree was not following along as I went from document to document doing search and replace. My manuscript is about ten chapters with about ten scenes each for about 110 documents. There are a few dozen documents in the Trash.

Enhancement request: Perhaps novelWriter could scroll the project tree so the actively edited document is at the top.

**Comment by vkbo** [comment]
You're right, it doesn't. It's actually one of the last changes I made before merging 0.9, so it's deliberate. At least in the sense that I disabled the Qt `scrollTo` call when a document is opened through user interaction.

The reason I did this was that the Qt feature not only ensures that the item is scrolled into view, but it also tries to centre it in the tree view. That meant that if you were looking through multiple document by double-clicking them in the tree, you ended up chasing a moving target. That was quite annoying.

On the other hand, the file continuation isn't really a direct user interaction as the open call is indirect, so I can rework the decision logic here a bit to limit the definition of user interaction to a direct open document call on the tree.

It will scroll to the centre though (if possible), not the top, but it will at least be in view. It will also ensure the node is expanded.
