### ISSUE TITLE
Markdown Emphasis

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#353]
I still manage to break the markdown formatting for emphasis and strong. For instance, this sentence from the sample text:

> `Depending on *the **syntax** highlighter*, these can be in different colours.`
> 
> Depending on *the **syntax** highlighter*, these can be in different colours.

Does not work in the current version, but I've managed to fix it by modifying the regex. However, there are multiple ways still to break it.

The challenge is to write a regex for bold and italic independently that never overlap on the `*`. If they do overlap, it will result in a malformed HTML conversion. The issue is mainly caused by the ambiguity of a triple `***`, like:

> `Depending on ***the syntax** highlighter*, these can be in different colours.`
> 
> Depending on ***the syntax** highlighter*, these can be in different colours.

It is possible to instead write an iterator that just loops through the text and switches on and off formatting flags. Using a large number of regexes is in any case rather slow, so this may be faster in the end.

Instead reverting to a split definition for bold and italic will solve this. One could for instance use `**` for bold and `_` for italic. This will render correctly in any other Markdown parser, and should produce correctly nested formatting in novelWriter. There is then no ambiguity like `***`.

**Comment by vkbo** [comment]
This will be resolved by reverting to a distinct syntax for bold and italic. While Markdown supports both `*` and `_` as near interchangeable wrappers for emphasis (1 level wrapping) and strong (2 level wrapping), the recommended style is often cited as using `**` for strong and `_` for emphasis. Adopting this as a requirement resolves the ambiguity of `***text* text**` cases which now become `**_text_ text**`. Unfortunately, since the underscore is also a valid word character, some additional restrictions apply to its use. The formatting `_**text** text_` is not valid, since the first `**` is considered intra-word, which isn't allowed in novelWriter.

**Comment by johnblommers** [comment]
As a happy Pop!\_OS user I have formed the habit of escaping the underscore to avoid Markdown mischief.

**Comment by vkbo** [comment]
novelWriter has supported escaping of `_`, `*` and `~` for a while, but not properly handled them when converting to HTML. That has been added as well in the above PR.
