### ISSUE TITLE
Text in the Project Settings Details tab is not selectable

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#354]
I opened the Project Settings menu and clicked the Details tab to determine where my project sits in the file system. I needed to open a particular file with `vi` in the terminal to understand why a space between words was colored in. To my dismay I wasn't able to select the long pathname, I had to type it all in by hand.

Consider making the Project path selectable text.

**Comment by vkbo** [comment]
Sure thing. It's just a flag on the QLabel widget that holds the text. I'll fix it.

**Comment by vkbo** [comment]
>  needed to open a particular file with `vi` in the terminal to understand why a space between words was colored in.

Because it's a non-breaking space. They have a different background colour so they stand out. Hard line breaks and non-breaking spaces have a slight colour overlay on the background.

**Comment by johnblommers** [comment]
And it's a mighty fine feature. I wanted to point that out. Spaces are not always what they appear and highlighting non-breaking spaces is helpful.

**Comment by vkbo** [comment]
I've changed the shortcut key from `Shift+Space` to `Ctrl+K, Space` to avoid accidental non-breaking spaces. I also added a bunch more `Ctrl+K` insert features in the new Insert menu.
