### ISSUE TITLE
Archive/Outtakes Root Folder

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#414]
### The Issue

While it is possible to just remove files from the project by changing the "include in project" flag, it would also be nice to have a folder for files that are taken out to keep the project tree clean. In my case these files will typically be the summary files of the story that I made prior to splitting them up into scenes. The files are still nice to have as reference, and the split tool does not anyway delete the original file.

Currently I have a subfolder in the Novel folder named "Archive" where all files have the export flag off. It achieves the same thing, but is more manual.

### The Solution

A folder that is equivalent to the Novel root folder that can hold any file, but the files are automatically excluded from the builds. The folder could be named "Archive" or "Outtakes". The latter is more on topic I guess.

**Comment by johnblommers** [comment]
This is a great idea. As we speak I've got a bunch of scenes that I've removed from my main story. But I want them close because there's material there that I may re-purpose later on. The Outtakes feature will do the job.

**Comment by vkbo** [comment]
Yeah, I have the same issue. I've merged the PR into main now, but I'm testing it for bugs. I found one already where it resets the word counts for the folder if you rebuild the index. There's a fix ready, but I'm testing for more at the moment.

**Comment by vkbo** [comment]
I've disabled creating subfolders within the Outtakes folder for now, as it complicates the logic. I may allow it later, but I won't allow draging and dropping entire folders to it I think. That is currently not allowed between root folders anyway.

**Comment by vkbo** [comment]
PR #419 also fixed an issue with this change where a file in a subfolder in Outtakes would still be included in the build.

**Comment by vkbo** [comment]
I'm happy with this implementation, so I'm closing this.
