### ISSUE TITLE
Document viewer back navigation

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#441]
The document viewer has the capability of back and forward navigation, but this isn't implemented. It would be convenient to be able to use the back button (especially on a mouse with such buttons) when quickly checking something by following a tag and going back.

**Comment by johnblommers** [comment]
This is a good idea!

**Comment by vkbo** [comment]
Just merged this into the main branch. It seems to be working fine as far as I've tested it. Hopefully there are no serious bugs!

I added navigation buttons at the top, left corner of the view panel, and menu entries in the View menu, with standard keyboard shortcuts. Standard mouse buttons should also work as long as they're mapped to backward/forward. Works on my mouse anyway.
