### ISSUE TITLE
Add a Search and Replace Feature

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#48]
Would a search and replace feature be added to novelWriter? I found myself having to switch to an external text editor to do edits.

**Comment by vkbo** [comment]
Yes, it's on my todo list.

**Comment by vkbo** [comment]
Just added a simple find function, connecting `Ctrl+F`, `F3` and `Shift+F3` keyboard shortcuts as well as menu entries. The search field is hidden until triggered, and can be closed manually.

I will extend the functionality to a full search/replace, but this is what I had time for right now.

**Comment by vkbo** [comment]
Full search and replace feature now implemented in master branch. They use the same keyboard shortcuts as VSCode, that is, `Ctrl+F` to open the search box and set selected text as search text, `Ctrl+H` to open the replace box, `F3` to find next occurrence, `Shift+F3` to find previous occurrence and `Ctrl+Shift+1` to replace selected occurrence and move to next. (I realise now that it will actually replace any selected text with what's in the replace box. will fix.)

Return key in search or replace box will got to next occurrence, and holding shift key will go backwards.
