### ISSUE TITLE
text fully justified

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#500]
**Describe the Bug**
The text both at the editor and view windows is fully justified. Is there a setting to change that?

**Screenshots**
![image](https://user-images.githubusercontent.com/1640855/99869325-ac5f8600-2bd2-11eb-9733-da422a10eb55.png)

**Additional Context**
I'm sure this isn't a bug. Just can't find the setting.

**Comment by vkbo** [comment]
Yes, in Preferences > Text Layout. It's labelled "Justify the text margins in editor and viewer".
