### ISSUE TITLE
Page size for exporting in PDF

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#507]
Is it too much trouble to be able to specify the page size while exporting to PDF? It makes it easier to estimate your progress than number of words, IMO, at least.

Alternatively (or additionally!), can the export to HTML (which is recommended for importing the text to MS Word) have all normal text styled as "Normal"?

**Comment by vkbo** [comment]
> Is it too much trouble to be able to specify the page size while exporting to PDF? It makes it easier to estimate your progress than number of words, IMO, at least.

Export to PDF is just a shortcut for print to PDF. It is exactly the same as selecting Print and selecting PDF as your printer. If you go the manual print route, you can also select your paper size.

On the other hand, calculating a project's page count may be a useful thing. Currently, there's a Details tab in the Project Settings with some information. I've considered making a "Project Details" dialog that sum up more data, perhaps as a part of the Build Novel Project tool or Writing Stats.

> Alternatively (or additionally!), can the export to HTML (which is recommended for importing the text to MS Word) have all normal text styled as "Normal"?

I'm not sure what "Normal" style is referring to here. Which style is applied to the various html elements is determined by the import functionality in MS Word and Libreoffice Writer. The export from novelWriter is standard HTML5 with minimal CSS3 styling.

I don't have access to MS Word, but Libreoffice Writer seems to generate styles based on the HTML+CSS classes used in the exported file.

**Comment by alexisargyris** [comment]
I hadn't thought of print previewing the result of "Build Novel Project". As you said, the print dialog allows to (re)set the page size and then the document gets repaginated. It's exactly what I was looking for. Thanks!

As for MS Word styling I mentioned it just in order to facilitate formatting the exported document. Currently, in MS Word, all headings seem to have a "Heading 1" style set but simple text doesn't have any style set.

**Comment by vkbo** [comment]
Interesting. This is certainly a limitation of MS Word's import feature. Perhaps there is a way to tag the HTML elements to push Word to interpret the formats.

Did you try exporting without applying any formatting? There is a "Disable styling" option on the Build Novel Project dialog.

I may write a proper exporter to Open Document Format in the future, where I would have more control over these things. However, I've attempted this before, and it isn't a trivial task. But it is on my ToDo list.
