### ISSUE TITLE
Kindly provide "Fountain" screenwriting markup feature to this and a debian 32 bit file

### ISSUE THREAD

**Issue by rokfrog** [vkbo/novelWriter#510]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by vkbo** [comment]
Please fill in the feature template, or write a complete description of what you're requesting. The headings are already there for you to complete.

I don't know anything about screen writing, and although I have some idea of how a script looks like, i know next to nothing about the rules of how they are written. Please describe what "markup features" are requested.

I'm not sure what you're requesting with "a debian 32 bit file". I don't provide any Linux packages at this time. novelWriter is written in Python, so there are no binaries to build other than its dependencies. If the dependencies are met, you can run it on a 32 bit system.

**Comment by vkbo** [comment]
Having had a look at the Fountain spec, it is clear that it is incompatible with the syntax that exists in novelWriter. See: https://fountain.io/syntax

I will not add support for this. At least not at this point. It would essentially require a separate set of syntax highlighting, indexing and parsing classes, which would in effect split novelWriter into two separate modes. It is certainly doable as novelWriter is written in an object-oriented way, and all these elements are classes that could be swapped out. However, it is still a lot of work to extend novelWriter to do something it wasn't designed for.

I'm closing this issue for now. Feel free to update it to a more specific feature request, and I'll look at it again. At the moment I'm mostly guessing what it is exactly you're requesting.
