### ISSUE TITLE
Please support other GUI language

### ISSUE THREAD

**Issue by LittleRey** [vkbo/novelWriter#525]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by vkbo** [comment]
This is a duplicate of the already existing issue on this topic pinned to the top of the issue tracker, issue #93.

In addition, the feature template is there to be filled in with more details of the request. Please use it in the future. Thanks! :)
