### ISSUE TITLE
App not starts on `$ novelWriter`

### ISSUE THREAD

**Issue by Symbian9** [vkbo/novelWriter#566]
- **Version:** `1.0.1` (installed via `pip3 install novelwriter`)
- **System Info:** Debian 10 buster

### Expected behavior

App should start on `$ novelWriter`

Also after install there should be menu entry in "Office" category (guess, need add `*.desktop` file)

### Actual behavior

App not start on `$ novelWriter`

Only way to start it is to use full path: `$ ~/.local/bin/novelWriter`

Also there are NO any launcher added into menu.

**Comment by vkbo** [comment]
To set up the `.desktop` launcher, install with `./setup.py xdg-install` from the folder where novelWriter is installed. Please see the [documentation](https://novelwriter.readthedocs.io/en/stable/int_started.html#setup-on-linux).

For the second point, make sure `.local/bin` is in your `$PATH`.

**Comment by Symbian9** [comment]
> For the second point, make sure .local/bin is in your $PATH.

How to do that?

**Comment by vkbo** [comment]
There you go :)
https://www.howtogeek.com/658904/how-to-add-a-directory-to-your-path-in-linux/

I should probably add a note on the pip install approach that it doesn't install novelWriter as a GUI app. Thanks for the feedback by the way!

**Comment by Symbian9** [comment]
OK.

As for first I just checks and files installed as:

```
/home/user/.local/bin/novelWriter
/home/user/.local/lib/python3.7/site-packages/novelWriter-1.0.1.dist-info/*
/home/user/.local/lib/python3.7/site-packages/nw/*
```

But non of those folders include `./setup.py` & it seems like a bug of `*.whl`on PYPI.

How should I fix it? Manually adding `./setup.py` by copying it from GitHub repo?

**Comment by vkbo** [comment]
The best way of installing on Linux is to just install from the tarball from the releases page (or clone the repo). I'll check again what the pip package does on a virtual machine when I get home from work, and update the documentation to note what needs to be done in addition to the  pip install command.

I'm reopening the issue, and changing the tag. Thanks again!

**Comment by vkbo** [comment]
Ok, I've updated install instructions. Hopefully this is clearer now. Thanks for the feedback!
