### ISSUE TITLE
installing via pip does not include dependencies

### ISSUE THREAD

**Issue by a2800276** [vkbo/novelWriter#570]
Installing via pip does not install all dependencies automatically as stated in READ and implied on novelwriter.io

I'm installing in a fresh virtualenv under Ubuntu 20.04 using the following commands:

    
```
$ virtualenv -p python3 novelenv
$ pip install --upgrade pip
$ . novelenv/bin/activate
(novelenv)$ pip install novelwriter
Collecting novelwriter
  Using cached novelWriter-1.0.1-py3-none-any.whl (2.8 MB)
Installing collected packages: novelwriter
Successfully installed novelwriter-1.0.1
(novelenv)$ novelWriter 
Traceback (most recent call last):
  File "/home/a2800276/projects/novel/novelenv/bin/novelWriter", line 5, in <module>
    from nw import main
  File "/home/a2800276/projects/novel/novelenv/lib/python3.8/site-packages/nw/__init__.py", line 32, in <module>
    from PyQt5.QtGui import QIcon
ModuleNotFoundError: No module named 'PyQt5'
```

installing PyQt5 manually  causes a new error concerning missing lxml and the program hangs and cannot be killed with ctl-c

```
(novelenv) $ novelWriter 
CRITICAL  Python module 'lxml' is missing.
```

installing lxml using: `pip install lxml` finally does the trick

**Comment by vkbo** [comment]
That's strange. The dependencies are listed in the `setup.cfg` file, and pip should install them. It does so when I run the command locally, so I'm not sure what's the issue here. You can also run the `pip install -r requirements.txt` command as mentioned in the docs.

**Comment by vkbo** [comment]
Ok, managed to reproduce with a clean install. Will investigate.

**Comment by a2800276** [comment]
Just to clarify: I'm not running pip in the context of a source package, all the steps above are from an empty directory, so there is no requirements.txt or setup.cfg. 

I see you noticed that already, but it may help others running into the same problem. Running:

```
pip install PyQt5 lxml
```

after installing is an easy workaround. This is probably obvious to all the programmers but may not be for the target audience :)

**Comment by stranger-danger-zamu** [comment]
I was checking out the program (which I love by the way) and noticed this bug when I was going to submit a feature. Looked into it and it was just having the install_requires under the meta_data instead of the options sections in the setup.cfg file.

**Comment by vkbo** [comment]
> Just to clarify: I'm not running pip in the context of a source package, all the steps above are from an empty directory, so there is no requirements.txt or setup.cfg.

The `setup.cfg` file should be parsed when creating the PyPi wheel, but there was clearly a bug in it. The dependencies were moved from the `setup.py` file to the `setup.cfg` file recently after I learned that this is the preferred method now. Thanks for reporting this issue.

> I see you noticed that already, but it may help others running into the same problem. Running:
> 
> ```
> pip install PyQt5 lxml
> ```
> 
> after installing is an easy workaround. This is probably obvious to all the programmers but may not be for the target audience :)

I've added this to the docs, and I removed the install instructions from the main README as it's messy to keep two versions of the same instructions in sync. I added a TLDR section instead, with a link to the full docs.

Thanks for the feedback. It is always useful with new eyes on this!

**Comment by vkbo** [comment]
New release have been pushed to GitHub and PyPi, and the dependencies are now listed again. Thanks!
