### ISSUE TITLE
Embedded code snippets

### ISSUE THREAD

**Issue by cweagans** [vkbo/novelWriter#571]
I know, I know: code snippets in a novel? Hear me out though:

As far as I can tell, the process of writing a technical book and the process of writing a novel are largely the same. There’s usually a fair amount of reference material to keep track of, ensuring that material is presented in a cohesive order, etc. In fact, the only thing that novelWriter doesn’t do that I’d need in order to be able to switch from my existing tools is a structured way to automatically pull in code from some external source and embed it inline in the page. Ideally, this code wouldn’t be copy/pasted into the text - the text would just reference the path to the file in question, the relevant git commit in that repo, and the line numbers to pull in.

That is, I’d want to be able to say “embed the contents of ./path/to/my/repo/path/to/specific/file at commit a4b7c9d2, lines 42-80”

Alternatively, some kind of plugin system to allow users to do this outside of the core product would also be amazing.

I know it’s not really the core audience for this tool, but is that a possibility nevertheless?

**Comment by vkbo** [comment]
Problem is that novelWriter cannot display code/verbatim blocks anyway. It isn't a markdown editor, rather it's a plain text editor with minimal formatting using markdown-like syntax. The syntax is currently limited to headings and text emphasis. I have written the parser with such simple syntax in mind, which makes it fast but also inflexible in terms of extending it to full markdown syntax. I would anyway thing reStructuredText was far more suitable for technical writing?

The export feature does allow exporting the project to a format that can be further processed by for instance a Python script. You can export the project to either novelWriter raw text or HTML wrapped in a JSON data structure.

**Comment by cweagans** [comment]
Thanks for your thoughts! I'll ponder this a bit.
