### ISSUE TITLE
User-defined, Work-specific Glossary

### ISSUE THREAD

**Issue by stranger-danger-zamu** [vkbo/novelWriter#574]
Being able to define words would be useful since not all words in fiction will be real. If this could be included into the spellchecker, I'd be more than happy but I know that that highly depends on how the spellchecking is implemented so it might not be possible. 

In terms of usability, if I could right click a word that is detected as spelled wrong and add it to the glossary that'd be sufficient. Being able to go into the glossary and add definitions and tag the word's parts of speech would be a great stretch goal.

**Comment by vkbo** [comment]
If you right-click on a misspelled word you can select "Add Word to Dictionary" which adds the word to a text file in the project folder, in the `meta` subfolder.

Is that the feature you're looking for?

**Comment by stranger-danger-zamu** [comment]
I might have missed that :sweat_smile: .

**Comment by stranger-danger-zamu** [comment]
No wait! It doesn't appear when there is no spelling suggestions!

**Comment by vkbo** [comment]
No, this is purely to stop the spell checker from complaining. If the spell checker doesn't complain, there is no menu entry for it. I'm not sure I understand why you'd need it if the spell checker doesn't flag it?

**Comment by vkbo** [comment]
Ah, wait, it's part of the spell check menu, so with no suggestions, the function exits before adding that option. Is that what you're seeing? If so, that's actually a bug.

I'll have a look ...

**Comment by vkbo** [comment]
Confirmed. Good work! Fix incoming :)
