### ISSUE TITLE
Setting Word goals per item

### ISSUE THREAD

**Issue by bitwave** [vkbo/novelWriter#588]
It would be awesome to set word goals like 500 Words per scene/page/chapter/etc. and see a progress bar on the bottom.
Additionally, calculate word targets for compound items like chapters and calculate remaining time using the already existing statistics

**Comment by vkbo** [comment]
Hmm, I have never understood why you'd want to set a word target for a scene. Scenes vary widely in length, and should be as long as they need to be. You can already see the word count of a scene if you keep them in one file each, or in the Outline view if you have several scenes in a file.

As for the aggregated count of a chapter, that is already added in the development version of novelWriter, and will be a part of version 1.1. If you want to check it out, it's in the `dev` branch.

**Comment by vkbo** [comment]
I missed the point about "calculate remaining time". I'm not sure I understand what you mean here.

Also, here's what the chapter details tab looks like in the `dev` branch.
![image](https://user-images.githubusercontent.com/1619840/105616166-2976c980-5dd5-11eb-812b-a964dd9fba36.png)

**Comment by bitwave** [comment]
> Hmm, I have never understood why you'd want to set a word target for a scene
Clear point. You're right, I meant mostly chapters.
The progress part is exactly what I missed, so I have to wait for the newer version :+1: 

> I missed the point about "calculate remaining time". I'm not sure I understand what you mean here.
I saw the "writing statistics" tab, maybe this can be used to calculate an overall estimate, when the comple novel is finished, based on how much someone writes per day.

**Comment by vkbo** [comment]
> The progress part is exactly what I missed, so I have to wait for the newer version 

I plan to make a pre-release of 1.1 next weekend so people can test it for issues before I make a final 1.1 release.

> I saw the "writing statistics" tab, maybe this can be used to calculate an overall estimate, when the complete novel is finished, based on how much someone writes per day.

That would be as accurate as "estimated time left" in Windows and on downloads :P

**Comment by bitwave** [comment]
>That would be as accurate as "estimated time left" in Windows and on downloads :P

:D

**Comment by vkbo** [comment]
The 1.,1 RC 1 version has been released, and I hope it covers ar least some of this suggestion. I'm not sure if I want to start adding progress bars on the GUI.
