### ISSUE TITLE
Typescrolling does not working on Windows

### ISSUE THREAD

**Issue by Ellipsine** [vkbo/novelWriter#589]
Hi  ! #

I really need typescrolling for my project however on Windows the option does not work properly on my computer. The line does not come up automaticaly whatever I activate it or not on the parameters screen or purcent I choose. Sometimes it works but it cease to function and now it does not work at all.

**Comment by vkbo** [comment]
For the scroll feature to work there need to be enough text to actually scroll. If the "scroll past end" option is on, you need to get to the middle of the window before the feature kicks in.

I'll check on Windows to see if it works just in case.

**Comment by vkbo** [comment]
Just tested on Windows 10, and everything seems to work fine for me.

Basically, if there's no vertical scrollbar, the feature doesn't have anywhere to scroll, so it does nothing. As soon as the scroll bar appears, it can start working. The scroll bar appears when you've reached 40% down the editor window (assuming you haven't hidden the scrollbar).

**Comment by vkbo** [comment]
I'm making a minor improvement to how this feature works. The "Scroll past end" feature now matches the typewriter range of settings.

You still have to enable the "Scroll past end" feature for the Typewriter scroll feature to have any space to scroll on a new document, but at least now thew two features work together and don't contradict each other.
