### ISSUE TITLE
Blank Document Does Not Have Cursor

### ISSUE THREAD

**Issue by dazappa** [vkbo/novelWriter#608]
Using v1.0.3

If you have an empty document, the editor will not show a blinking cursor even if the editor has focus.

It would be good to have a blinking cursor in an empty document for two reasons:

1. So the user has no doubt the editor currently has focus
2. So the user knows where text will begin appearing when typing (my brain is weird)

If the document has any content in it and you focus it in any way, a blinking text cursor appears as expected.

I'm not sure if blank documents not having a blinking cursor is a Qt limitation or not.

**Comment by vkbo** [comment]
I am aware of this, and have tried to fix it before. I think it's a Qt thing, and I find it annoying too. I'll look into it again.

**Comment by vkbo** [comment]
Fix has been merged to the `release` branch and will be included in Version 1.1 RC1.
