### ISSUE TITLE
Change Focus from Outline Tab

### ISSUE THREAD

**Issue by dazappa** [vkbo/novelWriter#612]
When in the Outline tab, it is not possible to focus the Document Editor or Document Viewer. (Alt+2, Alt+3).

It would be nice if when in the Outline tab, focusing the Editor or Viewer automatically first switched to the "Editor" tab

**Comment by vkbo** [comment]
Good idea. Together with #609, I'll add these to the 1.1 RC 1 release I plan for this weekend.

Thanks!

**Comment by vkbo** [comment]
Added and merged into the `release` branch, which will be tagged for Version 1.1 RC 1 this weekend.
