### ISSUE TITLE
Unclear usage of @command: value construct

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#64]
Section 5.1 of the documentation notes that:

`@command: value` A command followed by a value or a comma separated list of values.

We've tried substituting Linux command line tools but nothing happens, the entire line is ignored. In short I have no idea what this feature is supposed to do. What hidden power lies in wait to be discovered? 

Could you add a few examples in the documentation on how this feature is used?

**Comment by vkbo** [comment]
The documentation isn't quite up to date, so sorry about that. I will have a look at it on the weekend.

The purpose of the command feature is to add meta data about the connection between scene/chapter files and project notes. Each project note can have a tag, set with `@tag`, which each scene/chapter file can refer to.

How this works is demonstrated in the sample project in the source folder. You can have a character profile file with the tag `@tag: John`, and a scene file can then refer to the character John by for instance setting `@pov: John`. If you then open the Timeline View window `Ctrl+T`, you can then see a table with all your scenes and chapters on the vertical axis, and all your tags on the horizontal. A dot will indicate where a scene or chapter refers to a tag. The idea is to produce an overview of which scene has which characters, point-of-view, location, timestamp, whatever you want to track really.

It is especially useful for tracking multiple point-of-views, which I use myself. It can also be used for tracking objects, like the infamous "who has the gun now" problem for writers of the TV-show Lost in their first season(s).

In any case, this is a feature I took from yWrite. I found it very useful.

Calling it a command is perhaps misleading. It is probably better to call it a setting.

**Comment by vkbo** [comment]
Addressed in the recent update of the documentation.
