### ISSUE TITLE
Windows Installer and Warnings

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#640]
I wasn't prepared for how hostile Windows is as an environment to Open Source projects. I keep getting reports that novelWriter and the installer is flagged as all sorts of nasty things. Here's a few points about this:

### Malware Warning

Prior to version 1.0.3, the Windows version was packaged with `pyinstaller`. This is the source of the malware warnings that some scanners report (although a lot of them don't because `pyinstaller` is a very common tool for packaging Python applications.) It is a false warning, but this is a recurring issue with `pyinstaller`. See the numerous reports on their [GitHub repo](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

I've recently changed the way the installer is built to drop `pyinstaller` and do the packaging process manually. But there are still issues.

### Unknown Publisher

The "Unknown Publisher" warning is simply because since this is a hobby project, I don't want to spend hundreds of dollars a year for a certificate to sign these installers. Both Windows and MacOS are currently moving in a very Open Source hostile direction on this, so I am inclined to just stop providing these installers completely because I keep getting emails and issue reports from concerned users. Security is important, but there need to be non-commercial ways of approaching this. I also really don't want users to have to deal with this. I'm concerned about security myself, it comes with my job, so if I wouldn't have installed it, I don't expect others to either.

## Moving Forward

I'm a Linux user, and on Linux running a Python app like this is trivial. I've spent a lot of time trying to figure out a good way to distribute novelWriter to Windows users. From version 1.0.4 I'm adding the necessary code to just run novelWriter directly from an extracted zip file of the source. Then you can put it anywhere on your PC and run it. To make this easier, I'm also adding a simple Windows double-clickable batch script that will install the Qt framework for the GUI and create the icons for your desktop and start menu. I hope this is easy enough also for non-technical users. It does require that you first install Python though, but that is as easy as installing any other application.

The instructions for how to install on Windows have been added to the [documentation](https://novelwriter.readthedocs.io/en/latest) under "Setup on Windows". Version 1.0.4 is the first release to support this approach. I will likely stop adding the Windows installers to the releases and the website after that. Please test out this approach.

**Comment by gedakc** [comment]
Your description and approach to the issue makes complete sense to me.  We each choose how to spend our time, and I know that I would rather spend my time creating software and devising innovative solutions to problems instead of fighting with open source hostile operating systems.

One benefit to not providing packages and instead requiring uses to install python and source code is that the user base will need to be more knowledgeable and may perhaps be more forthcoming with helpful patches and suggestions.

Thanks again for offering your software as open source.

Sincerely,
Curtis Gedak

**Comment by vkbo** [comment]
Thanks :)

I just merged a `setup_windows.bat` script that will just run through the few steps needed and do everything for you, except install Python itself. I suppose that is about as easy as I can make it. I mean, you can just double-click the `.bat` file.

I figured out how to create desktop icons and add the needed registry keys so you also have the option to double-click a novelWriter project file from the file explorer. It does nearly everything the setup.exe file does. I hope that is easy enough for most users.

**Comment by vkbo** [comment]
It's been a few releases since I stopped making the Windows installer, and I think this issue can be closed. It is linked from the documentation under the Windows Setup page.
