### ISSUE TITLE
Session timer

### ISSUE THREAD

**Issue by alexisargyris** [vkbo/novelWriter#651]
Is it possible for the session timer to pause when novelWriter's window loses focus?

**Comment by vkbo** [comment]
This is a duplicate of #606.

But yes, I'm planning to add this feature. I was thinking to pause the timer after a certain amount of inactivity instead of on focus-loss.

**Comment by alexisargyris** [comment]
Sorry, forgot to check first.

**Comment by vkbo** [comment]
No problem. It may be a good idea to check both for idle time and loss of focus. I'll leave it open so both methods can be implemented.

**Comment by vkbo** [comment]
I've made a PR on this that I will think a bit more about before I merge, but I added a descriptive comment on the other issue: https://github.com/vkbo/novelWriter/issues/606#issuecomment-775521726

**Comment by vkbo** [comment]
See https://github.com/vkbo/novelWriter/issues/606#issuecomment-776229710
