### ISSUE TITLE
Sync view pane with edit pane

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#66]
If the view pane is showing the same document as the edit pane, it should be possible to sync the scrolling, or at least the cursor position. This can be achieved by inserting an anchor tag before each block in the html.

If this is done, it is probably useful to also have the option to show comments and meta tags in the preview.

**Comment by vkbo** [comment]
This has already been addressed in part. When ctrl-clicking on a tag reference, the corresponding document is opened in the view panel, and the window will scroll to the heading where the tag points to.

The HTML converter does preserve the soirce document line number, so in principle this can be achieved by aligning the top visible lines in each window, but this is not straight forward. I will take it off the release 1.0 schedule for now.

**Comment by vkbo** [comment]
I think this issue has been sufficiently addressed. Scrolling to the correct position when following links is the most important point. Parallel scrolling when using the viewer as preview goes against the point of the viewer.

**Comment by johnblommers** [comment]
Agreed.
