### ISSUE TITLE
(for French text) non breaking thin space before some chars

### ISSUE THREAD

**Issue by jyhelle** [vkbo/novelWriter#703]
Well, I eventually started doing "serious work" with novelWriter, and...

When typing French text we must add a narrow non breaking space, 202F, (or non breaking space if the former isn't available) before the "big punctuations". i.e. those signs made of two parts, namely ! ? : ;
There is also a nnbsp to be added between the angled quotation marks « » ‹ › and the text they enclose, that is right of the opening one and left of the closing one.

These are inserted automatically by Libre/Free Office or MS Word, and I think adding these nnbsp when typing should be an option in nW as the Ctrl-K Ctrl-Space sequence becomes quickly tedious !

(There are other places where the nnbsp is mandatory, like before % or as thousands separator in large numbers, but these are much less frequent when writing novels)

**Comment by vkbo** [comment]
Ah, yes, this was partially why I added these space characters in the first place.

I can't make it standard for « » ‹ › as Norwegian uses the same quote marks as French, but without the spaces, but I can certainly add the insertion of these to be automatic as an option. Perhaps a switch for quotes and another switch for ! ? ; :.

The usage of these between number and units (including %) is correct for English as well, but I agree they aren't as frequent and don't need to be automatic.

**Comment by jyhelle** [comment]
I think the two-switches solution should be OK, as I am not sure how other languages treat the problem. For sure there is nothing like that in both Spain-Spanish and Italian (no mention anywhere in Wikipedia and checked in several printed books in both languages)

**Comment by vkbo** [comment]
Yes, I'm also not familiar with any (western) languages that use space in the same way French does.

About the shortcut: It is very hard to find keyboard shortcuts that are not in use already on some systems, especially when they involve the Ctrl modifier. Ctrl+Space does nothing on my Debian system for instance. If you have a better suggestion, I'm happy to alter it. Originally, I used Shift+Space for regular non-breaking space, which is a common shortcut, but people keep typing it accidentally so I changed it.

I know 202F is the correct unicode character for these spaces, but I also see that with some systems or fonts that character doesn't show up properly and one tends to fall back to regular non-breaking space. Does this too need to be an option?

**Comment by vkbo** [comment]
And another issue: nW doesn't know the difference between a right-closing single quote and an apostrophe. In English it doesn't matter because they are the same symbol, but in French it does matter, and in Norwegian as well. Pressing `Ctrl+K, '` will insert a proper apostrophe symbol though, but it is a bit clunky.

It is very rare to use ‹ › in Norwegian, so I would just switch off auto-replace for single quotes, or set it to use the English ones.

**Comment by vkbo** [comment]
I decided to make a test document using Libre Office set to French:

![image](https://user-images.githubusercontent.com/1619840/111050868-6d8a6000-844f-11eb-8ce6-db6f347df92a.png)

I noticed that only the double quotes are replaced with the proper French ones, and the single quotes are replaced with the standard English ones, which solves the apostrophe issue. I also checked the non-breaking spaces, and they are regular non-breaking spaces, not thin non-breaking spaces 202F.

**Comment by jyhelle** [comment]
I don't use single French quotes, and they are rarely seen in texts, people tend to use the English ones (e.g. to quote inside a quote), and that is probably the rationale behind the LibreOffice choice. I know it was different some time (years ?) ago, might have been with Open and not Free Office... But again I didn't use the single angled one, so I would gladly use the English ones.

Regarding the narrow or standard non breaking space, I have different typographical codes, from different origins. The most praised are those from the National Printshop and Yves Perrousseaux, both use the nnbsp, but it is common practice to use the nbsp when the font used doesn't provide the nnbsp (especially when unknown characters are replaced by a ugly white square or a big question mark !)
Anyway I have a typographical code that you might prefer, as it comes from the CERN, and it only mentions the nbsp.

About the shortcut, I'll change the one used to call the launcher, probably using those "Windows" keys that are not used on my keyboard

**Comment by vkbo** [comment]
I've started adding the features in PR #704. They were actually quite easy to add with the current code structure. You can test them, but you currently have to manually edit the configuration file as I haven't yet added them to Preferences. (You need to open and close nW once to get the new settings fields into the config file).

The settings are:
```
fmtpadsingle = False
fmtpaddouble = False
fmtpadthin = False
fmtpadpunct = False
```

The third option will let you choose between nbsp and nnbsp. They are all `False` by default.

As for the shortcut, I found a long list of usage of the Ctrl+Space keys in numerous applications on both Windows, Mac and Linux. Interestingly, the Windows+Space shortcut is the standard shrotcut for switching keyboard layout on both Windows and Linux. When I worked at CERN I frequently shifted between Norwegian and English keyboard layout, and sometimes French. I've now gotten used to working on a UK English keyboard and use the compose key instead for Norwegian characters.

**Comment by jyhelle** [comment]
I asked a spanish newswriter about similar problems in Spain-Spanish, and he only mentioned nnbsp around the text of an interrogation or exclamation sentence where they use upside-down question or exclamation mark to open the sentence and normal ones to close it 
¿ see what I mean ?   ¡ yes for sure !
So these upside-down marks might be included with the normal ones, hence treated as opening quotation marks, as I don't think they are used anywhere else than in Spanish.

**Comment by vkbo** [comment]
Ok, thanks. I will probably split the pad punctuation option up into colon/semicolon and question/exclamation then. It should cover both French and Spanish.

**Comment by jyhelle** [comment]
waiting for Hungarian or Moldovan-Wallachian, lol
samedi, 13 mars 2021, 11:52PM +01:00 de Veronica Berglyd Olsen  ***@***.*** :

**Comment by vkbo** [comment]
In the end I decided to add three new settings to Preferences. There is a free text box where you can add single characters and symbols which will have a non-breaking space added before it, and the same for symbols to add a space after. There is also a switch to change whether it is a thin non-breaking space or a regular non-breaking space.

I think this should cover all known possibilities, and the user gets to choose which characters it applies to. It may even be convenient to use for dashes in UK English and other languages where non-breaking spaces are sometimes also wanted.

PR #704 has now been merged to `dev`, so please try it out and see if it works in practice.

**Comment by vkbo** [comment]
Since this has been merged, I'm closing this issue. You can still add comments here if there are issues with the changes, and we can reopen this issue thread if needed.
