### ISSUE TITLE
Search doesn't work because of lacking focus

### ISSUE THREAD

**Issue by gorhu** [vkbo/novelWriter#708]
Hi! After updated to 1.2, I noticed search doesn't work now. It looks like related to [701](https://github.com/vkbo/novelWriter/issues/701) because this time I see something on my terminal with verbose when I click search button (but I'm not sure of course):

`nw.gui.doceditor:664   VERBOSE   Editor does not have focus`

**Comment by vkbo** [comment]
Confirmed.

It's not related to #701 as these are in tow different classes, but it's a similar issue and probably related to the same round of changes. The searching still works, it just doesn't work when the search text has focus. You must manually click in the editor and search by pressing `F3`. The button doesn't work either.

It's easy enough to fix. Thanks for reporting it.

As last time, this is not caught by the tests as they are run headless and focus checks don't work. I will go through all the places that use focus checking to make sure they work properly. I'll make a patch release to resolve this. It's an annoying bug for sure.
