### ISSUE TITLE
Ubuntu 20.04 also needs package python3-setuptools

### ISSUE THREAD

**Issue by theselfupgrade** [vkbo/novelWriter#714]
/Downloads/novelWriter-1.2$ ./setup.py install
Traceback (most recent call last):
  File "./setup.py", line 969, in <module>
    import setuptools # noqa: F401
ModuleNotFoundError: No module named 'setuptools'

~/Downloads/novelWriter-1.2$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

To fix I did this: 
**sudo apt-get install python3-setuptools**

Then did this: 
 **./setup.py install**
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python3.8/dist-packages/test-easy-install-55697.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.8/dist-packages/

Perhaps your account does not have write access to this directory?  If the
installation directory is a system-owned directory, you may need to sign in
as the administrator or "root" account.  If you do not have administrative
access to this machine, you may wish to choose a different installation
directory, preferably one that is listed in your PYTHONPATH environment
variable.

For information on other options, you may wish to consult the
documentation at:

  https://setuptools.readthedocs.io/en/latest/easy_install.html

Please make the appropriate changes for your system and try again.

So then I just did this, but since the docs said it could install locally, I thought I'd mention the above error.

sudo ./setup.py install

**Comment by vkbo** [comment]
You're right, running a manual install requires `setuptools`. I should add this to the documentation.

Installing with `pip` or running from source does not require it. Neither do the other setup commands other than `install`. I think the error message it produces on its own are good enough, but as I said the docs should definitely mention it.

As for the access denied error, it all depends on whether you install it in user space or system space. In your case it's clearly trying to use `/usr/local/...` which requires `sudo` access. You can install in user space by adding the `--user` flag. These are all `setuptools` features, not anything included in the novelWriter seup script. All it does is forward the call to `setuptools`.

I'll make a mention of this too in the docs.
