### ISSUE TITLE
Windows can't find novelWriter.pyw

### ISSUE THREAD

**Issue by diseno-franco** [vkbo/novelWriter#727]
* A clear and concise description of what the bug is. Installed novelWriter with the setup_windows.bat file, when I click on the icon created it says that it can't find novelWriter.pyw
* Steps to reproduce the behaviour install python 3.9 with PATH option, run setup_windows.bat by double clicking, after installation double click on icon on desktop
* A clear and concise description of what you expected to happen. a window will appear saying that windows is looking for novelWriter.pyw with the options cancel and browse. a file with that extension can't be found in the folder
* If applicable, add screenshots to help explain your problem.
![imagen](https://user-images.githubusercontent.com/58040747/112734499-1aff7800-8f14-11eb-984a-9c2c811c4a2e.png)

![imagen](https://user-images.githubusercontent.com/58040747/112734485-07eca800-8f14-11eb-8e31-956198fcb3b9.png)

* If the error dialog popped up, copy/paste the content here.

**Comment by vkbo** [comment]
The `setup_windows.bat` script is intended to be used with the `novelWriter-1.2.1-minimal-win.zip` file. If you run it manually from the source package you have to copy or rename the `novelWriter.py` file to `novelWriter.pyw` yourself.

I can make a couple of modifications to the setup script to check for this.

**Comment by vkbo** [comment]
I've added a check in the setup script that will copy `novelWriter.py` to `novelWriter.pyw` if the file doesn't exist. It will be included in the 1.2.2 release that is anyway planned for tomorrow.

As I said, you can just do this manually now, or download the minimal zip file mentioned above which already has the `.pyw` file.
