### ISSUE TITLE
Please allow opening files in external editor.

### ISSUE THREAD

**Issue by jointri** [vkbo/novelWriter#732]
Could novelWriter have implemented the ability to open files in external editors that's available on your computer rather than use the built in one? I would like to use this program, but also like the editors I already use as well. Everything in this markdown is in plaintext, so no special features required for the editor. Just the option to set a GUI editor or open a terminal and use a terminal based editor. I would suggest implementing this via right click or a different button to be able to go back and forth from external editor and the internal one.

**Comment by vkbo** [comment]
There are several features provided by the editor that are specific for novelWriter including the entire tags and reference infrastructure, the specific highlighting that also validates these references, collection of other meta data, and s bunch of automated features. While it is possible to edit files within the project folder with other tools, it is not recommended and may cause novelWriter to crash for multiple reasons.

It is neither trivial to implement such a feature properly, nor does it make much sense considering what novelWriter does. This is not a plain text file editor, but a complete tool for managing and writing a novel.

**Comment by vkbo** [comment]
By the way, If you want to know where a specific file is located, you can select "Show File Details" from the "Documents" menu when a file is open. There's also a `ToC.txt` file in the project folder that will tell you which file on the disk belongs to which document inside novelWriter.

These have been added for people who do want to work with the files on disk, but editing them is at your own risk and will cause the index to get out of sync. I have no plans to encourage external editing.
