### ISSUE TITLE
Include languages other than english for Spellcheck

### ISSUE THREAD

**Issue by diseno-franco** [vkbo/novelWriter#735]
* A clear and concise description of what the problem is: I've been trying to add a spanish dictionary to the spellchecker, can't seem to find how to do it or where to add it
* A clear and concise description of what you want to happen: I want the spellchecker to spellcheck my spanish
* A clear and concise description of any alternative solutions or features you've considered: mixed language spellcheck and grammarcheck would be cool
* If applicable, add screenshots to help explain your request.

**Comment by vkbo** [comment]
Spell checking is provided by the [pyenchant](https://pypi.org/project/pyenchant/) library. It should look for dictionaries installed on your system, but you didn't specify which operating system you use. On Linux it's as simple as installing new hunspell dictionaries from the package manager.

novelWriter just tells pyenchant what dictionary to pick, that's all. You can set a global one in Preferences, and even set a custom one for a specific project in project settings.

As for grammar checking and other language tools, see #515 and #712 where there's an ongoing discussion on such features. I'm considering adding LanguageTools for instance.

**Comment by vkbo** [comment]
Also, you may have to select "Spell Enchant" as the spell check provider in Preferences. If's set to "Internal", only English is available by default.
