### ISSUE TITLE
Clarify best practices for LaTeX export

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#78]
Consider documenting the following suggestions for users exporting to LaTeX:

1. Set the Fixed Width to zero so LaTeX has maximum control over typesetting
2. Don't include any YAML in the Markdown source because it's passed directly to the output.
3 Avoid using special LaTeX characters, specifically the Ampersand `&` character because the LaTeX won't compile to PDF,  throwing a syntax error.

**Comment by vkbo** [comment]
Hmm, it may be best to simply drop fixed width for LaTeX export. It was only added to make the source more readable, but to be fair, other tools can be used to wrap lines in the generated source.

I will add a package to the dependencies to clear up unicode formatting in the .tex source as this is a fairly big job to code from scratch. The python package `latexcodec` seems to do the trick, and is also in the apt repo. I will make it an optional dependency and disable LaTeX export if it is not available.

**Comment by vkbo** [comment]
Fixed (hopefully) in PR #80.

Wrapping in LaTeX source has been removed. Most editors for post-export editing of the .tex have wrapping capability anyway.
