### ISSUE TITLE
When I run install.bat in Windows, I run into an error message like this:

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#805]
_This issue has been transferred from a different thread._
_Originally posted by @singlebunglemrbungle in https://github.com/vkbo/novelWriter/issues/481#issuecomment-858638668_

---

When I run install.bat in Windows, I run into an error message like this:
```
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 40: illegal multibyte sequence
```
Expected Action:
- Create novelWriting.exe
- Create desktop shortcut

What happened:
I guess successful running of setup.py  results in creating novelWritng.exe, but it does not.
And there is no desktop shortcut.

Fortunately, the program itself can be executed by running novelWriter.pyw nonetheless.

Source of the problem:
My windows locale is set to Korea, I guess unspecified encoding making the error.

---

Here's more latter part of the log from install.bat.

```
Windows Install
===============

C:\app\novelWriter>windows_install.bat

Looking for Python
Python 3.9.5
Python found. OK.
setup.py found. OK.

Requirement already satisfied: pywin32 in c:\users\gone\appdata\roaming\python\python39\site-packages (300)
Requirement already satisfied: pyqt5>=5.2.1 in c:\users\gone\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 1)) (5.15.4)
Requirement already satisfied: lxml>=4.2.0 in c:\users\gone\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 2)) (4.6.3)
Requirement already satisfied: pyenchant>=3.0.0 in c:\users\gone\appdata\roaming\python\python39\site-packages (from -r requirements.txt (line 3)) (3.2.0)
Requirement already satisfied: PyQt5-Qt5>=5.15 in c:\users\gone\appdata\roaming\python\python39\site-packages (from pyqt5>=5.2.1->-r requirements.txt (line 1)) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.8 in c:\users\gone\appdata\roaming\python\python39\site-packages (from pyqt5>=5.2.1->-r requirements.txt (line 1)) (12.9.0)

Windows Install
===============

Traceback (most recent call last):
  File "C:\app\novelWriter\setup.py", line 1236, in <module>
    winInstall()
  File "C:\app\novelWriter\setup.py", line 842, in winInstall
    numVers, hexVers = extractVersion()
  File "C:\app\novelWriter\setup.py", line 54, in extractVersion
    for aLine in inFile:
UnicodeDecodeError: 'cp949' codec can't decode byte 0xe2 in position 40: illegal multibyte sequence
Press any key to continue . . .

C:\app\novelWriter>
```
And here is a screenshot from the directory.
![image](https://user-images.githubusercontent.com/84944869/121535156-dbd5c300-ca3c-11eb-8ff2-5a31460ebb2e.png)

**Comment by vkbo** [comment]
Hi @singlebunglemrbungle,

All the script does is generate an icon on your desktop, your start menu, and add some registry keys so you can also double click a project file in your file explorer. The icons just launch the `novelWriter.pyw` file, which you also can du manually, as you discovered. There are no exe files generated.

Anyway, this seems to be an encoding issue. It looks like it tries to open the file as `cp949` encoding instead of `utf-8`. This seems to be an issue with Windows. I found [this](https://stackoverflow.com/questions/43821262/unicodeencodeerror-cp949-codec-cant-encode-character#43821283) discussion about it.

Could you please try to change line 53 in `setup.py` from:
```python
with open(initFile, mode="r") as inFile:
```

to this:
```python
with open(initFile, mode="r", encoding="utf8") as inFile:
```

and see if that fixes the issue? If it does, I can make a patch.

I'm not a Windows user, so I don't test this very often. I mainly work with Linux.

**Comment by vkbo** [comment]
I could not reproduce your issue on a Windows virtual machine, but I made a fix anyway and merged it into main. I think it should resolve the issue. If will be released with version 1.3.3, which I can do this weekend I expect.

**Comment by singlebunglemrbungle** [comment]
Yes, I did what you said, and it works flawlessly. Thank you for the time you took to fix somewhat unimportant thing.

**Comment by vkbo** [comment]
Great! That means the fix I merged yesterday should work too.

It's not an unimportant thing when the setup script doesn't work. Thank you for reporting it!
