### ISSUE TITLE
Capability to add images

### ISSUE THREAD

**Issue by dlzi** [vkbo/novelWriter#813]
Hey,

I just found this application and its looks very good.

One thing that I couldn't figure out is how to add an image to the text. For example, if I'm writing a user manual and I need to show a picture, how do I do? If this functionality doesn't exist, adding it will make noveWriter more versatile to the writers. 

Cheers.

**Comment by vkbo** [comment]
Hi, and thanks for trying out novelWriter.

You can't add images. It is not intended for writing technical documents, but for fiction. novelWriter is specifically tailored for organising and building a story. It is not a general purpose text editor. I have no plans to add support for images, lists or tables.

If you're looking for a multi-purpose text editor with a plain text syntax, I would suggest trying out GhostWriter, which is a full Markdown editor. It is excellent, and was one of the inspirations for novelWriter.

**Comment by oldstonegryzzly** [comment]
but... if I write a novel I might want to collect images, maps and more in a project note...

**Comment by vkbo** [comment]
It is still a plain text editor, so images aren't possible without a fundamental redesign. Also, the notes aren't really intended for storing research. Just character and plot notes. See #815.

I'm working on a rich text based clone of novelWriter, but I don't really have enough time for two projects right now.

**Comment by oldstonegryzzly** [comment]
thanks for the answer, I understand you, and anyway thank you for the job...
