### ISSUE TITLE
Allow for templates

### ISSUE THREAD

**Issue by TechGnome** [vkbo/novelWriter#841]
It would be nice to be able to set up templates - in addition to the 3 samples that come out of the box.
Use case: I just spent 20 minutes setting up my current project to use a layout format based on the Save the Cat beat ... which involved a lot of copying & pasting. It would be nice to 1) Save this off as a template so that if I wanted to use it as a base for additional projects, I could, and 2) it could be shared with others wanting to do the same.

**Comment by vkbo** [comment]
Thanks!

This can easily be implemented by extending the sample project logic to allow for unpacking template projects from a file dialog, or from a repository of submitted templates.

This requires the need for exporting a project as a template, which is simply to create a zip file of the `nwProject.nwx` file and the `contents` folder.

_This is a branch-off from a discussion in #798._

**Comment by vkbo** [comment]
Added to this issue for future reference:

There is a discussion about the Snowflake method in #853. This may also be accommodated by a template. Perhaps one that is shipped with novelWriter.

**Comment by vkbo** [comment]
The new Welcome screen that will be available in 2.3 has an option to copy another project when creating a new project. The logic behind that option was added just now in #1680, so I consider this issue resolved.

What is and isn't a template project is up to you. novelWriter will take any project as the source, so if you want a pure template project, you need to create a project for that purpose.

I plan to add the option to save a project as a single file, which will make this feature even easier to use, as moving around single files is easier than whole project folders. But for now, the template is a project folder like any other.

**Comment by vkbo** [comment]
The source project can now also be a zip file containing at least a `nwProject.nwx` file and any number of `.nwd` files in the `content` folder. This feature can also be used to create a new project from a backup of another project.

**Comment by hifron** [comment]
You could also have a web market with templates or maybe some donations for templates... Maybe with some guides how to use language for various literature styles for those not so literature well educated to became better writer or find new style or literature option and maybe make possibility to earn or make a hobby...

But for me is maybe more crucial to **create a new project from command line** (_to quickly test ideas_) and if there is possibility to use it with custom template from command line even better... Maybe another feature...
