### ISSUE TITLE
Project Details content not always updated

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#842]
Project Details content is not updated if the content of the project has changed between two times the dialog was opened.

I assume it is because the Qt library caches the dialog box in memory. The dialog needs an update function that is called every time it is opened to ensure content is updated.

**Comment by HeyMyian** [comment]
This issue seems to be back. The Project Details seems to fetch the `Title` and `Working Title` (possibly also `Author`) of the project that was first opened in this instance of novelWriter.

**Comment by vkbo** [comment]
Just open a new ticket. I think this is a different issue, This issue is about the outline in the second tab of the dialog.
