### ISSUE TITLE
Unclear warning about escaped unicode in LaTeX export

### ISSUE THREAD

**Issue by johnblommers** [vkbo/novelWriter#85]
When exporting to LaTeX the following warning is unclear for two reasons:

```
Failed to escape unicode characters while writing LaTeX file. 
The genrated .tex file may not build properly. 
Make sure the python package 'latexcodec' is installed and working.
```

1. `genrated` &rarr; `generated` is a simple typographical error.
2. According to Synaptic, there is no such package as `latexcodec`. The package is called  `python3-latexcodec` as mentioned in novelWriter's README file.

**Comment by vkbo** [comment]
Thanks for spotting the typo. It's been fixed.

The text clearly states that it's referring to the "python package `latexcodec`". That is what the package is called, see [latexcodec.readthedocs.io](https://latexcodec.readthedocs.io/en/latest/). The GUI will not refer to OS-specific package managers.

However, to be more helpful, I can add a link to the documentation for the missing package in the warning.

These issues have been addressed in PR #86.
