### ISSUE TITLE
How can I exempt pages from the word count in pages from 'Plot' to 'Trash'

### ISSUE THREAD

**Issue by boudiccas** [vkbo/novelWriter#857]
I find it rather disconcerting when writing a 'character' page and developing my character to find that the overall word count is growing. And the same when I'm writing my 'scene list'.

Therefore I'm asking for any pages from 'Plot' to 'Trash' to be exempted from the overall word count so that when you see the word count, its the word count of the actual book/novel only that you are writing.

**Comment by vkbo** [comment]
You can find word counts on all levels. The only place where there's a total word count for absolutely all files is on the status bar. The "Novel" folder has its word count right there next to the top folder. In the writing statistics tool you can filter out notes as well, and in the Project Details dialog you also only get the word count for the actual novel.

**Comment by vkbo** [comment]
I could potentially add a switch in Preferences named "Show status bar word count for Novel folder only" or something similar. The value displayed is handled by a single function, so it isn't particularly complicated to add the feature.

If this is the sort of thing you're requesting, that is ...

**Comment by boudiccas** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Veronica Berglyd Olsen ***@***.***> writes:

> I could potentially add a switch in Preferences named "Show status bar word count for Novel folder only" or something similar. The value displayed is handled by a single function, so it isn't particularly complicated to add the
> feature.
>
> If this is the sort of thing you're requesting, that is ...

Yes please.
    
Thanks
    Sharon.
- -- 
Debian 11.00, fluxbox 1.3.7, emacs 28.0.50, org 9.4.6
-----BEGIN PGP SIGNATURE-----

iQJPBAEBCgA5FiEELSc/6QwVBIYugJDbNoGAGQr4g1sFAmEfTTcbHGJvdWRpY2Nh
c0Bza2ltYmxlLnBsdXMuY29tAAoJEDaBgBkK+INbCZAP/3/pCbhZn7p05STSAaz+
K7gur4+AXUoBC5LnALIN3D7oiRHMFBbxISWSaZOnymhachbgLSDSmcIgEk2AfunV
jI4PqJcmwddzq/lXfNLxQE4S1XeZeyPpiIi28WRclEWF6bAmIr5KC5M4x8Pzn3RI
UbZCrMxTbRQ09YrK76k2QSn1RrHYxvN57i6y5OCL0dj2O+LIEKHvkgaDcaKCUDgj
cJA7jTDuvaTLfQSk2Ic6mZfgAgv6+Jv/wTJrItrot96GV74GRtXotQpmL1KM+rf9
EOKZ5dwhVsKTM02jlTRIBwTjlf7pX9jkpeEeewO9w8VbdazGJ+nBhncdPfwMcIVC
aWtqGWcSATvwCq/w5XrKr3JbsTaRvIwMvJZTwfVuBcKndhJ44fCToILrRtZNSTor
pb4Mb9ICE0xRDDrNQHIpHar5DWQ2/cdjOCFZ+SiXO9UlVMslx6LFA6rhSWJwcUsu
d7aHIBhTtPYiQ+16Ksca4QyyjZSYMaH9EiwTPcw6VFMpIsIAlp3WwU13b7EAqovR
+6y5zYZ21S/Hz4MS1mzGAyn0bPRqMW9ogT2MZkE35Hh42eE0OVSN173BWg0DEEUA
Ax1D3evCXiZsMgPQ6GCLBS1XNEzbUUQyBqzv2Te5y3a8xflYhq7radXrXKTg+2mm
1L0WJp20GZJ5AYvWasNbBfxR
=NECX
-----END PGP SIGNATURE-----

**Comment by vkbo** [comment]
Ok, not a problem. I'll add it for the upcoming 1.5 release.

**Comment by vkbo** [comment]
Added a setting on the "Editor" page of "Preferences" under the "Word Counts" heading. This will allow the exclusion of all project note files for the total word count display on the status bar.

It will be included in 1.5. The release candidate will be out this weekend I expect, and the full release after some testing and when translation files have been updated.
