### ISSUE TITLE
No quote syntax highlighting at beginning of paragraphs

### ISSUE THREAD

**Issue by kalrach** [vkbo/novelWriter#874]
I'm running novelWriter on linux and the quote's syntax highlighting does doesn't highlight at the beginning of paragraphs. I've tried on multiple projects and get the same result. Syntax highlighting does work if there if text before the quotes in the paragraph.

**Comment by vkbo** [comment]
I assume you figured this out? There are a few settings in Preferences that affect this feature.

Just curious if there is something that needs to be added to the documentation.

**Comment by kalrach** [comment]
I ended up using the keyboard combination CTRL + K, 3 from the documentation to add the left double quote (") at the beginning of the paragraph instead of using the double quotes from my keyboard. It's still strange having to use the keyboard combo if its the beginning of the paragraph rather than being able to use the double quotes off the keyboard in my opinion, but it's not the end of the world.

**Comment by vkbo** [comment]
What symbols do you have set in Preferences for double quotes? The highlighter will only highlight a set of open and close quotes matching those. These default to the standard double 66 and 99 style quotes for English. A matching set of straight quotes will then be highlighted with red (depending on syntax theme) to indicate the wrong quotes are used.

**Comment by kalrach** [comment]
I have it set to the standard American style left and right quotes. I've been using the double quote key on my keyboard to insert quotes which I thought would automatically input left and right quotes when appropriate. They came out fine in the first few instances when the quotes were at the end of paragraph, but when I put them at the beginning of paragraphs a right double quote is input into the editor.
Suffice to note that I've also been using the tab key to input indentations to the beginning of each paragraph and when I tried the quotes on a paragraph without a tab, the left quote was input without needing the key combo. 
For test quotes 2 and 5 I used the key combo CTRL + K, 3 to insert a left double quote. All other test quotes were pure keyboard input.
Screenshot attached below.
![Screenshot_20210830_122505](https://user-images.githubusercontent.com/7231909/131393755-7b36ea6f-1707-47ab-b785-9c7fbbcf096d.png)

**Comment by vkbo** [comment]
Hmm, it is a bit hard to tell, but it looks like the auto-replace is making mistakes here. Can you copy/paste that exact piece of text you show on that screenshot into a comment? Preferably wrapped in block code tags (three backticks) so I can copy them over and figure out what's going on.

This definitely looks like a hug of some sort. I'll reopen the issue ticket.

**Comment by kalrach** [comment]
No problem, here you go, I'm running on Linux if that helps at all as well.
`
	”Test quote 1”
	“Test quote 2”
“test quote 3”
> ”test quote 4”
> “test quote 5”
Test text “Test quote 6”
`

**Comment by kalrach** [comment]
`	”Test quote 1”
	“Test quote 2”
“test quote 3”
> ”test quote 4”
> “test quote 5”
Test text “Test quote 6”`

Here you go, the first time the markdown came out weird on Github. I'm running on Linux if that is any help.

**Comment by kalrach** [comment]
And the markdown is still coming out weird. I can assure you its a pure copy and paste from the program.

**Comment by vkbo** [comment]
Thanks! I fixed the markdown. I'll see if I can debug this.

**Comment by vkbo** [comment]
Ok, so it is definitely the auto-complete making a mistake. It is sometimes giving you a closing quote instead of an open quote.

The logic is fairly simple. If the quote follows a space or is the first character on a line, it is replaced with an open quote. Otherwise it's replaced with a closing quote.

The tab thus gets a closing quote, and so does the `>`. The former is easy to fix as I can also check for tab. The latter needs to figure out what the `>` is for before making a decision, but I can probably figure out something that is fast (this code is run every time you hit a key, so it needs to be fairly fast).

**Comment by kalrach** [comment]
Sounds good! Glad you were able to get to the bottom of it quickly, and I will keep the sidenote in mind!

**Comment by vkbo** [comment]
I believe I've fixed it now. It seems to work. Any combos I've missed?
![image](https://user-images.githubusercontent.com/1619840/131405276-bab6f8c3-db0b-4d8e-a14e-547ed4abb288.png)

I'll make a 1.4.2 release tomorrow when I've added some test coverage for it too.

**Comment by kalrach** [comment]
I think those cover it! Thank you!

**Comment by vkbo** [comment]
Fixed and 1.4.2 released. It's quite late here, so hope I didn't make any mistakes, but it looks ok.
