### ISSUE TITLE
[Bug] [Tag ref] NW does not recognize created reference

### ISSUE THREAD

**Issue by Ellipsine** [vkbo/novelWriter#891]
I use Novel Writer since the early version of this amazing software. I realy love the plain text files approach, everyting is writing in "hard", not stuck on a database (and the others features as well like a customizable colors interface as I work in a brownish grey color for my eyes). So I created my characters files to make "POV" tags, my chronological timeline to make a "Time" tag and so on. But in every single version of the software, the tags feature does not function properly : NW considers that my tags files are not created at all. 

- I had built and rebuilt my index thanks to the F9 touch every time. 
- My Python is up to date. The previous versions of NW where a manual Python install was not mandatory did not work either but I may have a problem without knowing it as I don't know how to use the Python consol.
- I work on Windows 10 and I know, my computer may have a soul of its own since it loves to make strange things.

![Capture d’écran 2021-09-12](https://user-images.githubusercontent.com/69767820/132992633-b03c63a2-46dd-483f-bb7d-a1afe2e9ede0.jpg)

What can I do to make it work properly ? I still can use my favorite writing tool but without one of its feature.

**Comment by vkbo** [comment]
Oh, this is not an issue with Python or Windows. It seems you are juts missing the actual tag.

You must define a tag by setting `@tag: Ardal` in the file where Ardal is described. Then you can make references to Ardal in other documents by adding `@pov: Ardal` or `@char: Ardal` etc. If there is no `@tag: Ardal` defined anywhere, then you will get this error when you try to click the reference. In this case, rebuilding the index doesn't change anything.

I realise that it isn't immediately obvious to everyone how tags and references work. It is described in the documentation, but it is only available in English at the moment. @jyhelle has made a French translation of an earlier version of the manual, but it is already a bit outdated.

I am planning to make it easier to create character notes and setting these things automatically. I want to add it very soon.

**Comment by vkbo** [comment]
I have a proposal for how to improve the user experience of tags and references in #823. Feel free to add suggestions if you have any!

**Comment by Ellipsine** [comment]
Oh my, it was so simple in fact, it needed to create the inital connexion to say "where this mention leads" .  Thank you :)  And I will look at it , thank you for your work !

**Comment by vkbo** [comment]
Glad to hear it is resolved. I'm closing this issue then :)
