### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#892]
It is possible to add themes at the moment, but they have to be made directly in the assets folder in the source code. Perhaps it is a good idea to allow themes to be added into a system data folder from within novelWriter.

A small dialog can take care of that part. But it may also be a good idea to add a theme editor.

**Comment by Ellipsine** [comment]
I would agree for anything that facilitate customisation. I think customisation is important as we spend hours on a writing software.
Right now I copy my assets custom files and duplicate them in the asset folder as soon as I intall a new version of NW.

**Comment by vkbo** [comment]
I also accept new themes as contributions. I've already added the Solarized Light and Dark themes from another user.

**Comment by Ellipsine** [comment]
Understood  ! I don't know if it fits to everyone taste but here my custom themes : 

I would call it "warm grey" to keep eyes from the bright of white, from the dark theme which hurts astigmate eyes, or overly saturated colors of the solarize theme and cut a maximum of blue screen color. 
- GUI : [Warm Grey GUI dl](https://drive.google.com/file/d/1gfosdw2_6tI_zXk_Zt_32D5h6Ekxwb4Z/view?usp=sharingl)
- SYNTAX : [Wargrey Syntax dl](https://drive.google.com/file/d/1cH0o9nTQVWCPZI6otvU7fzMmRb2JVnJP/view?usp=sharing)

**Comment by vkbo** [comment]
Thanks! I'll have a look at them. I'm currently rewriting the whole theme code, so I'll leave it until after.

From version 1.6 you should be able to add user themes. I think I will make a full GUI for it since it's just a series of colour settings.

**Comment by Ellipsine** [comment]
> 
> 
> Thanks! I'll have a look at them. I'm currently rewriting the whole theme code, so I'll leave it until after.
> 
> From version 1.6 you should be able to add user themes. I think I will make a full GUI for it since it's just a series of colour settings.

Seems perfect to me, thank you a lot !

**Comment by vkbo** [comment]
The option to save user-defined themes in the local app data folder is added to 1.6 Beta 1. This means there is no need to add files to the assets folder in the source. The documentation needs to explain how to do it. I will finish this for the next Beta release of 1.6.

**Comment by vkbo** [comment]
PR #984 adds the needed information to the documentation. I'm closing this issue now. The idea of making a special tool for managing and editing themes has been split out into issue #985.
