### ISSUE TITLE
Global search

### ISSUE THREAD

**Issue by Ellipsine** [vkbo/novelWriter#894]
I have a feature suggestion : a global search tool. 
Right now, the searching feature only looks inside the opened document but it would be convenient to be able to search something in the whole project. 
Sometimes, I have a urgent question while writing, some informations to check and the search tool does not allow me to look for it on my whole project.
For example, my last project weight something like 1 million words and a lot and a loooot of chapters to open to look for my informations. I had to open the content folder in Sublime Text to search with the fuzzy tool. 
Is it possible ton implement it ?

**Comment by vkbo** [comment]
That is absolutely possible. I have it on my own todo list in fact. I sometimes need it myself although my projects aren't quite that large!

It is not a very difficult feature to write, so I can probably squeeze it in for the 1.6 release. I want to implement some improvements suggested in #645 to the current search tool at the same time.

In the meantime, there is a button in the in-document search tool that will switch on continuing the search in the next document when reaching the end. It is easier than manually opening all chapters. It's the button with the down-arrow below.

![image](https://user-images.githubusercontent.com/1619840/133040149-8a257573-b53e-4268-a76b-edafe8bd4174.png)

**Comment by Ellipsine** [comment]
It is perfect thank you very much ! 
I combine four books from the same serie and I treat them like a whole, that's why I have so many words :)

**Comment by tmarplatt** [comment]
This may sound niche: if the user could refine a global search further by somehow specifying which documents (or type thereof) to search, that would potentially remove much noise from search results, especially in large projects.

Think of "I want to search only notes" or "I want to search all my files marked as Finished". But perhaps the best approach would be to first be able to filter-select all desired files in the project tree (assuming multifile selection is implemented) according to such a criteria, and _then_ do a global-but-only-for-selected-files search.
