### ISSUE TITLE
[Enhancement] To get the numbers of words of a selected text

### ISSUE THREAD

**Issue by Ellipsine** [vkbo/novelWriter#896]
I would like to be able to count how many words contains a section of a selected text for my statistics or for a publication with a limited number of words without creating a new document. I know it is not a vital point but it would be convenient :)

**Comment by vkbo** [comment]
Sure, I can add that. It's pretty simple.

If the text you want the word count of is under its own heading, you can also see the word count for the heading in the Outline tab.

**Comment by vkbo** [comment]
Note to self for implementation:

Add a "Selected" section on the status bar that will show information about selected text when there is a selection, and some placeholder when not. Something similar to what VSCode does.

**Comment by vkbo** [comment]
This feature has been merged to the `main` branch will be included in release 1.6, and the pre-releases.

The way I implemented it in the end is that the word counter in the document footer will show the selected word count when there is a selection in the document, and the full word count when there is none.
