### ISSUE TITLE
Editor ignoring themes on Mint XFCE

### ISSUE THREAD

**Issue by GuAcH0** [vkbo/novelWriter#897]
Hi, I am using Linux Mint 19.1 XFCE. The editor (where you actually type) ignores all themes (ex. Default Dark Theme) and remains white with black text. I tested this with a bootable usb of Mint 20 XFCE, with all default system settings, and reproduced the same behaviour.

I tried editing the theme.conf files (ex. /usr/lib/python3/dist-packages/novelwriter/assets/themes/gui/default_dark/theme.conf) and there are palettes for the window, and the base, but not the editor. I also didn't see anything in /gui/theme.py. It seems like the editor is handled differently than other palettes, so I am not sure how to proceed. I am not sure where the problem lies (with xfce, qt5, the app itself?). Any ideas are appreciated (and thanks for making this app - It is amazing!)

**Comment by vkbo** [comment]
The syntax theme is selected separately from the GUI theme since there are a lot more options for syntax themes. You will find it in the "Highlighting" tab in Preferences.

![image](https://user-images.githubusercontent.com/1619840/133736010-aecc1c8c-dd4c-4d6b-bd14-840a09f0d40c.png)

**Comment by GuAcH0** [comment]
Sorry for putting the bug tag. I didn't know that highlighting refers to the editor. Thank you!

**Comment by vkbo** [comment]
Not at all a problem. Glad it was sorted out. :)

**Comment by tmarplatt** [comment]
Relevant to this genuine mistake, perhaps it's more user friendly to group all theme settings under the General tab in Preferences.

If that's unacceptable, how about adding a note under General tab > Look and Feel, where it states that the user will also find another theme to configure under "Highlighting"?
