### ISSUE TITLE
1.5RC1 deb install doesn't launch on Linux Mint 20

### ISSUE THREAD

**Issue by dchurch315** [vkbo/novelWriter#898]
Did an install of the new deb file (thank you BTW) and it crashes on launch with the following error:

```
Traceback` (most recent call last):
  File "/usr/bin/novelwriter", line 33, in <module>
    sys.exit(load_entry_point('novelWriter==1.5rc1', 'gui_scripts', 'novelwriter')())
  File "/usr/bin/novelwriter", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_novelwriter.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/novelwriter", line 33, in <module>
    sys.exit(load_entry_point('novelWriter==1.5rc1', 'gui_scripts', 'novelwriter')())
  File "/usr/bin/novelwriter", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

Perhaps a dependency is missing on Mint?

**Comment by vkbo** [comment]
Hmm, interesting. It seems to be crashing before reaching novelWriter. The install step is done using easy_install and setuptools, so perhaps there is a dependency issue there.

It should do exactly the same as `pip install` does at that point in the installation. Does pip install work?

**Comment by vkbo** [comment]
Ok, it seems here that it may be an issue with imports, even if the backtrace is somewhat cryptic: https://github.com/pypa/setuptools/issues/2390#issuecomment-703142579

I'll try and spin up a virtualbox with mint and see if I can find out what's going on.

**Comment by vkbo** [comment]
Oh, wait, I think I see it.

```python
Traceback` (most recent call last):
  File "/usr/bin/novelwriter", line 33, in <module>
    sys.exit(load_entry_point('novelWriter==1.5rc1', 'gui_scripts', 'novelwriter')())
  File "/usr/bin/novelwriter", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

It seems it's looking for `novelWriter` with a capital `W`. I made everything lower case for the entry points to avoid such issues in the future, but if you've installed from pypi before, there may be remnants of the old upper case entry points. It happens when you have a mix of deb and pip installations of novelwriter.

If that is the case, the solution is to uninstall both with deb and pip versions, and reinstall the deb package. I had to do that on an ubuntu box.

There should be no mention of novelwriter in `pip3 freeze`.

**Comment by vkbo** [comment]
Just tested it on a VirtualBox with a fresh installation of Mint 20.2/ It installs and runs without any issue. I noticed that mine too has the upper case "W" in the launch script, but it seems to not matter after all.

The only issue I can think of is a mix of pip and deb install, which I've had issues with before as I mentioned. If that is the case, let me know if the suggestion from my previous comment works.

**Comment by dchurch315** [comment]
Spot on - I had an older version installed thru PIP - removed and reinstalled the DEB and everything is running. Thanks for the assist.

**Comment by vkbo** [comment]
Thanks for the update. It's good to get confirmation. I'll keep testing the deb packages on Mint, and add a bote about the pip conflict in the docs.
