### ISSUE TITLE
Unlocalised string "Save" under Project Settings > Auto-Replace

### ISSUE THREAD

**Issue by tmarplatt** [vkbo/novelWriter#919]
There is a non-localisable string "Save" in the Save button under Project Settings dialog > Auto-Replace. The translation files however have a specific token for "Save entry" which apparently is unused.

![Screenshot](https://user-images.githubusercontent.com/16073344/139513238-a8e1ffef-2b79-4eab-afb2-a9ded12bacc1.png)

**Comment by vkbo** [comment]
Thanks!

Since there are already Save buttons on the dialog, fixing this should not introduce more strings that need translation.
