### ISSUE TITLE
Improve the reference panel

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#925]
The reference panel below the document viewer could do with a bit of an update. It is a very old feature that hasn't been given much attention since it was first added. It is a bit confusing, and so are the two buttons "References" and "Sticky" associated with it. See comments in #923.

I propose to:

* Add a more obvious show/hide button for the panel.
* Move the "Sticky" button into the panel itself, and add a descriptive heading on the panel with the sticky button next to it.
* Add some placeholder text in the case where there are no references to show.
* Consider changing how the references are listed, perhaps with a compact/detailed view option.

**Comment by tmarplatt** [comment]
By default the open reference panel extends to considerable screen real estate, for what it currently holds. Can its height be dynamically set depending on its contents?

**Comment by vkbo** [comment]
The vertical size of the panel is adjustable. The default size is a proportion of the window height, but it should remember its previous setting after that.

**Comment by vkbo** [comment]
If anyone's interested, I'm working on the new reference panel functionality for 2.2 now. Here's a video of the code so far. Still has a few issues, but mostly works as intended. This also demonstrates the auto-complete feature for references.

https://github.com/vkbo/novelWriter/assets/1619840/0626f433-02da-42c8-8447-f444d49e499c
