### ISSUE TITLE
Recovering old files

### ISSUE THREAD

**Issue by Charabistouille** [vkbo/novelWriter#932]

**Comment by vkbo** [comment]
I see you deleted the text of your issue. Does that mean you figured it out?

The .bak file you originally mentioned only contains a copy of the old good project file, not the text of your documents. If you've deleted them (not just put them in the trash folder) they can only be recovered from a backup.

**Comment by vkbo** [comment]
Since you deleted the text and haven't responded, I'm closing this. If you have any more questions, please make a thread in the [Discussions](https://github.com/vkbo/novelWriter/discussions) section.
