### ISSUE TITLE
Document label emphasis not updated after changing heading level 

### ISSUE THREAD

**Issue by tomatic** [vkbo/novelWriter#935]
It seems the optional document level highlighting (bold + underline) isn't updated when changing a document's heading level from a chapter to a scene.

**Steps to reproduce:**

1. Make sure the setting _Emphasize partition and chapter labels_ in _Preferences -> General -> GUI settings_ is enabled.
2. Open a chapter (level 2) document in the editor. The document label in the tree should be emphasized (bold + underlined).
3. Change the heading level from `##` to `###` and close the document.

**Expected result:**

The emphasis is removed from the document label in the tree, indicating that the document is now neither a partition nor a chapter.

**Actual result:**

The document label retains its emphasized state. This only disappears if you either disable and re-enable the emphasis setting in _Preferences -> General -> GUI settings_ or close and re-open the project.

**Note:**

If you do it the other way around, i. e. change a scene to a chapter (changing the heading from `###` to `##`), it works as expected: the document label gets bolded + underlined when you close the document.

**Comment by vkbo** [comment]
Confirmed. In fact, the icon changes colour, it is just the text that doesn't.

I just released a patch on Sunday, so bad timing, but I'll group up a few minor issues and there will probably be a 1.5.3 patch soon.

Thanks!
