### ISSUE TITLE
Dark Modes don't affect the Editor

### ISSUE THREAD

**Issue by tosho** [vkbo/novelWriter#938]
I'm running Ubuntu 20.04.3, just installed novelWriter and tried to change the theme.
Switching to any of the 2 Dark Modes works for the GUI but not for the Editor.
![novelWriter](https://user-images.githubusercontent.com/1470742/147274881-083cbc1f-2ff3-4b2c-a63f-72ff8d1d8c21.png)

**Comment by vkbo** [comment]
The editor theme and syntax theme are separate settings. Just pick a dark theme for the syntax theme as well, and you're all set. :)

**Comment by vkbo** [comment]
PS: The syntax theme setting and related options are in the "Highlighting" tab of the settings.

**Comment by tosho** [comment]
Yeah, I found. 
I'm an idiot :)
