### ISSUE TITLE
Suppress hard line break in build output where carriage returns exist in source

### ISSUE THREAD

**Issue by bertput** [vkbo/novelWriter#944]
Currently it appears that carriage returns in the markdown source result in hard line breaks in the build output, because the build tool places two spaces at the end of every line of build output.

Can you provide functionality to suppress those double-spaces, perhaps controlled by a new switch in the build dialog?
I've linked the discussion for reference.  Thank you.

### Discussed in https://github.com/vkbo/novelWriter/discussions/939

<div type='discussions-op-text'>

<sup>Originally posted by **bertput** December 28, 2021</sup>
Hello,

As I understand the markdown syntax, if two lines flow one after the other without a blank line in between, the text should flow in the rendered output or (I guess) the preview.  I think this is mentioned in another question but that turned into a discussion about MD vs. other formats.

Specifically, if I write some text like this:
```
these are some very
short lines
of text.
```
then I would expect it to render like this:
```
these are some very short lines of text.
```

Only an empty line should cause a hard line break, but I'm not seeing that.  Instead I see line breaks at the end of each line.
If there is a setting that I'm missing, I'd appreciate a pointer to it!  Thank you!

Regards,    Bert
</div>

**Comment by vkbo** [comment]
Feature added for inclusion in 2.4
