### ISSUE TITLE
Exporting only one or two documents is difficult

### ISSUE THREAD

**Issue by Ellipsine** [vkbo/novelWriter#971]
I am sorry to make many request in a row. 

Right now, I have a little problem : to construct an epub for my novel, I want to use Sigil and convert it with Calibre (PDF, DOCX).  It is really easy with a small amount of CSS and HTML. 

However, to generate page breaks as a PDF, I need to create different html pages in Sigil. But NW only allows me to export the whole novel, so I have a big html file and I can't choosing only one page in NW, or only a small amount of them. 

The solution right now is to check every "include/exclude in export" manually. It is quite tedious because I have to do it one by one. 

**Idea 1** : It would help to allow multiple selection of documents to change the "publication" statut at the same time. 

**Idead 2** : If not possible, is it possible to add a dialogue option in the "construct novel" window ? It could look like this : 

-> [ ] export every checked Document 
-> [x] or select them manually  
---->[ ] Doc 1 
---->[x] Doc 2
---->[x] Doc 3
---->[ ] Doc 4

Is it possible to do something about this issue ? Thank you for your work :)

**Comment by vkbo** [comment]
> I am sorry to make many request in a row.

Don't be! These are good suggestions :)

I actual;ly plan to make such an addition, so I'll tag this as part of the planned upgrade og the Build tool.

**Comment by Ellipsine** [comment]
> Don't be! These are good suggestions :)
> 
> I actual;ly plan to make such an addition, so I'll tag this as part of the planned upgrade og the Build tool.

Thank you  ! *frolicing happily*
