### ISSUE TITLE
Allow user to save file templates

### ISSUE THREAD

**Issue by vkbo** [vkbo/novelWriter#996]
This is not the same as #841, which concerns project templates, but they are related.

The user should be allowed to add a bunch of template files that can be loaded when a new file is created.

For myself the use case would be a character template. The template files could be saved either as a project template or as a general template in the app data folder. There should be a way to add custom fields to the template. In particular `%label%` and `%tag%`.

**Comment by xahodo** [comment]
Yes, this would be useful. It would also really help me with my current project. When working on notes, I would really love to be able to import a template.

Templates regarding f.e. characters, would be different than templates for locations.

Allowing different templates to be loaded based on where they are created, would be great (saves clicks)! This would mean that creation of a project note in the "character" root folder would yield a different result than in the "objects" root folder.

Another option could be to have an "create note with template" item in the "+" drop-down menu.

Yet another option could be to simply add a menu item to import a template for current dialog, which would then open a file dialog where the user can select a template to load. However, this would be quite cumbersome to the user.

I do not understand what you mean with "custom fields". Could you elaborate?

**Comment by vkbo** [comment]
The idea is to add a new root folder for templates, which populates the "+" menu in the tree.

The fields are for instance:

```md
### %label%

Bla bla bla
```

Where the document label (name) will be inserted where `%label%` is. You fill this out when you create a new item in the project.

I will probably use `{Label}` instead, to be consistent with the new syntax for variable inserting.
